### ISSUE TITLE
Cortex Shuts down

### ISSUE THREAD

**Issue by ramsys28** [Emotiv/cortex-example#10]
Operating system: MACos
Cortex version: latest

I made a wrapper in python... see code: 
python client.py
import sys
import websocket
import ssl
import time
import thread

ws = websocket.WebSocket(sslopt={"cert_reqs": ssl.CERT_NONE}) #edw einai auto pou sou elega me ton none cert
ws.connect("wss://emotivcortex.com:54321")
file1 = open('js_session.txt', 'r')
def client_func(sendquery):

    ws.send(file1.read()) #apostolh pros emotivcortex.com
    result1 = ws.recv()
    for i in range(2):
        
        ws.send(sendquery)
     
        result = ws.recv()    #apanthsh apo emotivcortex.com
        with open("test.txt", "a") as myfile:
            myfile.write(result + "\n")
        print(result)
    return
file = open('json.txt', 'r') 
client_func(file.read()) 
  
    
which I call it from matlab inside a while true loop. However after 50-100 iterations (calls in websocket) the cortex shuts down. 

---

**Comment by nguoithichkhampha** [comment]
Hi @ramsys28 ,
what is the request which you sent to Cortex ?

**Comment by ramsys28** [comment]
Hi,
I sent this through matlab 

['{"jsonrpc": "2.0","method": "subscribe","params": {"_auth": "' json_auth.result.x_auth '","streams": ["pow"]},"id": 1}']);
