### ISSUE TITLE
Usubscribe stream eeg with session <sessionID-here> fail.

### ISSUE THREAD

**Issue by ksjacobs** [Emotiv/cortex-example#100]
Operating system: Windows 10
Last upstream commit (run `git log --author="Robert Lord" | head -n 1`): N/A
language version:  python
Cortex version:  N/A

---

I am having an issue unsubscribing to raw eeg data. I can create a stream, subscribe and collect the raw eeg data and everything works fine. But when I try to unsubscribe it fails. (I have tried running it in a while loop and after more than 2000 tries it still gives me the same result).

 I am also having issues closing sessions. I may take close to 200 tries before the session actually closes. 

The JSON I send in order to unsubscribe: 
{
    "jsonrpc": "2.0",
    "method": "unsubscribe", 
    "params": {
        "_auth": token,
        "streams": [
            "eeg"
        ], 
        "session": sessionID
    }, 
    "id": id
}

The JSON I send to close session:
{
    "jsonrpc": "2.0", 
    "method": "updateSession", 
    "params": {
        "_auth": token,
        "status":"close", 
        "session": sessionID
    }, 
    "id": id
}

The response when I try to unsubscribe is either an eeg-event or:
{
  "jsonrpc": "2.0",
  "id": id,
  "result": [
    {
      "message": "Unsubscribe stream mot with session <sessionID> fail"
    }
  ]
}

And when I try to close session I then either get belated Unsubscribe-messages or eeg-events.

**Comment by Finenicedy** [comment]
Received: Internal JSON-RPC error.
Message Error recieved from CortexAccess.CortexClient
Recieved: -32603 : Internal JSON-RPC error.
I have trouble in Authorize.Can you help me to slove it,please.
