### ISSUE TITLE
Training Data is not synced across devices 

### ISSUE THREAD

**Issue by jayjagtap** [Emotiv/cortex-example#101]
Emotiv Cortex Version: 1.8.1
OS: Windows 10

Training data done on one device(Computer 1) is not synced with other devices (Computer 2).
Profile loaded from python code reflects trained profile on Computer 1 but not on Computer 2.
We have waited for 2 days but the data is not synced.

**Comment by bchaperon** [comment]
Can you see your training data on computer 2 with [EmotivBCI](https://www.emotiv.com/emotiv-bci/)?
If not, then please contact the [Emotiv customer support.](https://www.emotiv.com/contact-support/)
