### ISSUE TITLE
How can we understand that epoc + is off

### ISSUE THREAD

**Issue by guneteroglu** [Emotiv/cortex-example#103]
During a session, when the charge of epoc+ is finished, or when it is closed, how can we understand it in MainActivity.java
and handle this situation in Cortex API Band Power interface?

**Comment by nguoithichkhampha** [comment]
@guneteroglu , our example does not handle all the exception case. it just a small demo, how to work with Cortex API. want to know headset is off, better to call API "queryHeadset". if don't see the headset in response, that mean headset is off.
