### ISSUE TITLE
Comparing a freshly recorded training (e.g Push) with recorded data from profile

### ISSUE THREAD

**Issue by edi4101** [Emotiv/cortex-example#104]
Hello, 

I wanted to know, how it is possible to compare a live "mental training" stream with the recorded training data from a profile, to see if the live input stream matches the recorded data. (e. g for moving a object in unity)

Which functions from Cortex API i can use for that? Or is there another way to realize sth like that.

Greets 

Eduard

**Comment by duytan90** [comment]
Hey @edi4101, we can't do that now since a headset can only connect to one application while it's in use.

**Comment by edi4101** [comment]
But in my case its the same application :) 

I just need to implement a mechanism to move a object in unity if a certain mental command (which was trained before) is recognized

**Comment by edi4101** [comment]
Like the "Live Mode" in Emotiv BCI

**Comment by duytan90** [comment]
Responses from subscribing `com` event (https://emotiv.github.io/cortex-docs/#com-event) contains action and power, perhaps you can map MC action to box's direction and how far will it be?
```json
{
  "com":[
    "push",
    0.673717498779297
  ],
  "sid":"46d18597-7034-40ab-9d6e-d617a89a24ce",
  "time":245.356536865234
}
```

**Comment by orenhoxha** [comment]
Hello,
I am I trying a create a similar application as you @edi4101 and I have the same problem. I want to create something similar to the "Live Mode" in EmotivBCI but cannot find a way to properly connect to a specific profile(one that I have trained) and then check if a command is recognized. 
If you have found the solution to this problem, could you please help me?
NOTE:  @duytan90 , I have read your response but I don't see any connection between the power of the command and the what we have trained our profile, therefore I'm a bit lost.
Thanks :)

**Comment by edi4101** [comment]
Hey @orenhoxha 
So I got an answer from the support. As I understand, you have to use also the community sdk (EmoEngine) from GitHub, where there is an EventHandler for the Mental Command Detection.

Here are some the links they sent me:

https://emotiv.zendesk.com/hc/en-us/articles/201483705-Understanding-the-Mental-Commands-Detection-Suite

https://emotiv.zendesk.com/hc/en-us/articles/201508605-Example-4-CognitivDemo

https://emotiv.zendesk.com/hc/en-us/articles/201216335-Training-Mental-Commands
