### ISSUE TITLE
Performance Metrics values on cortex-app and EmotivPro app (Difference?)

### ISSUE THREAD

**Issue by aitoey** [Emotiv/cortex-example#105]
Operating system: Microsoft Windows 10 Enterprise
language version: C++
Cortex version: latest

Hello,

I am developing an application in which I am reading the **Performance Metrics** values.

My question is: The performance metrics values that I am reading on my application are the same as the ones that appear on the Performance Metrics live-screen of the EmotivPro program or EmotivBCI but in a 0-1 scale rather than in a 0-100 scale?

The question is very important for me, so I appreciate if anyone knows it.

Thank you,

AT.

**Comment by nguoithichkhampha** [comment]
@aitoey correct value of Performance Metrics in range 0-1. Emotiv and BCI just scale this value 10 times with rounding.

**Comment by aitoey** [comment]
Perfect, thanks a lot @nguoithichkhampha !
