### ISSUE TITLE
Invalid Client Credentials

### ISSUE THREAD

**Issue by 122671644** [Emotiv/cortex-example#106]
![image](https://user-images.githubusercontent.com/57382388/89127539-c3de0a80-d520-11ea-8bd5-7bcb1afb3517.png)
![image](https://user-images.githubusercontent.com/57382388/89127550-d35d5380-d520-11ea-811d-482ca1a501cd.png)

I have applied for the ID and password on the website. Why is the display invalid? My license will expire in about two years

**Comment by 122671644** [comment]
> I have applied for the ID and password on the website. Why is the display invalid? My license will expire in about two years

"D:\python inter\python.exe" D:/EPOC/time/record.py
query headset --------------------------------
EPOCPLUS-4A2C0521
connect headset --------------------------------
connect headset result {
    "id": 2,
    "jsonrpc": "2.0",
    "result": {
        "command": "connect",
        "message": "The headset EPOCPLUS-4A2C0521 has been connected or is connecting."
    }
}
request access --------------------------------
Traceback (most recent call last):
  File "D:/EPOC/time/record.py", line 63, in <module>
    r = Record()
  File "D:/EPOC/time/record.py", line 7, in __init__
    self.c.do_prepare_steps()
  File "D:\EPOC\time\cortex.py", line 190, in do_prepare_steps
    self.authorize()
  File "D:\EPOC\time\cortex.py", line 122, in authorize
    self.auth = result_dic['result']['cortexToken']
KeyError: 'result'
{
    "id": 3,
    "jsonrpc": "2.0",
    "result": {
        "accessGranted": false,
        "message": "The user has not granted access right to this application. Please use EMOTIV App to proceed."
    }
}
authorize --------------------------------
auth request 
 {
    "jsonrpc": "2.0",
    "method": "authorize",
    "params": {
        "clientId": "W9hdBsammVdJJSFi7frdym8sAmWKJv7PFIvnKObV",
        "clientSecret": "PDGOShuQtksUsGUw5xxzNge7aHwTRirVKVZNyPmwFJCJmQjFYxZUp74PMTn1nY7eiXRVuNiCXT5bXw8MkTkFHskV7LF0rzmXZlOPDgqgyHdKH0HQktXPb0yEDuQFWNUy",
        "license": "9f728e8b-8ba1-4c8b-8e4d-d3c506e709cc",
        "debit": 100
    },
    "id": 4
}
auth result 
 {
    "error": {
        "code": -32102,
        "message": "You have no access rights to the Application."
    },
    "id": 4,
    "jsonrpc": "2.0"
}

**Comment by nguoithichkhampha** [comment]
`"message": "You have no access rights to the Application."`
you have to accept request from Emotiv app first.
https://emotiv.gitbook.io/cortex-api/authentication/requestaccess
