### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError  Nodejs Example

### ISSUE THREAD

**Issue by joseph27** [Emotiv/cortex-example#107]
Operating system: MAC OS 10.13.1
language version:(nodejs version) v10.15.3
Cortex version:   1.8.1

---
Greetings,
I'm trying to work with Node js Example but I get an error 

Youssefs-MacBook-Pro:nodejs Joseph27$ node index.js
method:  inspectApi  needs auth:  false
method:  CortexVersion  needs auth:  false
method:  generateNewToken  needs auth:  false
method:  createSession  needs auth:  true
method:  updateSession  needs auth:  true
method:  querySessions  needs auth:  true
method:  deleteRecord  needs auth:  true
method:  updateNote  needs auth:  true
method:  queryHeadsets  needs auth:  false
method:  updateHeadset  needs auth:  true
method:  controlBluetoothHeadset  needs auth:  false
method:  authorize  needs auth:  false
method:  injectMarker  needs auth:  true
method:  getDetectionInfo  needs auth:  false
method:  training  needs auth:  true
method:  getTrainingTime  needs auth:  true
method:  getTrainedSignatureActions  needs auth:  true
method:  mentalCommandGetSkillRating  needs auth:  true
method:  mentalCommandActionSensitivity  needs auth:  true
method:  mentalCommandActionLevel  needs auth:  true
method:  mentalCommandActiveAction  needs auth:  true
method:  mentalCommandBrainMap  needs auth:  true
method:  mentalCommandTrainingThreshold  needs auth:  true
method:  facialExpressionSignatureType  needs auth:  true
method:  facialExpressionThreshold  needs auth:  true
method:  setupProfile  needs auth:  true
method:  queryProfile  needs auth:  true
method:  getCurrentProfile  needs auth:  true
method:  login  needs auth:  false
method:  logout  needs auth:  false
method:  getUserLogin  needs auth:  false
method:  acceptLicense  needs auth:  true
method:  getLicenseInfo  needs auth:  true
method:  configMapping  needs auth:  true
method:  subscribe  needs auth:  true
method:  unsubscribe  needs auth:  true
method:  decryptData  needs auth:  true
(node:20377) UnhandledPromiseRejectionWarning: TypeError: client.init(...).queryHeadsets is not a function
    at client.ready.then (/Users/Joseph27/Desktop/EEG project/cortex-example-master/nodejs/index.js:7:4)
(node:20377) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20377) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I have noticed that Cortex UI application logs out once I run the code and when re-login nothing happens.

**Comment by kinghaseo** [comment]
@joseph27  what was the solutions to this ?
