### ISSUE TITLE
Error -32018 with Cortex Examples 

### ISSUE THREAD

**Issue by zlz0731** [Emotiv/cortex-example#108]
Operating system: WIN10
Last upstream commit : Cortex Example
language version:(nodejs version, ruby version ....) C++
Cortex version: V1.8.1 - X86

I ran the version of cortex example-cpp-qt and encountered the following problem. Qt reported that it was missing the required parameters. How to solve this problem?
 I would really appreciate it if someone could point me in the right direction. Thanks again
![BD55E92F%403E9FE10B 7962B05C_recompress](https://user-images.githubusercontent.com/49619194/56096872-0e003e80-5f20-11e9-82f5-d8885279332c.jpg)

**Comment by bchaperon** [comment]
When you call the method "createSession", you need an additional parameter "sensors" for the Epoc Flex.
So in the source code, you need to update the method CortexClient::createSession and add this parameter.
See the documentation for details https://emotiv.github.io/cortex-docs/#createsession
