### ISSUE TITLE
EEGLAB File

### ISSUE THREAD

**Issue by joseph27** [Emotiv/cortex-example#109]
Greetings,

I have Emotiv insight paired with Bluetooth, I would like to know how can I generate EDF or CVS file that is compatible with EEGLAB using Cortex SDK with Node js, I was able to extract the data from the SDK

("COUNTER_MEMS": 0.00,"GYROX": 0.00,"GYROY": 0.00,"GYROZ": 0.00,"ACCX": 0.00,"ACCY": 0.00,"ACCZ": 0.00,"MAGX": 0.00,"MAGY": 0.00,"MAGZ": 0.00,"int": 0.00,"str": 0.00,"rel": 0.00,"exc": 0.00,"eng": 0.00,"lex": 0.00,"foc": 0.00,"theta": 29.01,"alpha": 29.16,"betaL": 67.63,"betaH": 70.97,"gamma": 88.64).

But I want to know how I can display that data on EEG toolbox.

Thanks.

**Comment by marcelo-66** [comment]
Hello, help me please, as you got the brain signals I need to get those signals but with free software

**Comment by hoangphamemotiv** [comment]
hi @marcelo-66 
can you tell more clear on your issues?
if you have a EDF file from Emotiv data, you can load it in EEG lab. it is compatible. you can use EmotivPro to create a recording that can be exported to EDF and CSV files.
