### ISSUE TITLE
Authentication Problem

### ISSUE THREAD

**Issue by joseph27** [Emotiv/cortex-example#110]
Operating system: MAC OS 10.13
language version: Node.js
Cortex version: v1.81

A new issue has arisen in the last week for code that has not changed: JSONRPC internal errors thrown by attempting to call the authorize method in the Cortex SDK.

Whenever I run Numbers.js the Cortex UI kicks me and I have to login again so I decided  to enter the Auth Details and pass it to init() function

  const auth = {
    username: "myusername",
    password: "mypassword",
    client_id: "from my account details",
    client_secret: "from my account details",
    debit: 1 // first time you run example debit should > 0
  };

  client.ready.then(() => client.init(auth)).then(() =>
    numbers(client, avgWindow, averages => {
      const output = Object.keys(averages).map(k => 
        `${JSON.stringify(k)}: ${averages[k].toFixed(2)}`
        ).join(",");
  
    })
  );

I get this error

JSONRPCError: Internal JSON-RPC error.
    at Object.requests.(anonymous function) (/Users/Joseph27/Desktop/EEG project/cortex-example-master/nodejs/lib/cortex.js:187:32)
    at Cortex._onmsg (/Users/Joseph27/Desktop/EEG project/cortex-example-master/nodejs/lib/cortex.js:99:26)

**Comment by Finenicedy** [comment]
I have the same trouble

**Comment by Finenicedy** [comment]
Received: Internal JSON-RPC error.
Message Error recieved from CortexAccess.CortexClient
Recieved: -32603 : Internal JSON-RPC error.
