### ISSUE TITLE
Not able to create a Session

### ISSUE THREAD

**Issue by cherwag** [Emotiv/cortex-example#110]
I am using the Epoc X and trying to run the example.py file from the async folder. While creating the session is am getting the following error:

{"error":{"code":-32019,"message":"Session limit on this device has been reached."},"id":8,"jsonrpc":"2.0"}

Thank you in advance!

**Comment by nguoithichkhampha** [comment]
@cherwag , when get this error you need to call authorize again with debit param > 0.
Actually, our example set debit=None
`async def authorize(self, license_id=None, debit=None)`
so, in example.py. you can change
`await cortex.authorize(debit=10)`
