### ISSUE TITLE
Question: accessing data from EPOC 1.0 EEG

### ISSUE THREAD

**Issue by meta-meta** [Emotiv/cortex-example#111]
Operating system: Windows 10
Last upstream commit (run `git log --author="Robert Lord" | head -n 1`): 41a03139078cbbbde56a389c650947c83f2b4f39
language version:(nodejs version, ruby version ....) nodejs
Cortex version: 1.8.1

---

I have an older Emotiv EPOC Model 1.0 EEG Version. Using the current Cortex API, I'm unable to access motion data. I _am_ able to access at least `pow` or `met` (I don't recall which one and don't have it set up at the moment). How can I enable motion data and raw EEG? I would much prefer to use Cortex rather than the community-sdk as I am most familiar with nodejs.

I have asked this on Zendesk, but I would like a more detailed and technical answer than 
> Cortex UI will not support the data streams from older version software.

I will also post in community-sdk and link to this issue.

```
client.ready
.then(() => client.init())
.then(() => client.queryHeadsets().then((headsets) => {
console.log(headsets);
}))
```
console:
```
[ { connectedBy: 'dongle',
dongle: '565',
firmware: '565',
id: 'EPOC-000000CC',
label: '',
motionSensors:
[ 'GYROX',
'GYROY',
'GYROZ',
'ACCX',
'ACCY',
'ACCZ',
'MAGX',
'MAGY',
'MAGZ' ],
sensors:
[ 'AF3',
'F7',
'F3',
'FC5',
'T7',
'P7',
'O1',
'O2',
'P8',
'T8',
'FC6',
'F4',
'F8',
'AF4' ],
settings:
{ eegRate: 128, eegRes: 14, memsRate: 0, memsRes: 0, mode: 'EPOC' },
status: 'connected' } ]
```

**Comment by bchaperon** [comment]
I see "memsRate: 0, memsRes: 0" in the settings.
This probably means that the motion sensors are disabled.
Can you connect to your headset using [EmotivBCI](https://www.emotiv.com/emotiv-bci/) and see if BCI can display any motion data?

**Comment by meta-meta** [comment]
@bchaperon EmotivBCI exits when I click on the motion data tab. Everything else seems to work OK.

**Comment by bchaperon** [comment]
Hi @meta-meta
I just talked to our customer support and it seems that the problem is bit complicated, because you are using an old headset.
Could you contact the [Emotiv customer support](https://www.emotiv.com/contact-support/) directly for further assistance?
It would be easier for them to help you.

**Comment by meta-meta** [comment]
Thank you @bchaperon I've reached out to CS.

**Comment by meta-meta** [comment]
@bchaperon I finally had a remote support session with CS. 

> Thank you for your time in the remote session. 
Since the EPOC Model 1.0 does not support the Motion sensors of the BCI application, the application cannot run as expected. Therefore, this is not an issue but by design. 

Where can I get a straight answer whether my headset has a gyroscope or not? It was advertised as a feature.

https://emotiv.zendesk.com/hc/en-us/articles/200785669-What-are-the-features-of-the-EPOC-

> Limited edition design 
14 sensors plus 2 references offer optimal positioning for accurate spatial resolution 
Gyroscope generates optimal positional information for cursor and camera controls 
Hi-performance wireless gives users total range of motion 
Dongle is USB compatible and requires no custom drivers 
Lithium Battery provides 12 hours of continuous use

**Comment by hoangphamemotiv** [comment]
Hi @meta-meta 
can you tell me your headset version number? you can check it on a Emotiv app. 
every Emotiv headset has gyroscope, it is a part of motion. but each kind of headset or headset version, they will have different format. 
ie: with Epoc headset, Gyro just 2 directions Gyro X and Gyro Y. 
Epoc+ headset,  it is 9 channels: 3 channels Gyro X, Y, Z, 3 channels Accelerometers and 3 channels of Magnetometers. 
and something new with newest version of Epoc+ . you can check : https://www.emotiv.com/epoc/

**Comment by meta-meta** [comment]
EPOC 1.0 EEG Version

I got a response from customer support essentially saying that my headset has a gyroscope but the new cortex platform does not support that data format. They are hooking me up with access to Xavier control panel.

> with Epoc headset, Gyro just 2 directions Gyro X and Gyro Y.

Thank you, this is illuminating and unfortunate for how I wanted to use it. Oh well. Good to know it doesn't have full orientation tracking.
