### ISSUE TITLE
no viable overloaded operator[] for type 'QjsonValue '

### ISSUE THREAD

**Issue by gubeifang** [Emotiv/cortex-example#111]
I downloaded the sample data, I used CPP-QT, and then filled in Client Id and ClientSecret  in Config.h according to the document prompts. I used QT5.9.9 and VS2017. The following errors occurred during runtime. How can I solve these problems? thanks a lot.
![QQ图片20200811162912](https://user-images.githubusercontent.com/69452743/89875425-d2e34d80-dbef-11ea-85fb-d3d9dffbb402.png)

**Comment by nguoithichkhampha** [comment]
we recommend you work on new qt version. at least 5.13.
operator [] of QJsonValue added from Qt 5.10
https://doc.qt.io/qt-5/qjsonvalue.html#operator-5b-5d
