### ISSUE TITLE
Emotiv Cortex UI Error: Invalid license key

### ISSUE THREAD

**Issue by soufineyestani** [Emotiv/cortex-example#112]
Operating system: MAC 
language version:(nodejs version, ruby version ....) C++
Cortex version:  
---

I am trying to use Emotiv Cortex UI. When I am running "cortex examples.pro" from Qt Creator, I faced this problem "authorize" -32002 "Invalid license key." What I should do?
I am using the free version of Cortex.

**Comment by bchaperon** [comment]
Which example are you running? The EEG example requires a license. But the other examples should work.

**Comment by soufineyestani** [comment]
I used Cortex API example, but it didn't work.

**Comment by bchaperon** [comment]
Yes, but when you open the C++ examples in Qt Creator, you can see that the project contains 6 different programs: eeg, motion, training, marker, mentalcommand, facialexpressions.
You can select the program to run by clicking on the gray button in QT Creator, at the bottom left (just above the green arrow)
If you select "eeg" then you need a license key. But for the other examples, it should work without a license.
