### ISSUE TITLE
Socket error: QAbstractSocket::UnsupportedSocketOperationError

### ISSUE THREAD

**Issue by gubeifang** [Emotiv/cortex-example#113]
win10, use CPP-QT，QT5.14+VS2017，I filled in the ClientId, ClientSecret and HeadsetId according to the case prompts, and then an error occurred during the operation. Is there any way to solve this problem? thank you very much！
![image](https://user-images.githubusercontent.com/69452743/89973631-6457cb80-dc93-11ea-8982-b192d975cac3.png)

**Comment by bchaperon** [comment]
Hi @gubeifang 

When you start EmotivPRO or EmotivBCI, do they successfully connect to Cortex?

The Qt documentation says that this error can be related to IPv6.
Do you use IPv6 on your computer?
https://doc.qt.io/qt-5/qabstractsocket.html#SocketError-enum

In the file CortexClient.cpp at line 62, can you try to replace this line:
`socket.open(QUrl("wss://localhost:6868"));`
by this:
`socket.open(QUrl("wss://127.0.0.1:6868"));`

**Comment by gubeifang** [comment]
Hi
Thank you for your reply.
When i start EmotivPRO or EmotivBCI, they can successfully connect to Cortex



At 2020-08-14 12:39:20, "Benoit" <notifications@github.com> wrote:

Hi @gubeifang

When you start EmotivPRO or EmotivBCI, do they successfully connect to Cortex?

The Qt documentation says that this error can be related to IPv6.
Do you use IPv6 on your computer?
https://doc.qt.io/qt-5/qabstractsocket.html#SocketError-enum

In the file CortexClient.cpp at line 62, can you try to replace this line:
socket.open(QUrl("wss://localhost:6868"));
by this:
socket.open(QUrl("wss://127.0.0.1:6868"));

**Comment by gubeifang** [comment]
Hi
Thanks for  your reply.
When i start EmotivPRO or EmotivBCI,  they can successfully connect to Cortex ，But when I run the case code,EmotivPRO or EmotivBCI does not respond.
I don't use IPv6 on my computer,IPv6 on my computer is the original setting 
I used another computer to run this case code, and the same situation occurred
I replace 62 line by socket.open(QUrl("wss://127.0.0.1:6868"));and the same situation occurred

Qt keeps showing ：Socket error: QAbstractSocket::UnsupportedSocketOperationError

I have no idea to solve this problem
Looking forward to your reply again









At 2020-08-14 12:39:20, "Benoit" <notifications@github.com> wrote:

Hi @gubeifang

When you start EmotivPRO or EmotivBCI, do they successfully connect to Cortex?

The Qt documentation says that this error can be related to IPv6.
Do you use IPv6 on your computer?
https://doc.qt.io/qt-5/qabstractsocket.html#SocketError-enum

In the file CortexClient.cpp at line 62, can you try to replace this line:
socket.open(QUrl("wss://localhost:6868"));
by this:
socket.open(QUrl("wss://127.0.0.1:6868"));

**Comment by bchaperon** [comment]
So after you start the example code, PRO and BCI stop working?
It seems that your issue is similar to this other one https://github.com/Emotiv/cortex-v2-example/issues/112
@nguoithichkhampha is already investigating.

**Comment by gubeifang** [comment]
No, when I start the example code, PRO and BCI   working normal，

It's like whether I run the code has nothing to do with  PRO and BCI，
The code usage instructions say that EmotivApp will be prompted for authorization the first time the code is run correctly, but when I run the code, EmotivApp does not respond.
Is there a problem with my computer software environment configuration?
Looking forward to your reply again










At 2020-08-14 17:07:02, "Benoit" <notifications@github.com> wrote:

So after you start the example code, PRO and BCI stop working?
It seems that your issue is similar to this other one #112
@nguoithichkhampha is already investigating.

**Comment by gubeifang** [comment]
hi, Is there have any ways to solve this problem?



At 2020-08-14 17:07:02, "Benoit" <notifications@github.com> wrote:

So after you start the example code, PRO and BCI stop working?
It seems that your issue is similar to this other one #112
@nguoithichkhampha is already investigating.

**Comment by nguoithichkhampha** [comment]
@gubeifang , Can you setup a teamview session to figure out the problem ?

**Comment by gubeifang** [comment]
Yes，Please tell me when we setup a teamview session,thank you.



At 2020-08-18 10:29:00, "Cuong Trinh Manh" <notifications@github.com> wrote:

@gubeifang , Can you setup a teamview session to figure out the problem ?

**Comment by gubeifang** [comment]
hi , When do we start a teamviewer session？Please contact me at your convenience, I will follow the email message between 8 am and 10 pm at Beijing time



At 2020-08-18 10:29:00, "Cuong Trinh Manh" <notifications@github.com> wrote:

@gubeifang , Can you setup a teamview session to figure out the problem ?

**Comment by nguoithichkhampha** [comment]
@gubeifang , sorry for late response. Please email for me your team id/ pass 
cuong@emotiv.com
when you ready at 10 AM GMT+7, tomorrow

**Comment by gubeifang** [comment]
OK，my team id/ pass is 1 573 242 908/4kt69f
Looking forward to your help



At 2020-08-19 17:39:07, "Cuong Trinh Manh" <notifications@github.com> wrote:

@gubeifang , sorry for late response. Please email for me your team id/ pass
cuong@emotiv.com
when you ready at 10 AM GMT+7

**Comment by nguoithichkhampha** [comment]
@gubeifang , I mean , we will setup session tomorrow and you send these informations via my email before start.
Don't public it .

**Comment by gubeifang** [comment]
haha, ok, i get it . thank you



At 2020-08-19 18:08:38, "Cuong Trinh Manh" <notifications@github.com> wrote:

@gubeifang , I mean , we will setup session tomorrow and you send these informations via my email before start.
Don't public it .

**Comment by nguoithichkhampha** [comment]
the cause is missing openssl library when run with Qt example on windows.

**Comment by gubeifang** [comment]
Hello,
I'm a Emotiv Epoc+ user, I download "Emotiv-Installer-v3.2.0-x64.exe" from my Emotiv account
There was an error when I use it, like the picture show,I can't get the data
What should I do to solve this problem？
Look forward to your reply，thank you

**Comment by nguoithichkhampha** [comment]
@gubeifang this is reason for your error

> the cause is missing openssl library when run with Qt example on windows.

**Comment by gubeifang** [comment]
hi，I've tried what you said, but the problem still hasn't been solved. Can you remotely control my computer to help solve it



At 2022-03-04 17:35:57, "Cuong Trinh Manh" ***@***.***> wrote:

@gubeifang this is reason for your error

the cause is missing openssl library when run with Qt example on windows.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gubeifang** [comment]
hi， I've tried what you said, install the OpenSSL library， but the problem still hasn't been solved. Can you remotely control my computer to help solve it

**Comment by nguoithichkhampha** [comment]
@gubeifang , sorry, this is out of scope in our supporting.

**Comment by gubeifang** [comment]
OK，Can you provide me with some other solutions to solve this problem？



At 2022-03-07 14:12:10, "Cuong Trinh Manh" ***@***.***> wrote:

@gubeifang , sorry, this is out of scope in our supporting.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nguoithichkhampha** [comment]
@gubeifang , you need to check supported version in your Qt lib and add it into project. Ex: Qt lib supports open ssl 1.1, you can not use open ssl 1.0. One more thing, openssl lib has some dependencies. You need all of them to make openssl lib work.

**Comment by gubeifang** [comment]
thank you



At 2022-03-07 14:42:08, "Cuong Trinh Manh" ***@***.***> wrote:

@gubeifang , you need to check supported version in your Qt lib and add it into project. Ex: Qt lib supports open ssl 1.1, you can not use open ssl 1.0. One more thing, openssl lib has some dependencies. You need all of them to make openssl lib work.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gubeifang** [comment]
hello , my openssl  version 1.1.1m, and it normal operation，However, the following situation still occurs，“result”:[]













At 2022-03-07 14:42:08, "Cuong Trinh Manh" ***@***.***> wrote:

@gubeifang , you need to check supported version in your Qt lib and add it into project. Ex: Qt lib supports open ssl 1.1, you can not use open ssl 1.0. One more thing, openssl lib has some dependencies. You need all of them to make openssl lib work.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
