### ISSUE TITLE
Connecting to API from React Native

### ISSUE THREAD

**Issue by ajdinahmetovic** [Emotiv/cortex-example#113]
Hello, I am trying to use Cortex API from React Native Expo. I cant connect to API. I don't get any response. Is there a way of implementation to React Native.

Thanks

**Comment by bchaperon** [comment]
I never used React Native, but from what I understand, it is just a GUI library, it has nothing to do with the web socket connection.
Which API do you use to open the web socket?
Can you post some code?

**Comment by ajdinahmetovic** [comment]
componentDidMount() {
    this.webSocket = new WebSocket("wss://emotivcortex.com:54321")

    this.webSocket.onopen = () => {
      console.log("API opened")
    }
  }

I use this to connect to API but when I run it i get bo response. 
If i run this on other APIs i get response. Also i tried running this wih Angular and it was sucessful.

**Comment by bchaperon** [comment]
If the connection fail, you should get an error at some point.
Add something like this to your code to check for errors:
```
this.webSocket.onerror = function(event) {
    console.error("WebSocket error observed:", event);
};
```

**Comment by SSead** [comment]
Hello, I am getting the same problem with the connection to the API. I get the following error message:

failed to connect to emotivcortex.com/14.160.32.18 (port 54321) from /192.168.100.11 (port 39176) after 10000ms

**Comment by bchaperon** [comment]
Hello @SSead @ajdinahmetovic 
I just had a closer look at React Native Expo,  and I just realized that it is an library for iOS and Android.
Are you trying to build a mobile application?
Currently, Cortex only works on Windows and macOS.
So there is no way to use the Cortex API on iOS or Android.
