### ISSUE TITLE
Performance metric returns comma separated values

### ISSUE THREAD

**Issue by filchevv** [Emotiv/cortex-example#114]
The issue here is when new emotion is added the mapping becomes obsolete. My suggestions is a wrapper object to be returned, this way it wont break any logic. 
{
    "met": {
        "eng": {
            "isActive": true,
            "value": 0.663328
        },
        ..........
    }
}

**Comment by bchaperon** [comment]
Hi @filchevv 

Yes, the mapping can change when we release a new version of Cortex.
However, that should not be a problem.
When you call the method "subscribe", you must check the field "cols" in the result to see the mapping.
You must not hardcode the mapping in your application.

https://emotiv.gitbook.io/cortex-api/data-subscription/subscribe
https://emotiv.gitbook.io/cortex-api/data-subscription/data-sample-object
