### ISSUE TITLE
Error when trying to inject a Marker in EEG stream 

### ISSUE THREAD

**Issue by jabarragann** [Emotiv/cortex-example#115]
Operating system: Windows
language version: Python 3.6
Cortex version:

---
Good afternoon, 

I have been trying to inject a marker to the EEG stream of data to synchronize the data between the Epoc and other sensors however everytime I send the injectmarker command I get the error code 32602 corresponding to invalid method parameters. I have tryied modifying the Json command but no matter what I change I am still getting the same error.

`{'error': {'code': -32602, 'message': 'Invalid method parameter(s).'}, 'id': 1, 'jsonrpc': '2.0'}`

The Json command I am using to call the injectMarker method can be seen below. In this snipted of code authorizationToken is a variable with the the session token and sessionId is a variable with the current session Id.  My code is being run from Python 3.6.

`markerCmd = {
              "jsonrpc": "2.0",
              "method": "injectMarker",
              "params": {
                "_auth": authorizationToken,
                "session": sessionId,
                "label": "test1",
                "value": "record-1",
                "port": "USB",
                "time": 123456789
              },
              "id": 1
            }
`
Is there something I am missing to use the inject marker correctly?

**Comment by Qurite** [comment]
oh，We had the same problem.I tried so many times, not even.

**Comment by Qurite** [comment]
Have you solved the problem?
