### ISSUE TITLE
Wrong example in setupProfile JSON request

### ISSUE THREAD

**Issue by jmota-dev** [Emotiv/cortex-example#115]
I figured out that one of the request examples of the API in [setupProfile section](https://emotiv.gitbook.io/cortex-api/bci/setupprofile):  _"Create a new empty profile"_ is missing one parameter:

**"status" : "create"**

    {
      "id": 1,
      "jsonrpc": "2.0",  
      "method": "setupProfile",
        "params": {
            "cortexToken": "xxx",
            "profile": "cortex-v2-example",
            "MISSING_PARAM":  "MISSING_VALUE"
        }
    }

**Comment by bchaperon** [comment]
Thank you @jmota7dev 
I fixed it.
