### ISSUE TITLE
Missing parameter in a JSON request example

### ISSUE THREAD

**Issue by jmota-dev** [Emotiv/cortex-example#116]
I figured out that one of the request examples of the API in [createRecord ](https://emotiv.gitbook.io/cortex-api/records/createrecord) section: "Create a new record" is missing one parameter:

    {
      "id": 1,
      "jsonrpc": "2.0",  
      "method": "**MISSING_VALUE**",
        "params": {
            "cortexToken": "xxx",
            "session": "1067dc90-eb17-489b-9514-69cb79ac696c",
            "title": "Cortex Examples C++"
        }
    }

It's just the example.

Best regards.

**Comment by bchaperon** [comment]
Thanks @jmota7dev 
If you find more errors, please add them to this issue.
