### ISSUE TITLE
Help!! Unable to find valid websocket connection

### ISSUE THREAD

**Issue by methylDragon** [Emotiv/cortex-example#117]
I've been trying to connect to all of the following using a websocket client or a Python wrapper.

`wss://emotivcortex.com:54321`
`wss://emotivcortex.com:54123`
`wss://127.0.0.1:54321`

But none have been able to be connected. Tried bluetooth dongle, bluetooth, wired, for Emotiv Epoc+ but nothing seems to work. I turned off my firewalls.

I'm on Cortex Service: 2.0.132, running an Emotiv Epoc+ that's manufactured in 2018. What's going on?

The BCI service receives messages just fine, but I can't connect to the websockets. If I can't do that then I've essentially wasted money because I can't do anything with the Emotiv... :( Any help would be greatly appreciated.

**Comment by bchaperon** [comment]
Hello @methylDragon 

If you are using Cortex 2.0, then you must connect to **wss://localhost:6868**
Also be aware that the 2.0 API is different than the 1.x API. So the examples in this repository only work for Cortex 1.x, 

The examples for Cortex 2.0 are here https://github.com/Emotiv/cortex-v2-example
Please check the Cortex 2.0 documentation https://emotiv.gitbook.io/cortex-api/
