### ISSUE TITLE
Perform Baseline (Eyes Open / Closed) Before Training

### ISSUE THREAD

**Issue by cyberspace69** [Emotiv/cortex-example#120]
I'm currently building an interactive wrapper for performing trainings.

Within EmotivBCI, I typically perform a baseline reading (eyes open / closed) before working with mental commands, etc.

Is this necessary / how would this be implemented via API before training?

**Comment by bchaperon** [comment]
Hello @cyberspace69 
The training doesn't depend on the baseline. And there is no specific API for the baseline.
