### ISSUE TITLE
EEG data export

### ISSUE THREAD

**Issue by Yosief208** [Emotiv/cortex-example#121]
Hello...I am trying to export EEG signal recorded by Emotiv Insight, however it's not working...Here is the code below...
from cortex2 import EmotivCortex2Client
from websocket import create_connection
import json
import time
from auth import *
from emotiv_record_dt_way import Cortex
import datetime

url = "wss://localhost:6868"
id='bOnVA7tcEztcbr0OX0SIgAbqKAZyoI9c7EBw8dJz'
secret='5p8m9WMoTME9PTEyoHXavaw9RthJ2swuExA2V4oExmWf3rXvWXWjSECzksEq318jeHfZwU0UaO9dPXwaUhHrXX1wyUKnWXzqpt6igjmXVYy2mgTHS6EWPKfBCiCyEBfE'
tok1 = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6ImNvbS5oYWJlbmlkLnByb2plY3QiLCJhcHBWZXJzaW9uIjoiMS4wIiwiZXhwIjoxNTk5NjgxMjA0LCJuYmYiOjE1OTk0MjIwMDQsInVzZXJJZCI6IjZiNWEzNTZkLTRhOWQtNDk0My1iODlkLTYxNTJlMTFhNDc4ZCIsInVzZXJuYW1lIjoiaGFiZW5pZCIsInZlcnNpb24iOiIyLjAifQ==.y+s8MuNXl5yUtey0bexpqWGsFpGCQ3zL8Vlrs7WG5vg="
tttt = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6ImNvbS5oYWJlbmlkLnByb2plY3QiLCJhcHBWZXJzaW9uIjoiMS4wIiwiZXhwIjoxNTk5ODQzMDM0LCJuYmYiOjE1OTk1ODM4MzQsInVzZXJJZCI6IjZiNWEzNTZkLTRhOWQtNDk0My1iODlkLTYxNTJlMTFhNDc4ZCIsInVzZXJuYW1lIjoiaGFiZW5pZCIsInZlcnNpb24iOiIyLjAifQ==.yv678Zi1//Xqw4w+RTzTkwnCewZEDknfrOHRpcfXWt0="
tok="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6ImNvbS5oYWJlbmlkLnByb2plY3QiLCJhcHBWZXJzaW9uIjoiMS4wIiwiZXhwIjoxNTk3NzIxNzE4LCJuYmYiOjE1OTc0NjI1MTgsInVzZXJJZCI6IjZiNWEzNTZkLTRhOWQtNDk0My1iODlkLTYxNTJlMTFhNDc4ZCIsInVzZXJuYW1lIjoiaGFiZW5pZCIsInZlcnNpb24iOiIyLjAifQ==.stjkENkyr07IMKBzQd+DNU0a6ZLEMVnNtupbqDfn75c="
pro_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6ImNvbS5oYWJlbmlkLnByb2plY3QiLCJhcHBWZXJzaW9uIjoiMS4wIiwiZXhwIjoxNTk5OTg2NDY2LCJuYmYiOjE1OTk3MjcyNjYsInVzZXJJZCI6IjZiNWEzNTZkLTRhOWQtNDk0My1iODlkLTYxNTJlMTFhNDc4ZCIsInVzZXJuYW1lIjoiaGFiZW5pZCIsInZlcnNpb24iOiIyLjAifQ==.sLRI6TsX6WcfDnDA1yohvr7/+zqpc5PNg90Du8siq4w="
#session_id=str()
#token=""
ws=create_connection(url)

class Emotiv_Class:

    def do_stuff(self,emotive):
        emotiv.request_access()
        #ws=create_connection(url)
    def create_record_then_export(self,record_name,record_description,record_length_s,record_export_folder,record_export_data_types,record_export_format,record_export_version):
        self.create_record(record_name,record_description)

        self.wait(record_length_s)

        self.stop_record()

        self.disconnect_headset()

        self.export_record(record_export_folder,record_export_data_types,record_export_format,record_export_version,[self.record_id])

    def wait(self, record_length_s):
        print('start recording -------------------------')
        length = 0
        while length < record_length_s:
            print('recording at {0} s'.format(length))
            time.sleep(1)
            length += 1
        print('end recording -------------------------')
    def create_record(self,record_name,record_description):
        print('create record --------------------------------')
        create_record_request = {
            "jsonrpc": "2.0",
            "method": "createRecord",
            "params": {
                "cortexToken":token,
                "session": session_id,
                "title": record_name,
                "description": record_description
            },

            "id": CREATE_RECORD_REQUEST_ID
        }

        ws.send(json.dumps(create_record_request))
        result = ws.recv()
        result_dic = json.loads(result)

        self.record_id = result_dic['result']['record']['uuid']

    def stop_record(self):
        print('stop record --------------------------------')
        stop_record_request = {
            "jsonrpc": "2.0",
            "method": "stopRecord",
            "params": {
                "cortexToken": token,
                "session": session_id
            },

            "id": STOP_RECORD_REQUEST_ID
        }

        ws.send(json.dumps(stop_record_request))
        result = ws.recv()
        result_dic = json.loads(result)
    def disconnect_headset(self):
        print('disconnect headset --------------------------------')
        disconnect_headset_request = {
            "jsonrpc": "2.0",
            "id": DISCONNECT_HEADSET_ID,
            "method": "controlDevice",
            "params": {
                "command": "disconnect",
                "headset": "INSIGHT-A1D206B4"
            }
        }

        ws.send(json.dumps(disconnect_headset_request))

    def export_record(self,folder,export_types,export_format,export_version,record_ids):
        print('export record --------------------------------')
        export_record_request = {
            "jsonrpc": "2.0",
            "id": EXPORT_RECORD_ID,
            "method": "exportRecord",
            "params": {
                "cortexToken": token,
                "folder": folder,
                "format": export_format,
                "streamTypes": export_types,
                "recordIds": record_ids
            }
        }

        # "version": export_version,
        if export_format == 'CSV':
            export_record_request['params']['version'] = export_version

        ws.send(json.dumps(export_record_request))

        # wait until export record completed
        while True:
            time.sleep(1)
            result = ws.recv()
            result_dic = json.loads(result)

            if 'result' in result_dic:
                print(result_dic['result'])
                #if len(result_dic['result']['success']) > 0:
                #break

r = Emotiv_Class()
# record parameters
record_name = 'haben record'
record_description = 'record for project'
record_length_s = 5

# export parameters
record_export_folder = 'C:/Users/halan/Desktop/recorded/Programmatically'
record_export_data_types = ['EEG']
record_export_format = 'CSV'
record_export_version = 'V2'

QUERY_HEADSET_ID = 1
CONNECT_HEADSET_ID = 2
REQUEST_ACCESS_ID = 3
AUTHORIZE_ID = 4
CREATE_SESSION_ID = 5
SUB_REQUEST_ID = 6
SETUP_PROFILE_ID = 7
QUERY_PROFILE_ID = 8
TRAINING_ID = 9
DISCONNECT_HEADSET_ID = 10
CREATE_RECORD_REQUEST_ID = 11
STOP_RECORD_REQUEST_ID = 12
EXPORT_RECORD_ID = 13
INJECT_MARKER_REQUEST_ID = 14
SENSITIVITY_REQUEST_ID = 15
MENTAL_COMMAND_ACTIVE_ACTION_ID = 16
MENTAL_COMMAND_BRAIN_MAP_ID = 17
MENTAL_COMMAND_TRAINING_THRESHOLD = 18

# start record --> stop record --> disconnect headset --> export record
r.create_record_then_export(record_name,record_description,record_length_s,record_export_folder,record_export_data_types,record_export_format,record_export_version)
# -----------------------------------------------------------
#obj=Emotiv_Class()
emotiv=EmotivCortex2Client(url,client_id=id,client_secret=secret)
r.do_stuff(emotiv)

### The output of the above code is
Hello USER.
The following set of letters is your session token. In order maintain security, do not share this token:
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6ImNvbS5oYWJlbmlkLnByb2plY3QiLCJhcHBWZXJzaW9uIjoiMS4wIiwiZXhwIjoxNjAwNzYxNTc2LCJuYmYiOjE2MDA1MDIzNzYsInVzZXJJZCI6IjZiNWEzNTZkLTRhOWQtNDk0My1iODlkLTYxNTJlMTFhNDc4ZCIsInVzZXJuYW1lIjoiaGFiZW5pZCIsInZlcnNpb24iOiIyLjAifQ==.BX1auWbKN5Ad1h0ojyDaZjQIbKz34Anz4HbALQRQe7M=
This token has been automatically registered as your session token. You may use the headset as a client
{"id":1,"jsonrpc":"2.0","result":{"failure":[],"success":[{"cols":["COUNTER","INTERPOLATED","AF3","T7","Pz","T8","AF4","RAW_CQ","MARKER_HARDWARE","MARKERS"],"sid":"d384ea48-042e-4c47-804b-f960a35900fa","streamName":"eeg"}]}}
create record --------------------------------
start recording -------------------------
recording at 0 s
recording at 1 s
recording at 2 s
recording at 3 s
recording at 4 s
end recording -------------------------
stop record --------------------------------
disconnect headset --------------------------------
export record --------------------------------
{'command': 'disconnect', 'message': 'Disconnect device INSIGHT-A1D206B4 successfully'}
{'failure': [{'code': -32603, 'message': 'Internal Error.', 'recordId': '59a6e721-eee4-4ec7-9776-41d295f8993f'}], 'success': []}

I am waiting for your help......

**Comment by nguoithichkhampha** [comment]
@Yosief208 , Can you try to wait a few seconds between 2 functions disconnect_headset and export record ?
