### ISSUE TITLE
Question: Why session does not exist right after creating?

### ISSUE THREAD

**Issue by jracp** [Emotiv/cortex-example#121]
Operating system: Windows 10
language version: Python 3.8
Cortex version: 'v2.2.0-636-gaf1ff8f

---

I have developed a simple code in Python to connect to Emotiv EPOC+ with free BCI API license, which executes the following steps:
 - `ec.testConnection()`
 - `ec.requestAccess()`
 - `ec.generateToken()`
 - `ec.connectedHeadset()`
 - `ec.controlHeadset()`
 - `ec.openSession()`
 - ` ec.subscribe()`

The problem is that I can open and activate a new session, but as soon as I want to subscribe to the session, I get the **The session does not exist** error. Anyone has experienced the same issue?

**Comment by bchaperon** [comment]
Hi @jracp 
If the method createSession is successful then you should be able to subscribe.
Can you show me the JSON request and response for createSession and subscribe ?
Maybe some parameter is wrong.

**Comment by bchaperon** [comment]
Also, if you are using Cortex v2.2 and no v1, then you should post on this forum:
https://github.com/Emotiv/cortex-v2-example/issues 
Thanks :)

**Comment by jracp** [comment]
> Hi @jracp
> If the method createSession is successful then you should be able to subscribe.
> Can you show me the JSON request and response for createSession and subscribe ?
> Maybe some parameter is wrong.

Thank you for your reply. I found out that the websocket object was closed for some reason right after creating a session so the subscribe was not going through. Fixed the problem with websocket object and everything is working fine now.

**Comment by jracp** [comment]
> Also, if you are using Cortex v2.2 and no v1, then you should post on this forum:
> https://github.com/Emotiv/cortex-v2-example/issues
> Thanks :)

Sorry for posting the issue in the wrong place. Will do for future issues.
