### ISSUE TITLE
mentalCommandActiveAction issue

### ISSUE THREAD

**Issue by Akshathhm** [Emotiv/cortex-example#122]
The API is not working as expected..

We are trying to set the commands to be used by using the below request..

{"jsonrpc":"2.0","method":"mentalCommandActiveAction","params":{"cortexToken":"XXXX","status":"set","session":"20863a01-5e61-4e33-8304-7ac6287f3497","actions":["lift"],"profile":"XXX"},"id":411114}

REsponse:

{"id":411114,"jsonrpc":"2.0","result":{"actions":["lift"],"message":"Set MentalCommand active actions successfully"}}

But subsequent get calls provide multiple "commands" like "neutral, list, push".... whereas we were expecting "lift" only...

**Comment by nguoithichkhampha** [comment]
@Akshathhm , which param you set in the request get mentalCommandActiveAction ?
"session" or "profile"
https://emotiv.gitbook.io/cortex-api/advanced-bci#profile-name-or-session-id
if you set param "profile" and you don't save this profile before. command "lift" just save to memory .

**Comment by nguoithichkhampha** [comment]
and you are working on Cortex v2 or v1. if on v1, I recommend you change to use v2 with more feature and bug fixing.
if on v2 please create ticket on this repo 
https://github.com/Emotiv/cortex-v2-example

**Comment by Akshathhm** [comment]
We are using cortext v2..

We tried to set the mentalCommandActiveAction using session.. So, do we need to updateSession after that?
or saving the profile is sufficient?
Subsequent get calls provide multiple commands like "neutral" ,"push", "lift".. which is not correct

**Comment by Akshathhm** [comment]
we tried to call saveProfile - but its saying "profilename already exist"...

So here is what we want 

1. Call mentalCommandActiveAction API to set the commands
2. Try subscribe to the steams  and expect only the activated command

**Comment by nguoithichkhampha** [comment]
did you try with new profile and work from your project ?

**Comment by Akshathhm** [comment]
We got it work by doing following steps

Load the profile
Call mentalCommandActiveAction API
save the profile
