### ISSUE TITLE
40s to receive a valid update from Performance Metrics

### ISSUE THREAD

**Issue by HelenoSK** [Emotiv/cortex-example#122]
Hi,

I've been testing some funcionalities from EPOC+ using Emotiv Plugin for Unity 3D and the basic license.
In the sample scene provided by plugin, and as well in my test project, Cortex is taking 40s to receive a valid information about PM Metrics.

In my tests, "OnPMDataReceived" method in PMDataBuffer.cs file is called every 10s,  it's receiving valid values( by debugging), but when I request "DataStreamManager.Instance.GetPMData()" it returns -1. Only after 40s a valid data is received by this method.

Note: 
- this issue is happening in my project and in 'Cortex Unity Example'.
- I've updated my EPOC+ firmware and Emotiv app today.

**Comment by nguoithichkhampha** [comment]
@HelenoSK , Cortex will return null value in the case detection is not active. The cause is your signal quality is not good.
we mentioned about it in the document 
https://emotiv.gitbook.io/cortex-api/data-subscription/data-sample-object
