### ISSUE TITLE
(node:20656) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

### ISSUE THREAD

**Issue by m-usama-hub** [Emotiv/cortex-example#124]
wss://localhost:6868 not opening saying "this site cannot be reached".

**Comment by bchaperon** [comment]
Hi @m-usama-hub 
Can you start EMOTIV App or EmotivBCI and see if these applications works properly?
