### ISSUE TITLE
"Session limit on this device has been reached"...even if I just received this device

### ISSUE THREAD

**Issue by jfortias** [Emotiv/cortex-example#125]
I'm coding on C# Windows 10 pro with an insight...
After some issues about the config.cs (I expected an app.config).... My authentication is ok
but now I have "Session limit on this device has been reached" ..... 

I bought this device to code on (open source) .... What's this limit ?

**Comment by nguoithichkhampha** [comment]
@jfortias , what is the Cortex version you are working on ? if version 2. may you check the issues related to Session limit on this repo
https://github.com/Emotiv/cortex-v2-example

**Comment by jfortias** [comment]
v2 ... but I did not request my dev license ... I did it :-)
