### ISSUE TITLE
authorize error about behavior

### ISSUE THREAD

**Issue by ivaylov** [Emotiv/cortex-example#129]
I authorize with this code but giving following error any suggestion?

{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "authorize",
    "params": {
        "clientId": "xxx",
        "clientSecret": "xxx"
    }
}

Subscription: {"error":{"code":-32018,"data":{"behavior":"This parameter is required: cortexToken"},"message":"Missing the required parameters."},"id":1,"jsonrpc":"2.0"}
Profile Set-up: {"error":{"code":-32018,"data":{"behavior":"This parameter is required: cortexToken"},"message":"Missing the required parameters."},"id":1,"jsonrpc":"2.0"}
Mental Command Brain Map: {"error":{"code":-32018,"data":{"behavior":"This parameter is required: cortexToken"},"message":"Missing the required parameters."},"id":1,"jsonrpc":"2.0"}

**Comment by bchaperon** [comment]
Hi @ivaylov 

After you send the request "authorize", you must wait for the response from Cortex, and extract the Cortex token from this response. Then you must pass this token as an argument of other methods like "subscribe" or "mentalCommandBrainMap".
