### ISSUE TITLE
No headsets available

### ISSUE THREAD

**Issue by CrisMD** [Emotiv/cortex-example#13]
I've tried all the examples and none of them are working, the response for query headsets always contains [] as result. Also, when trying to use CortexUI, I get the same message "No available headsets". The headset is connected and working, I've tested it with Emotiv Xavier Control Panel. 
I'm working on Windows 10, last version of Cortex API.
Any idea why this is happening? Any help is much appreciated :)

**Comment by patdotme** [comment]
@CrisMD have you tried with the latest Cortex 1.3?
