### ISSUE TITLE
The name of clientID and clientSecret does not exist in the current context

### ISSUE THREAD

**Issue by chenlixiao-a** [Emotiv/cortex-example#131]
I creat a APP and get the clientID and clientSecret. But when I run it it tells me that"The name of clientID and clientSecret does not exist in the current context."Can you tell me how to deal with it?
`[Header("Connection")]
    public string socketUrl = "wss://localhost:6868";

    [Header("Emotiv")]
    public string clientId= WiPiYYURLcBSKviJ4mxYA498H4IgNnh7YPuOBgB0;
    public string clientSecret=xxxx;
    public string headsetId = "EPOCPLUS-3B9AEC58";`

**Comment by bchaperon** [comment]
Hi @chenlixiao-a 

Please, do not publish the client secret of your application on a public forum. The client secret must remain a secret :)

About your error, how did you get it? Does it come from the Cortex API? What message did you send to Cortex to receive this error?
Please post the complete response from Cortex.

**Comment by chenlixiao-a** [comment]
Hello,
I want to run the project  [https://github.com/BrandlMax/BrainFramework].I follow the instructions.I l get the clientID and clientSecret. Then I added them in the code . After that I click the  the button of "play" in Unity.The errors tells me that "The name of xxxxxxxx(my clientID and clientSecret) does not exist in the current context."

**Comment by bchaperon** [comment]
If the error comes from the BrainFramework, then please contact the authors of this software to get help.
EMOTIV is not involved in the development of this software and so we cannot provide any support for it.
