### ISSUE TITLE
contact quality  vs eeg quality in EmotivPro 2.7.0

### ISSUE THREAD

**Issue by jyauri** [Emotiv/cortex-example#135]
Hi all, I am sorry, maybe my question is off topic.

Today I unpack my Emotiv X headeset. 
My software:
- Windows 10
- EmotivPro 2.7.0.341.
- An Emotiv account of student.

I drop the pads and setup on the EEG. But when I go the the software to record something, I was surprised, I never get 100% of eeg quality instead of the contact quality is 100%, even when I stay quit, so I assume it isn't not working well, or yes ?.

![IMG_20210429_125347318](https://user-images.githubusercontent.com/15385234/116564941-b44fee80-a905-11eb-80a0-5da5ace99200.jpg)
![IMG_20210429_125409941](https://user-images.githubusercontent.com/15385234/116564990-bb76fc80-a905-11eb-9ca6-551bf3efcb26.jpg)

While I achieve a constant contact quality of 100%, the eeg quality oscillates (0%, 8%, 20%, 75%). I wet more the pads, but no solution.

Does someone experimented it? Is this a manufacturing fail?

**Comment by bchaperon** [comment]
Hi @jyauri 

The difference between Contact Quality and EEG Quality is explained on this page:
https://emotiv.gitbook.io/cortex-manual/setting_up_your_eeg_device/view_contact_quality_map/contact-quality-cq-vs.-eeg-quality-eq

Reaching 100% EEG quality is more difficult than reaching 100% CQ. It is expected. The EEG quality score is always lower than or equal to the contact quality score. 

There is probably nothing wrong with your headset. But if you still have difficulties getting a stable EEG quality score, then you can contact the EMOTIV customer support.
https://www.emotiv.com/contact-support/
