### ISSUE TITLE
Mental commands

### ISSUE THREAD

**Issue by floriangamillscheg** [Emotiv/cortex-example#137]
Hello!

I am having some difficulties when I try to load a profile for using the mental commands. Like in the example, I first:

- connect to the headset like in the unity example 
- then I subscribe to `sys` and `com` data streams
- then I instantiate a new BCITraining object and call `Init()`
- then I call `GetDetectionInfo("mentalCommand");`
- then I call `queryProfile` where my profile is correctly found
- and then I call `LoadProfile()` with the appropriate profile. But here I get a NullReferenceException in ` if (_profileLists.Contains(profileName))`...

Also I am getting only the neutral state with power 0....

Am I missing something?

**Comment by floriangamillscheg** [comment]
The problem was that the profile was loaded, but Init was not done.... Therefore I load the profile in `OnQueryProfileOK`

**Comment by ClaireShuttle** [comment]
hi there 
Could I please talk to you about the work you are doing?
I need some support from someone with both unity and emotiv.
would you be able to assist please?
My address claire@monichron.com
thanks
