### ISSUE TITLE
Problem with the connection between the Cortex API and Flutter

### ISSUE THREAD

**Issue by nicpenaloza** [Emotiv/cortex-example#140]
Hello, I am currently trying to make a connection between my App in Flutter and Cortex API through the websocket, as such it does not generate an error, but I am not receiving a response.

I am sending a json as a request (as the documentation indicates). The Websocket should respond with a json, but I am not receiving any response, it generates a null.

![dudap1](https://user-images.githubusercontent.com/47763248/118039342-dbf77b80-b335-11eb-8496-bea34f9e86cf.jpg)

![dudap2](https://user-images.githubusercontent.com/47763248/118039401-e9ad0100-b335-11eb-89c9-deccdd0ad7bd.jpg)

![dudap3](https://user-images.githubusercontent.com/47763248/118039438-f3ceff80-b335-11eb-9f8d-aa6bbac727b2.jpg)

**Comment by bchaperon** [comment]
Hi @nicolaspgamba 

I have no experience with Flutter, and we don't use this framework at EMOTIV. So it impossible for me to check if your source code is correct or not.

Which OS are you using? 
Can you try the Python example (or any other example) from this Github repo and see if it works?
Does your program handle the errors that may occur when you connect to the web socket?

**Comment by nicpenaloza** [comment]
Hi @bchaperon 

It seems that the problem is with the port, Flutter tells me that it has problems trying to certify it. Does the API only work on that port? Is there no way to change it?

This is the error that generates me
![image](https://user-images.githubusercontent.com/47763248/119382216-5950b380-bc87-11eb-81de-726c162f3c8c.png)

**Comment by bchaperon** [comment]
Hi @nicolaspgamba 

The problem comes from the certificate. The Cortex web socket server uses a self-signed certificate. By default, most web socket clients consider that such certificate is invalid.

Maybe you can configure Flutter to accept self signed certificate. I know it is possible in other languages.
I see that other people had the same issue with Flutter: https://github.com/dart-lang/sdk/issues/34284

**Comment by shathaalotaibi** [comment]
Did the connection work with you?

**Comment by shathaalotaibi** [comment]
Did the connection work with you?
