### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by nicpenaloza** [Emotiv/cortex-example#145]
I purchased the STUDENT license to access the Raw data from the INSIGHT device.

Yesterday I completed the [form](https://www.emotiv.com/student-sdk-application-form/) to request access to the SDK and I have already got the approval.

Now I am trying to make the connection via the Cortex API using Python. I am following the steps indicated in the [documentation](https://emotiv.gitbook.io/cortex-api/overview-of-api-flow), when trying to carry out the authorization process it generates the following error

`{'error': {'code': -32027, 'message': 'The application does not have permission to use the license.'}, 'id': 1, 'jsonrpc': '2.0'}`

Which is strange to me because I already have access to the SDK and have already registered the app in my account.

PS: when registering my application in the account, I selected the box 'My application requires access to EEG'

**Comment by tungntEmotiv** [comment]
Hi @nicpenaloza ,

Please try to put empty string to licenseID as below and try again
`
user = {
    "license" : "",  # set empty license here -> Cortex will help take a valid license in your license list
    "client_id" : "your client id",
    "client_secret" : "your client secret",
    "debit" : 100
}
`
If the issue still happen, please provide your emotivID and clientId for checking

**Comment by nicpenaloza** [comment]
Hi @tungntEmotiv,

I tried again, but this time leaving the license field empty and it gives me another error
```
 {
    "error": {
        "code": -32002,
        "message": "Invalid license key".
    },
    "id": 1,
    "jsonrpc": "2.0"
}
```

My code is like this
```
    def authorize(self):
        print('authorize --------------------------------')
        authorize_request = {
            "id": 1,
            "jsonrpc": "2.0",
            "method": "authorize",
            "params": {
                "clientId": "KGajqqGzoHn3ZzNbYXmvKgrRnLJUyMrn5xnK90oO",
                "clientSecret": "CLIENT_SECRET",
            },
        }

        if self.debug:
            print('auth request \n', json.dumps(authorize_request, indent=4))

        self.ws.send(json.dumps(authorize_request))

        while True:
            result = self.ws.recv()
            result_dic = json.loads(result)

            if 'error' in result_dic:
                print('error\n', json.dumps(result_dic, indent=4))
                break

            elif 'id' in result_dic:
                if result_dic['id'] == 1:
                    if self.debug:
                        print('auth result \n', json.dumps(result_dic, indent=4))
                    self.auth = result_dic['result']['cortexToken']
                    break
```

PS: I am guided by the example code that is on github

**Comment by tungntEmotiv** [comment]
Hi @nicpenaloza ,
Your code is fine. 
Please try again. Now , your license has API access . Sorry for your inconvenient. Thanks

**Comment by CarlosA-Mtz** [comment]
I have the same problem and my _emotivID_ is **_carlosantonio_** and my _clientID_ **_tXtEeB6XE2aqlBBLJtstvGzKHlhctniBVXwYB856_**

**Comment by asim-v** [comment]
@tungntEmotiv  Hello, I have the same issue, my emotivID is **emiliobazan** and my clientID is **exr7IrTMi6hnnTfx6kzRhmyWMyFiYFi5TpadfQu2**

**Comment by tungntEmotiv** [comment]
@asim-v , We see that you haven't granted EEG API access for your application. Please grant via https://www.emotiv.com/cortex-sdk-application-form/

**Comment by RYCoop** [comment]
@tungntEmotiv I have the same problem and my emotivID is **lgh4gh** and clientID is **sZteLJ27aZCq63F2Im8yeKuAk7K1hNRIiOnw3Dm2**

**Comment by tungntEmotiv** [comment]
Hi @RYCoop,
It's closed ticket. So to get better support about this issue. please follow below guides:
1. Check if you have done all steps in https://emotiv.gitbook.io/cortex-api/#create-a-cortex-app?
2. If you have done all of them and still have the issue, contact our Customer Support team via support@emotiv.com

**Comment by kliklis** [comment]
@tungntEmotiv Hi! I have the same problem and my emotivID is **kliklis** and clientID is **r059xxqBpvhjim37gYU8BkTJZnFmfiMmw1iK7Dd7**

**Comment by tungntEmotiv** [comment]
Hi @kliklis ,
Please help to contact to our Customer Support team via support@emotiv.com . thanks

**Comment by unigithubSB** [comment]
@tungntEmotiv Hello, 
I have the same issue as well and my emotivID is **leen_s** and clientID **sPiA8o9IQa2f3os4BuDHjQLTsN38hspyDBhRLBTb**.
