### ISSUE TITLE
Python Connection refused

### ISSUE THREAD

**Issue by nicpenaloza** [Emotiv/cortex-example#149]
I am trying to connect via websocket to the Cortex API. I am running the project on Amazon Cloud9, which in turn is connected to an Amazon EC2 server.

```
GET_INFO_ID = 1
REQUEST_ACCESS_ID = 2
QUERY_HEADSETS_ID = 3
CONTROL_DEVICE_ID = 4
DISCONNECT_HEADSET_ID = 5
AUTHORIZE_ID = 6
CREATE_SESSION_ID = 7
SUB_DATA_ID = 8
CREATE_RECORD_REQUEST_ID = 9
STOP_RECORD_REQUEST_ID = 10
EXPORT_RECORD_ID = 11
INJECT_MARKER_REQUEST_ID = 12

class Cortex(Dispatcher):
    def __init__(self, user, debug_mode=False):
        url = "wss://127.0.0.1:6868"
        self.ws = websocket.create_connection(url, sslopt={"cert_reqs": ssl.CERT_NONE})
        self.user = user
        self.debug = debug_mode

        self.headset_id = ''
        self.auth = ''
        self.session_id = ''
        self.record_id = ''

    def get_info(self):
        print('Get info -------------------------')
        get_info = {
            "id": GET_INFO_ID,
            "jsonrpc": "2.0",
            "method": "getCortexInfo"
        }
        self.ws.send(json.dumps(get_info, indent=4))
        result = self.ws.recv()
        result_dic = json.loads(result)

        return result_dic['result']


user = {
    "username": "username",
    "license": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "clientId": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "clientSecret":XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "debit": 100
}

cortex_conn = Cortex(user, True)
print(json.dumps(cortex_conn.get_info(), indent=4))
```
When calling the Cortex class I get the following error

```
Traceback (most recent call last):
  File "/home/ec2-user/environment/src/cortex/main.py", line 485, in <module>
    cortex_conn = Cortex(user, True)
  File "/home/ec2-user/environment/src/cortex/main.py", line 25, in __init__
    self.ws = websocket.create_connection(url, sslopt={"cert_reqs": ssl.CERT_NONE})
  File "/home/ec2-user/.local/lib/python3.7/site-packages/websocket/_core.py", line 596, in create_connection
    websock.connect(url, **options)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/websocket/_core.py", line 250, in connect
    options.pop('socket', None))
  File "/home/ec2-user/.local/lib/python3.7/site-packages/websocket/_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/websocket/_http.py", line 208, in _open_socket
    raise err
  File "/home/ec2-user/.local/lib/python3.7/site-packages/websocket/_http.py", line 185, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by nguoithichkhampha** [comment]
@nicpenaloza you installed Cortex on Amazon server, right ? did you run successful Emotiv Launcher on this server ?

**Comment by nicpenaloza** [comment]
@nguoithichkhampha Well, initially I was running the project in Pycharm without any inconvenience, I copied and pasted the code and made the corresponding installations of the packages necessary for the execution and operation of the project, but it generates that connection error when trying to connect through the websocket, I don't know if I should configure something else on the server side

**Comment by nguoithichkhampha** [comment]
@nicpenaloza Can you check on server port 6868 open or not ? and my first question, did you run successful Emotiv Launcher on this server .

**Comment by nicpenaloza** [comment]
@nguoithichkhampha Sorry, when you ask me if I run the emotiv launcher, what exactly do you mean? because as such the Cortex app I am using is already accepted on my account. Is there anything else I need to do?

**Comment by nguoithichkhampha** [comment]
@nicpenaloza I suppose that you will use our linux installer on your server. in this installer includes an application named as Emotiv App or Emotiv Launcher. Did you able to run this app ? and how about port 6868 on server ?

**Comment by nicpenaloza** [comment]
@nguoithichkhampha port 6868 is already enabled on the server, but I have not done the emotiv launcher, I don't know how since the server is the one that gives me the Amazon service

**Comment by nguoithichkhampha** [comment]
@nicpenaloza , I think aws server does not accept self signed certificate from Cortex. But what is the reason to run Cortex on aws ? you can not plug a emotiv headset to aws server

**Comment by nicpenaloza** [comment]
@nguoithichkhampha It is that I am currently developing an application that connects to the Cortex API through python. My idea was to have everything in the cloud, but I don't think it's possible. I will have to leave part of the backend on my local PC.

As a result of that, another question arises, is it possible to save the CSV files in the cloud? There is a method called 'exportRecord' where a route is passed as a parameter. So is it possible to save the file somewhere other than my local storage?

**Comment by bchaperon** [comment]
Hi @nicpenaloza 

To collect data from your EMOTIV headset, you must run the Cortex service and your Python script on your local PC.

The CSV export can only write the file to your local hard drive. It cannot upload data to your cloud.
So you have to upload the CSV file yourself.
