### ISSUE TITLE
Python Connection Error

### ISSUE THREAD

**Issue by CarlosA-Mtz** [Emotiv/cortex-example#150]
I've a problem running train.py 'cause a KeyError is shown and I don't know how to fix it, below is shown the execution of train.py and the redirection to cortex.py

```
C:\cortex-v2-example-master\python>train.py
query headset --------------------------------
The headset EPOCPLUS has been connected.
request access --------------------------------
authorize --------------------------------
Traceback (most recent call last):
  File "C:\cortex-v2-example-master\python\train.py", line 234, in <module>
    t.do_prepare_steps()
  File "C:\cortex-v2-example-master\python\train.py", line 51, in do_prepare_steps
    self.c.do_prepare_steps()
  File "C:\cortex-v2-example-master\python\cortex.py", line 218, in do_prepare_steps
    self.authorize()
  File "C:\cortex-v2-example-master\python\cortex.py", line 137, in authorize
    self.auth = result_dic['result']['cortexToken']
KeyError: 'result'
```

**Comment by nguoithichkhampha** [comment]
seems there is an error in line 
`self.auth = result_dic['result']['cortexToken']`
Can you try to comment this line and print result_dic

**Comment by CarlosA-Mtz** [comment]
Another Error is shown 

```
Traceback (most recent call last):
  File "C:\cortex-v2-example-master\python\train.py", line 234, in <module>
    t.do_prepare_steps()
  File "C:\cortex-v2-example-master\python\train.py", line 51, in do_prepare_steps
    self.c.do_prepare_steps()
  File "C:\cortex-v2-example-master\python\cortex.py", line 220, in do_prepare_steps
    self.create_session(self.auth, self.headset_id)
AttributeError: 'Cortex' object has no attribute 'auth'
```

**Comment by nguoithichkhampha** [comment]
what is the result of 
`result_dic `
I think Cortex return error in response of request "authorize".

**Comment by CarlosA-Mtz** [comment]
Investigated the code further and found that it all originates from this in "result": {'error': {'code': -32027, 'message': 'The application does not have permission to use the license.'}, ' id ': 4,' jsonrpc ':' 2.0 '}.
In another issue I saw that license don't have API access.
My emotivID is carlosantonio and my clientID tXtEeB6XE2aqlBBLJtstvGzKHlhctniBVXwYB856

**Comment by nguoithichkhampha** [comment]
@CarlosA-Mtz , you should contact our css team to request API access with your license.

**Comment by CarlosA-Mtz** [comment]
where do I communicate with the CSS team?

**Comment by bchaperon** [comment]
Hi @CarlosA-Mtz 
Please use this form on the Emotiv e]web site :) 
https://www.emotiv.com/contact-support/

**Comment by CarlosA-Mtz** [comment]
I need a subscription for use the code?

**Comment by bchaperon** [comment]
Hi @CarlosA-Mtz 

It depends on what you want to do.
Most of the features are available for free: mental command, facial expressions, motion data, performance metrics...
But you need a paid subscription to get the raw EEG data.
https://emotiv.gitbook.io/cortex-api/#license
