### ISSUE TITLE
How To Connect with Cortex API?

### ISSUE THREAD

**Issue by shathaalotaibi** [Emotiv/cortex-example#152]
Is it mandatory to have the Emotive Launcher running, to be able to call wss://localhost:6868?

**Comment by bchaperon** [comment]
Hi @shathaalotaibi 

You must install the EMOTIV Launcher and run it once to login with your EMOTIV id. After that, you don't have to run it to use the Cortex API.
Installing the Launcher also installs the CortexService, which is a background process. When you connect to wss://localhost:6868 you actually connect to the CortexService, you don't connect to the Launcher application.

**Comment by shathaalotaibi** [comment]
I am developing an Android application and I cannot download the Emotiv launcher on it, is there another way?

**Comment by shathaalotaibi** [comment]
I am developing an Android application and I can not download the Emotiv launcher on it, is there another way?

**Comment by bchaperon** [comment]
On Android you must install the application "EMOTIV Launcher". But this app is currently in Beta.
The only way to get it is to send a request to the EMOTIV customer support.
https://www.emotiv.com/contact-support/
