### ISSUE TITLE
Can I develop an Android app with cortex API ?

### ISSUE THREAD

**Issue by TeifAlSulaim** [Emotiv/cortex-example#153]
Can I develop an Android app with cortex API ?

**Comment by bchaperon** [comment]
Hi @TeifAlSulaim 

Yes, you can develop an Android app. But first, you must install EMOTIV Launcher on your Android device. This app is currently in Beta.
The only way to get it is to send a request to the EMOTIV customer support.
https://www.emotiv.com/contact-support/
