### ISSUE TITLE
Inject Maker error response

### ISSUE THREAD

**Issue by iBibek** [Emotiv/cortex-example#154]
Hello,
I am using Cortex V2 and have been trying to insert the inject using injectMarker. But, I keep on getting this error back.
 {'code': -32115, 'message': 'The marker timestamp is invalid (too far in the past).'}
Any idea on what's wrong?

**Comment by bchaperon** [comment]
Hi @iBibek 

When you inject a marker, the time in your request cannot be too far in the past. You should inject your markers in real time, when the event you want to marks happens.

https://emotiv.gitbook.io/cortex-api/error-codes#32115-the-time-of-the-marker-is-too-far-in-the-past

Also make sure that you use the right unit. Your time must be in milliseconds.
