### ISSUE TITLE
Deployment of the web-app on linux server

### ISSUE THREAD

**Issue by nigoshaya** [Emotiv/cortex-example#158]
Hello all!

I am developing a web application with Python and Cortex API. 
At the moment my application is only running locally and I am looking for a way to deploy the application on the Internet on a Linux server. Can you please explain me if this is possible and how?

Thanks a lot.

**Comment by bchaperon** [comment]
Hi @nigoshaya 

You can install Cortex on your Linux server. But this Cortex won't be able to connect to your Emotiv headset. You must install Cortex locally so it can connect to you headset via Bluetooth or USB dongle.
