### ISSUE TITLE
wss://emotivcortex.com:54321 :x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by notnot** [Emotiv/cortex-example#16]
The emotivcortex.com:54321 websocket server doesn't have a proper certificate for secure websockets. I can only connect to it by skipping the certificate verification. Please fix this ASAP.

**Comment by notnot** [comment]
I downloaded and installed the Cortex software for OS X from the emotive website. The CortexUI application does work, i can log in with it.
I have started to write an application that communicates with the Emotiv Insight using websockets, and that is where i notice that wss://emotivcortex.com:54321 can only be connected to when i skip certificate verification. I am writing my application in the Go language, using the websocket package. I have tried connecting to other urls that provide websocket services using the same code, and there i don't have to skip certificate verification to make the connection to the server. 
I have tried an online websocket demo (www.websocket.org), and yes it can connect, but it is probably skipping verification as well. If i look in the chrome developer menu, WS tab, you see that wss://emotivcortex.com:54321 has a very different response than for instance wss://echo.websocket.org (which is connected to properly by my code, without the need to skip verfication.

**Comment by nguoithichkhampha** [comment]
I see the difference but it's not related to that is valid certificate or not. If cortex uses a self signed certificate, you can not connect to Cortex on chrome extension. I think main issue is Cortex use local machine as a host and the method verify certificate on Go doesn't accept that.

**Comment by notnot** [comment]
Yes, perhaps that is true, i am not (yet) a TLS expert. It isn't a big problem for me that i have to skip verification at this point. I will look deeper into it later. Right now getting the data is more important. 

If there is a Go programmer at Emotiv, i hope he or she will look into this issue, and develop example code about how to establish a secure connection.

**Comment by nguoithichkhampha** [comment]
@notnot , thanks for your feedback. One more thing, even you ignore verify. it only not trust certificate, already is a secure connection. the data send between server and client is encrypted. you can use wireshark to double check.

**Comment by notnot** [comment]
Aha yes, connecting to wss://emotivcortex.com:54321 doesn't need an internet connection, it indeed seems to connect to a server on localhost. How does it know that emotivcortex.com is a local service?

**Comment by notnot** [comment]
Thanks @bchaperon 
i didn't know it could be done as easy as this! Nice to know.
