### ISSUE TITLE
Mobile app developing language

### ISSUE THREAD

**Issue by shathaalotaibi** [Emotiv/cortex-example#161]
I have a query, is there anyone who tried to develop a mobile application with Emotiv successfully? If the answer is yes, which language did they use?

**Comment by bchaperon** [comment]
Hi @shathaalotaibi 
To create a mobile application, you have 2 options:

1. Install the application "Emotiv Launcher" on iOS or Android. This app creates a WebSocket server, exactly like Cortex on Windows/macOS. So you can write your application with any language.
2. Link your mobile application with the Cortex library. So your app doesn't depend on Emotiv Launcher. The library provides an API in Objective-C (iOS) and Java (Android) https://emotiv.gitbook.io/cortex-library-for-mobile/ 

Both solutions are currently in Beta. Please contact the EMOTIV customer support to gain access.
https://www.emotiv.com/contact-support/
