### ISSUE TITLE
The type of data 

### ISSUE THREAD

**Issue by Batuhanyucel** [Emotiv/cortex-example#162]
I am getting real time data with cortex sub.data py but ı can’t understand what is the type of this data? 
what should ı do for reachimg  voltage values from these datas  
![Uploading BFA830F5-36D1-4E19-9834-5F0FAC2B5F64.jpeg…]()

**Comment by bchaperon** [comment]
Hi @Batuhanyucel 
The format of the data you receive from the Cortex API is described here:
https://emotiv.gitbook.io/cortex-api/data-subscription/data-sample-object

**Comment by Batuhanyucel** [comment]
İt says “ For each EEG sensor, you get 1 value in microvolt” but values are over 400 mV it is real ?

**Comment by Batuhanyucel** [comment]
Correction : over4000

**Comment by bchaperon** [comment]
Hi @Batuhanyucel 
Yes, the values usually are around 4200 micro volts. It is expected.
But before you do analyze the data, it is recommended that you remove the DC offset.
https://emotiv.gitbook.io/emotivpro-v3/notes-on-the-data/dc-offset

**Comment by Batuhanyucel** [comment]
Thank you
