### ISSUE TITLE
Print Raw Data Code

### ISSUE THREAD

**Issue by Batuhanyucel** [Emotiv/cortex-example#163]
I got eeg signals real time from emotiv but ı have to print them too. All eeg companies which supporting open source codes are already shared printing Raw EEG datas with python but emotiv doesn't. Can you help me about this ?

**Comment by Batuhanyucel** [comment]
İf we don't look raw eeg signals ,the eeg datas just number.

**Comment by bchaperon** [comment]
Hi @Batuhanyucel 
What do you mean by "printing the data"?
Do you want draw the EEG graph on your screen?
EMOTIV doesn't provide the code to do that, but it should be quite easy to do it in Python using a library like matplotlib.
You can also use the EMOTIV PRO software to see the graph in real time.

**Comment by Batuhanyucel** [comment]
Okay ı will try but ı have one more question. I need to put every single channel info in single array . Like {AF3 electrode:4168 , time :1.600}. How can ı do this can you help me ?   Because before using matplotlib ı  think ı need to seperrate and throw in directory . every single channel.

**Comment by Batuhanyucel** [comment]
if you tecah me for a single channel ı can do others sir.
