### ISSUE TITLE
Sensors status

### ISSUE THREAD

**Issue by shathaalotaibi** [Emotiv/cortex-example#165]
Is there a way with the cortex API to know if each sensor receives signals strongly, weakly, or not positioned correctly (green, yellow, red) the same as available in EMOTIV applications?

**Comment by bchaperon** [comment]
Hi @shathaalotaibi 

Yes, the data you are looking for is the Contact Quality and/or the EEG quality.

To receive this data in real time, you must subscribe to the stream "dev" to get the contact quality.
You can also use the stream "eq" to get the EEG Quality.
https://emotiv.gitbook.io/cortex-api/data-subscription

Please check the Emotiv PRO user manual for more details about CQ and EQ.
https://emotiv.gitbook.io/emotivpro-v3/emotivpro-menu/contact-quality-map/contact-quality-cq-vs.-eeg-quality-eq
