### ISSUE TITLE
Problem with authorization 

### ISSUE THREAD

**Issue by CarlosA-Mtz** [Emotiv/cortex-example#169]
Greetings, I bought the student license for Emotiv pro and the following issue appears:
ine 137, in authorize
    self.auth = result_dic['result']['cortexToken']
KeyError: 'result'

**Comment by tungntEmotiv** [comment]
Hi @CarlosA-Mtz ,

Which python example did you run ? 
Please help to set debug_mode=True in the __init__ function as below. We need more log to debug
`
    def __init__(self):
        self.c = Cortex(user, debug_mode=True)
`
and make sure you fill  below user object
`user = {
    "license" : "",
    "client_id" : "your client id",
    "client_secret" : "your client secret",
    "debit" : 100
}
`
Please note that when you run the example firs time, you might need to approve your application via Emotiv Launcher.

**Comment by CarlosA-Mtz** [comment]
I followed the instructions as they appear in the video, last time the same error happened to me but they told me that I needed the license, which I already got

**Comment by tungntEmotiv** [comment]
Hi @CarlosA-Mtz ,

Could you send us your emotivID and the clientId via email tungnguyen@emotiv.com ? We will check more

**Comment by tungntEmotiv** [comment]
Thanks @CarlosA-Mtz ,
We have received your email. Because you create an application which require EEG access. So you need request API access via https://www.emotiv.com/cortex-sdk-application-form/
