### ISSUE TITLE
How can we get Performance Matrix from cortex ?

### ISSUE THREAD

**Issue by ashwath1295** [Emotiv/cortex-example#170]
I have the pro license. I want to get Live Performace Matrix from the Cortex.
Which Python script should I use to do so?

**Comment by tungntEmotiv** [comment]
Hi @ashwath1295 ,

You can use sub_data.py with a modification at line 205
streams = ['met']  # for performance metrics

**Comment by ashwath1295** [comment]
Thank you for your help
