### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.cortex'

### ISSUE THREAD

**Issue by rmwvamp** [Emotiv/cortex-example#172]
I executed the following code `import asyncio
import time
import sys
import os
import threading
from pynput import keyboard
from pynput.mouse import Button, Controller
from lib.cortex import Cortex
from datetime import datetime

mouse = Controller()
terminated = False`

I have installed pypnut, web sockets, websocket-client,cortex-cli,cortex,cortex2

**Comment by bchaperon** [comment]
Hi @rmwvamp 

I suppose it should be `from cortex import Cortex` instead of `from lib.cortex import Cortex`.

**Comment by rmwvamp** [comment]
On doing the same. It shows the following error: 
[C:\Users\User>python -u "c:\Users\User\Desktop\experiment\main.py"
Traceback (most recent call last):
  File "c:\Users\User\Desktop\experiment\main.py", line 8, in <module>
    from cortex import Cortex
ImportError: cannot import name 'Cortex' from 'cortex' (C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cortex\__init__.py)](url)
