### ISSUE TITLE
Inquiries about the POW feature in Cortex API?

### ISSUE THREAD

**Issue by shathaalotaibi** [Emotiv/cortex-example#176]
I have a query about the POW function; what did you do with the EEG to get these values? 
I need to understand what happened in the background.  

Also, can you tell me what is the MAX and MIN Values for each value in the resulted array?

**Comment by bchaperon** [comment]
Hi @shathaalotaibi 

The band power are calculated every 0.5 seconds, using the last 2 seconds of EEG data.
The steps are:
1. High pass filter
2. Remove DC offset (for each EEG channel, remove the mean value)
3. Hanning window
4. FFT
5. make the sum of the squares of the FFT values
