### ISSUE TITLE
{'error': {'code': -32027, 'message': 'The application do not have permission to use the license.'}, 'id': 4, 'jsonrpc': '2.0'}

### ISSUE THREAD

**Issue by vinay-sourcecodes** [Emotiv/cortex-example#177]
i have a student license of cortex , when i try to run authorize() without the license in the parameters, i get {'error': {'code': -32002, 'message': 'Invalid License Key.'}, 'id': 4, 'jsonrpc': '2.0'} and when i pass license in the parameters i get {'error': {'code': -32027, 'message': 'The application do not have permission to use the license.'}, 'id': 4, 'jsonrpc': '2.0'}.
 reached out to the cortex support, they said that student licenses have EEG api access but i am not able to access.

**Comment by tungntEmotiv** [comment]
Hi @vinay-sourcecodes ,

Have you request EEG access via https://www.emotiv.com/cortex-sdk-application-form/ ?
