### ISSUE TITLE
Stuck at executing https://github.com/Emotiv/cortex-v2-example/blob/master/python/sub_data.py

### ISSUE THREAD

**Issue by vishwasdalal** [Emotiv/cortex-example#179]
I do not have the license to the raw data stream, I want to access the free APIs
I made the following changes to https://github.com/Emotiv/cortex-v2-example/blob/master/python/sub_data.py

# list data streams
    streams = ['mot','met','pow', 'dev']
    s.start(streams)

My python is stuck at this
![unnamed](https://user-images.githubusercontent.com/41986273/170810194-96ffa0da-774a-4956-a383-94e0cd394df7.png)

**Comment by tungntEmotiv** [comment]
Hi @vishwasdalal ,

I think the problem might from missing a python lib such as python-dispatch or something wrong when receive response message from websoscket. So 

1) do you install python-dispatch via "pip install python-dispatch" ? 
2) Please add a debug log to on_message function at cortex.py as below? And let us know the result
`
def on_message(self, *args):
        recv_dic = json.loads(args[1])
        print( recv_dic)
        if 'sid' in recv_dic:
`
Thanks

**Comment by vishwasdalal** [comment]
hi @tungntEmotiv 
1.do you install python-dispatch via "pip install python-dispatch" ?
- I have python-dispatch installed already
2. Please add a debug log to on_message function at cortex.py as below? And let us know the result
- well I inserted a breakpoint at **on_message** and the program is stuck before that, **on_message** is never called.

**Comment by vishwasdalal** [comment]
Hi @tungntEmotiv 

![image](https://user-images.githubusercontent.com/41986273/170921825-996ab70b-22f3-4ca5-9a18-a1d9c5dc1cd1.png)


this is where this shows up, this is in **threading.py**
**cortex.py** line 107 calls this   **self.websock_thread .start()**
