### ISSUE TITLE
insight often returns identical stream data at a very high frequency 

### ISSUE THREAD

**Issue by notnot** [Emotiv/cortex-example#18]
I am seeing erratic behaviour from my Emotiv Insight after i subscribe to receive a 'pow' stream. Most of the times, after subscribing, the device sends identical json data very quickly after each other (thousands of times a second). Sometimes it sends proper data, after subscribing, at a much lower rate (about 8 times a second). Is my device broken? 

I am using the latest Cortex software on OS X, i installed the upgrade today, but it didn't solve my problem.

**Comment by notnot** [comment]
Note that when i unplug the USB dongle and plug it back in, the first session/subscribe always works. After that, the headset gives the corrupt and identical data at high speed. 

I think unplugging/plugging in the bluetooth dongle resets the emotiv websocket server, and that is why it then works (one time only). Switching the headset off and back on has no effect.

I will try the community SDK soon, i hope it is more reliable!

**Comment by nguoithichkhampha** [comment]
Thread get band power data run with interval 125 ms. first time headset connected, buffer data is not full so, it output 8 values/second -> this is speed of the detection. You see the output about 1000 value/s because have many response with same value. Basically, it only has 8 new values / second.

**Comment by notnot** [comment]
I can't verify it right now, because i need to charge my headset.

I assumed that the cortex websocket server would send a new pow stream data event 8 times per second, always. It makes no sense sending data each millisecond when it doesn't change so often, it is terribly inefficient! It would then even make more sense to subscribe/get data/unsubscribe 8 times a second... 

When i use the headset the first time after plugging in the USB dongle, i can receive thousands of pow data events, at 8 times per second. This is how it should always behave from the users point of view, device buffer full or not...

**Comment by notnot** [comment]
I have the headset charger again, and i did some experiments. When receiving the pow data continuously, without adding a pause between the reading, i do get new different values 8 times a second, you are right. If i add a pause of 125 ms between reading, something strange happens: i don't get new values each time, but i get an irregular sequence where most values are identical and some are different. So you can't poll the device at a lower rate either...

I will try an approach where stream data is read continuously, without a pause, and let the software skip all data packets that have identical data as the previous data. I hope i can get a stream of valid data points this way, but even if it wil work, it is so inefficient :(

**Comment by notnot** [comment]
I tried reading other types of streams ("mot", "fac", "met" and "dev") and these all work as expected: a data frame is sent only when there is actual new data. Why does behave "pow" differently? A bug?

**Comment by patdotme** [comment]
@notnot it is related to the bug in https://github.com/Emotiv/cortex-example/issues/24 as well so we will fix this in the upcoming release.

**Comment by notnot** [comment]
Update: Cortex 1.4 fixes this issue, thanks.
