### ISSUE TITLE
 How do I subscribe to performance metrics data in Unity

### ISSUE THREAD

**Issue by tearoue323** [Emotiv/cortex-example#182]
As title， How do I subscribe to performance indicator data in Unity, I just want to get the foc and eng data, is it in DataStreamManger.cs or PMDataBuffer.cs?

**Comment by tungntEmotiv** [comment]
Hi @tearoue323 ,

To get the performance metrics data you can use EmotivUnityItf.cs and follow the below steps:
1) call Init() to set application configuration ( clientId, client Secret...) and if you want to save data to buffer before obtaining the data , please set isDataBufferUsing = true
2) call Start() to start a websocket and authorizing 
3) CreateSessionWithHeadset(string headsetId)  to create a working session with your headset
4) call SubscribeData(List<string>() {"met"}) to subscribe performance metrics
5) If you use Data buffer -> you need to call GetPMData(string label) to get the pm data. If you don't use the data buffer -> you will get the data at OnPerfDataReceived()
You can reference to https://github.com/Emotiv/cortex-v2-example/blob/master/unity/Assets/SimpleExample.unity for more detail
Thank you

**Comment by tearoue323** [comment]
@tungntEmotiv  I will give it a try ,thanks.
