### ISSUE TITLE
Python Example Dispatch Reference Error

### ISSUE THREAD

**Issue by philhyp** [Emotiv/cortex-example#183]
from pydispatch import Dispatcher

can not be referenced, editor asks me to initialize Dispatcher in the lib, how could we resolve this?

**Comment by tungntEmotiv** [comment]
Hi @philhyp ,

Have you installed  python-dispatch via "pip install python-dispatch" ?

**Comment by philhyp** [comment]
@tungntEmotiv yes, also tried PyDispatcher

**Comment by philhyp** [comment]
> Hi @philhyp ,
> 
> Have you installed python-dispatch via "pip install python-dispatch" ?

@tungntEmotiv yes, also tried PyDispatcher - could it be a version issue?

**Comment by tungntEmotiv** [comment]
@philhyp ,

Ah I mean that python-dispatch (https://pypi.org/project/python-dispatch/) not PyDispatcher (https://pypi.org/project/PyDispatcher/) . They are not the same
