### ISSUE TITLE
Invalid Key licence in Python with registered Cortex app

### ISSUE THREAD

**Issue by craigvear** [Emotiv/cortex-example#184]
Running sub.data.py. Have supplied your_app_client_id & your_app_client_secret in the main() as given in EMOTIV account.
Headset Insight2 connected, and Cortex App showing in EMOTIV launcher.

Error returns :

```
{
    "jsonrpc": "2.0",
    "method": "authorize",
    "params": {
        "clientId": "removed for security",
        "clientSecret": "removed for security",
        "license": "",
        "debit": 10
    },
    "id": 4
}
handle_error: request Id 4
{'code': -32002, 'message': 'Invalid License Key.'}
```

Why invalid licence?

**Comment by nguoithichkhampha** [comment]
@craigvear , because you send empty license in the request
`"license": ""`
if you don't know exactly your license id. you can remove the params "license", our system will choose the best match 
`{
    "jsonrpc": "2.0",
    "method": "authorize",
    "params": {
        "clientId": "removed for security",
        "clientSecret": "removed for security",
        "debit": 10
    },
    "id": 4
}`

**Comment by craigvear** [comment]
Thanks. Which line of code do I change for that ? Is it in cortex.py? FYI I am using your sub_data.py out of the box.

**Comment by craigvear** [comment]
removed licence param in LOC449 in cortex.py. same response

```
 {
    "jsonrpc": "2.0",
    "method": "authorize",
    "params": {
        "clientId": "removed for security",
        "clientSecret": "removed for security",
        "debit": 10
    },
    "id": 4
}
handle_error: request Id 4
{'code': -32002, 'message': 'Invalid License Key.'}
```

**Comment by nguoithichkhampha** [comment]
@tungntEmotiv pls help to check this issue

**Comment by craigvear** [comment]
I now seem to be getting the following:

handle_error: request Id 4
{'code': -32130, 'message': 'The cloud token is refreshing.'}

**Comment by tungntEmotiv** [comment]
@craigvear ,
Do you have PRO license or free license? 
If you only have free license, please don't tick "My App required EEG access"  as below:
![image](https://user-images.githubusercontent.com/21233798/182992469-c77fb2fa-cf8d-4478-a258-361871f67384.png)

If you have PRO license, but still get the issue. Please send us your clientID and emotivID via email tungnguyen@emotiv.com We will check more.
Thanks

**Comment by craigvear** [comment]
Have basic license. Already ticked eeg for my app. 

UPDATE:

yep - now works. Thank you for your help. perhaps you should make this process clearer for developers.


pm data: {'met': [True, 0.642478, True, 0.74391, 0.0, True, 0.363572, True, 0.456362, True, 0.658906, True, 0.140554], 'time': 1659718532.1614}
pm data: {'met': [True, 0.404533, True, 0.528303, 0.0, True, 0.32198, True, 0.385608, True, 0.35132, True, 0.065574], 'time': 1659718542.1586}

**Comment by craigvear** [comment]
working - thank you
