### ISSUE TITLE
When running python/sub_data.py, it interrupted at this step.

### ISSUE THREAD

**Issue by KevinsWang** [Emotiv/cortex-example#185]
Subscribe __init__
websocket opened
do_prepare_steps--------------------------------
check has access right --------------------------------

**Comment by tungntEmotiv** [comment]
@KevinsWang ,
Could you help add a debug as below in https://github.com/Emotiv/cortex-v2-example/blob/4b35cd74c2b7b478c68dc67a3ae0dca48612701a/python/cortex.py#L131
at line 373 . I want to see the response
`
 def on_message(self, *args):
        recv_dic = json.loads(args[1])
        print(recv_dic)
`
you mean that the program is interrupted suddenly at "check has access right" or do nothing any process after the step ?
