### ISSUE TITLE
Can I use academic PRO license with a different emotivID than the one that applied for the license

### ISSUE THREAD

**Issue by nwagu** [Emotiv/cortex-example#186]
Hi,

My school lab has an academic PRO license. I don't have access to the Emotiv account that was used to purchase the license but I have the license key. I have my personal emotiv account and emotiv id. If I create an application with my account, can I use the client id and client secret of the application with the license key that was not purchased by me?

**Comment by thamha-emotiv** [comment]
Hi nwagu,
If you have a valid PRO license key, please make sure your school lab has applied for SDK access for that PRO license key, and after that you can register your client ID and client secret and use that license key to unlock access to raw EEG and create the application. Please email our support team through this form  [https://www.emotiv.com/contact-support/](https://www.emotiv.com/contact-support/)  in case you have any further questions or need more guidance.
