### ISSUE TITLE
License permission problem - Student License

### ISSUE THREAD

**Issue by kaali728** [Emotiv/cortex-example#189]
Hello, I have a problem with python subscribe.py example. I get 

`{'code': -32027, 'message': 'The application does not have permission to use the license.'}`

I have purchased a EmotivPRO student license. 

my emotiv ID alika and client Id: SIexmTFqD5NGpYPTppg5ZgFS0V9i7Kdex0OaxzVC

**Comment by nguoithichkhampha** [comment]
@kaali728 , You need to fill out the Cortex SDK Application Form to be able use the license in your app.
