### ISSUE TITLE
Question: Why cant i connet to Websocket?

### ISSUE THREAD

**Issue by superseppl** [Emotiv/cortex-example#19]
Operating system: Windows 10 64 Bit
language version: C++
Cortex version:  v.1.3.0 

---
Hello guys, 
I want to work a little bit with the epoc+ device and cortex, but unfortunately I can not connect to the Websocket wss://emotivcortex.com:54321 with Qt. 
I tried the following:
 - connect to wss, I'll get the error: QAbstractSocket::UnsupportedSocketOperationError
 - connect to ws: QAbstractSocket::RemoteHostClosedError
 - but if i connect with Simple WebSocket Client in Chrome, it works.
 - and also if i connect in qt to ws://echo.websocket.org

The websocket is running in the background and i also changed the sessioncreator with the necessary informations like emotiv id and stuff.

Maybe I forgot a little thing but can you help me?
Thanks in advance.

**Comment by nguoithichkhampha** [comment]
Did you try our qt example ?

**Comment by superseppl** [comment]
Yes it was with the latest cortex-example.

**Comment by nguoithichkhampha** [comment]
which qt version you are using ? we will ask qa team test example again.

**Comment by superseppl** [comment]
It is qt 3.9.5 with the community edition.

**Comment by nguoithichkhampha** [comment]
You should update your qt. should run on qt 5.10 or newer.

**Comment by superseppl** [comment]
Well I updated it, but still the same.
Maybe there is something wrong with my setup.
![setup_qt](https://user-images.githubusercontent.com/36512880/41345238-614ca4b0-6f03-11e8-9cfa-0595b94bb983.PNG)

**Comment by nguoithichkhampha** [comment]
@superseppl . Did you resolve your issue ?

**Comment by superseppl** [comment]
Sorry, for my late response. I had alot of work and tried it with the old sdk instead. 
I don't know, I downloaded the binary and tried the different implementations from this link: https://stackoverflow.com/questions/20351155/how-can-i-enable-ssl-in-qt-windows-application
but unfortunately it won't work. Maybe I miss something.

**Comment by colaspolarbear** [comment]
Operating system: Windows 10 64 Bit
language version: C++
Cortex version: Master Branch as of 01/11/19
Qt 5.12.0 MSVC 2017 64bit

Hello all, 

I am trying to run the Motion example in Qt and it compiles and "runs" exiting with 0. However, the I cannot get wss://emotivcortex.com:54321 to open or the executable to run. I also get the following error under the general messages tab, " Clang Code Model: Error: The clangbackend executable "D:\Qt\Tools\QtCreator\bin\clangbackend.exe" could not be started (timeout after 10000ms)."

Also, I have tried adding OpenSSL 32bit and 64 bit. When I do the app will continually "Looking for a headset". 

Does anyone know how I can get the websocket to open?

Please let me know if more information may be helpful to understand and resolve my issue. 

Thank you for your time.
