### ISSUE TITLE
run cortex.py --ImportError: cannot import name 'Dispatcher'

### ISSUE THREAD

**Issue by Yangdudua** [Emotiv/cortex-example#190]
i run cortex.py,but it show "ImportError: cannot import name 'Dispatcher'".Then i charge it to dispatcher and it is ok.But now it show
Traceback (most recent call last):
  File "E:\data\python\cortex-v2-example-master\python-cortex\cortex.py", line 60, in <module>
    class Cortex(dispatcher):
TypeError: module.__init__() takes at most 2 arguments (3 given)

**Comment by tungntEmotiv** [comment]
Hi @Yangdudua ,

Does your project reference the latest our python example ? Could you try run sub_data.py and let us know the result ?

**Comment by danielgonzalez3** [comment]
similar issue here:
`ImportError: cannot import name 'Dispatcher' from 'pydispatch' (`

maybe we can lockdown on `requirements.txt`?

**Comment by danielgonzalez3** [comment]
https://stackoverflow.com/questions/70019526/importerror-cannot-import-name-dispatcher-from-pydispatch

helped me out :)
