### ISSUE TITLE
Regarding error 32027

### ISSUE THREAD

**Issue by Cha-cha-dkvdf** [Emotiv/cortex-example#192]
Regarding error 32027, do I need to fill out the Cortex SDK Application Form before I can give the application permission to use the license?

**Comment by nguoithichkhampha** [comment]
@Cha-cha-dkvdf yes, you need to do it to use the license in your app.

**Comment by Cha-cha-dkvdf** [comment]
The Order Number for your PRO License* message is not a string of letters and numbers with four '-'s in it.

**Comment by nguoithichkhampha** [comment]
where do you see this error ? when you fill the form ?

**Comment by Cha-cha-dkvdf** [comment]
Thank you, this problem has been solved.

**Comment by a1848580190** [comment]
> 
How do you solved this problem?I meet this problem recently,but I don't konw how to fix it.
