### ISSUE TITLE
"error": {         "code": -32022,         "message": "Device limit on this license has been reached."

### ISSUE THREAD

**Issue by a1848580190** [Emotiv/cortex-example#194]
This problem occurs when the same code runs on different computers

I don't understand what the device limit means.

**Comment by nguoithichkhampha** [comment]
"device" mean your computer. That mean your new computer can not use the license

**Comment by a1848580190** [comment]
> "device" mean your computer. That mean your new computer can not use the license



> "device" mean your computer. That mean your new computer can not use the license

This is so inconvenient, is there any way to deal with this?

**Comment by a1848580190** [comment]
> "device" mean your computer. That mean your new computer can not use the license



> > "device" mean your computer. That mean your new computer can not use the license
> 
> > "device" mean your computer. That mean your new computer can not use the license
> 
> This is so inconvenient, is there any way to deal with this?

Or if I can change the device

**Comment by nguoithichkhampha** [comment]
@a1848580190 , you can contact our support team to reset device for your license.

**Comment by a1848580190** [comment]
> I can change the device

ok ,thanks
