### ISSUE TITLE
warning 103 is not sent when powering off a virtual headset 

### ISSUE THREAD

**Issue by landret** [Emotiv/cortex-example#196]
Hi,
when powering off a real headset, warning 103 is sent 30s after communication is lost. However, warning 103 is never sent when powering off a virtual headset, while it should for consistency.

**Comment by nguoithichkhampha** [comment]
@landret , here is the meaning of warning 103

> Cortex disconnected a headset because it didn't receive any data from this headset for more than 30 seconds. This can happen if the headset goes out of range of the computer, or if the wireless connection is of poor quality.

with virtual headset, this problem does not happens . so, we don't send warning 103.
