### ISSUE TITLE
Wireless signal returned is either 0.0 or 1.0

### ISSUE THREAD

**Issue by landret** [Emotiv/cortex-example#198]
Hi,
the wireless signal should range between 0.0 and 1.0. However, either 0.0 or 1.0 is returned by my headsets, nothing between. 
Test done with 
- EPOC+ S/N 4A2C01C7 firmware 0x634
- Insight v1.0 S/N 5968367B firmware 0x5014

**Comment by nguoithichkhampha** [comment]
@landret , how do you get wireless signal from cortex ? did you get correct order from data stream ?

**Comment by landret** [comment]
@nguoithichkhampha 
Example for the insight headset: the order is : ["Battery","Signal",["AF3","T7","Pz","T8","AF4","OVERALL"],"BatteryPercent"]

Example of data sample I receive for the "dev" data stream (I am not wearing the headset here so the sensors signal quality is bad) :

{"dev":[3,0.0,[0,0,0,1,0,0],59],"sid":"09ff2962-dc7b-40f6-843e-c98691af56d9","time":1680252416.4949}

or

{"dev":[3,1.0,[0,1,0,0,0,0],64],"sid":"09ff2962-dc7b-40f6-843e-c98691af56d9","time":1680252371.4733}

For the wireless signal, the Json data sample shows either 0.0 or 1.0 when I move the headset away from the dongle.

**Comment by nguoithichkhampha** [comment]
@landret Can you try to record data and send me an example file ? how long you see the wireless signal = 0.0. in theory, wireless signal = 0.0 mean very bad signal.

**Comment by landret** [comment]
@nguoithichkhampha Here is a recording. 

[sample.txt](https://github.com/Emotiv/cortex-v2-example/files/11187177/sample.txt)

**Comment by thamha-emotiv** [comment]
Closed it, we supported in a private call.
