### ISSUE TITLE
Emotiv pro premium license

### ISSUE THREAD

**Issue by rajatanand86** [Emotiv/cortex-example#199]
Hi. We are using emotiv pro premium license to use the API. The license is right now installed in our desktop. 
We want to change it to have license present in software installed in our laptop. 
Can somebody help?

**Comment by nguoithichkhampha** [comment]
hi, please contact our customer support team to reset device for your
license.

**Comment by rajatanand86** [comment]
Can you please send customer support email?

**Comment by nguoithichkhampha** [comment]
you can send to hello@emotiv.com

**Comment by rajatanand86** [comment]
Can't read this mail id. Please send to rajatanand86@gmail.com

**Comment by nguoithichkhampha** [comment]
> Can't read this mail id. Please send to [rajatanand86@gmail.com](https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=rajatanand86@gmail.com)

I updated the comment.
