### ISSUE TITLE
I purchased pro license, filled SDK request form, customer support never follows up

### ISSUE THREAD

**Issue by junpengqiu** [Emotiv/cortex-example#201]
I need to access raw EEG data stream from my EPOC X. From Emotiv policy, I need to:
1. buy a pro license
2. fill and submit the SDK request form

I did both but the customer support only reached me once with bunch of questions regarding my org affliation and my purpose of grabbing those data, below is what I responded:

> I have no organization affiliation.
> I am doing a personal project:
> I am going to record my own EEG data, and then apply this data to train a BERT alike model I built.
> The EEG data is being recorded when I am watching a screen flashing. The screen flashing pattern will also be recorded.
> The using this data pair, I wanna train a model to predict screen flashing with my EEG info. So then I can control screen flash with my brain.
> Now, please kindly activate the license I have already purchased so I can start capturing my EEG data.

And then your customer support never follows up.
Is this because I am not from some big organization so helping me out is not your priority.

I knew github issues is not good place for customer support of Emotiv but you leave me no places to go to.
So my dear Emotiv developers, please help me activate my access to EEG data stream since I have paid all the price I need to. My Emotiv ID is naminoqiu@gmail.com, there is only one license under my Emotiv Account, activate it so I can send "authorize" request to your websocket for token to get EEG data stream.

**Comment by Emynguyen-Emotiv** [comment]
Hi! It's been a while and I understand that you were provided the license key to continue with your project. Feel free to reach back out to us if you encounter any further issues with our software development kit.
