### ISSUE TITLE
Warning for headset status change

### ISSUE THREAD

**Issue by landret** [Emotiv/cortex-example#203]
Hi,
It would be great to have a warning when headset status changes. 

I am using an Emotiv Insight 1.0. When it is turned off after connecting it from my app (status goes from CONNECTED to CONNECTING), I have no way to know that it was turned off, and have to wait for 30s for the warning stating that Cortex disconnected the headset after timeout. During that time, Data Samples are no longer sent and my app users can think the GUI is frozen because nothing is happening.

If I could receive a warning telling about status change, I could know that the headset was turned off and understand why no Data Samples are no longer received. Also, I don't want to have to call queryHeadset every 2s to check for that.

**Comment by hoangphamemotiv** [comment]
Hi @landret . Thank you for your suggestion. 
In some cases, Cortex doesn't know when headset turned off or it was in a poor connection. Many cases around that. 
in a case of poor connection, data can lost so much, if sending a warning for changing status, it can be spamming . 
anyways, we are thinking about this and will improve it in near future. 

![image](https://github.com/Emotiv/cortex-v2-example/assets/13273932/eff533f5-c12a-45dd-8993-413f1013607e)

**Comment by landret** [comment]
Hi @hoangphamemotiv 
Thanks for your reply.
