### ISSUE TITLE
Error -32027

### ISSUE THREAD

**Issue by ananyakapoor19** [Emotiv/cortex-example#207]
Sent an email to customer support regarding this. They told me to buy another license. 
I already bought the student license and filled the request form for the EEG SDK access.
FYI: the above mentioned are the steps that are required to be done as per the documentation of cortex in order to access EEG data stream. 
I have done both.
However while running any script from the cortex api I was still receiving error -32027. So I reached out to customer support and they told me to buy another license worth $1250. 
After reading through the closed issues on GitHub I came across several people who were facing the same issue. So I'm hoping to get contacted by someone who would guide me through the next steps.

**Comment by tungntEmotiv** [comment]
Hi @ananyakapoor19 ,
the error said that you don't have permission for this  license. If you would like to access raw EEG API to stream raw EEG data in real time to a third party application, you'll need to have a Developer API license. You can contact our Support team to get more information about the licensing option and they can further assist you
