### ISSUE TITLE
[Errno 2] No such file or Directory

### ISSUE THREAD

**Issue by sttsak007** [Emotiv/cortex-example#209]
Hi, I had an issue. After I run the code of metal_command_train.py Normally, it will ask us to authorize but it doesn't show up. It's showing up on the Terminal 
     [Errno 2] No such file or Directory
     on_close
     None
How to fix this?
Thanks.

**Comment by tungntEmotiv** [comment]
@sttsak007 ,
Firstly,  make sure you put right client Id and client secret of your application. Secondly, please try to set a new profile name at line 279 https://github.com/Emotiv/cortex-v2-example/blob/master/python/mental_command_train.py and run again.
Let us know the result. If the issue still happen, please contact to our CSS team (https://www.emotiv.com/contact-support/) to 
set a teamviewer for checking. Thanks
