### ISSUE TITLE
TypeError raised by Promise Subclass in ES6

### ISSUE THREAD

**Issue by jdpigeon** [Emotiv/cortex-example#21]
Operating system: Windows 10
Last upstream commit: d2018a60a02dc0041a8ba8ae1509a85f256b5939
language version: nodejs
---

Hey there,

I'm encountering an error when trying to incorporate the Node.js example into an Electron project: `Uncaught TypeError: undefined is not a promise` raised by the line containing `class ChainablePromise extends Promise {` in the JS Cortex Wrapper.

It seems this is due to the method of extending the Promise class not working in my Electron environment, which makes use of ES6, Webpack and Babel. Running the example raw file works when ran directly with node. The error is encountered when running with babel transpilation.

I'm having a hard time figuring out a way around this without rewriting the Cortex wrapper, which I would prefer not to have to do. Any suggestions?

**Comment by jdpigeon** [comment]
In order to see whether this was just due to my app's unique webpack config, I created a new React app from scratch and tried to include the Cortex wrapper. Getting a very similar error now: `TypeError: calling a builtin Promise constructor without new is forbidden`

**Comment by jdpigeon** [comment]
I'm getting around this error now by directly importing the `cortex.js` wrapper file into my app's `index.html`. This is less than ideal and I foresee errors in testing and packaging the app for production, but will work for until the Cortex wrapper can be update to be ES6 compatible

**Comment by jdpigeon** [comment]
Can we reopen this? I'm going to refactor the example code to remove the Promise subclass and will be filing a PR. Any support would be appreciated

**Comment by jdpigeon** [comment]
Hey there,

I've created a fork of this repo in which the Promise class is used directly instead of being subclassed. This lets the wrapper and the examples run when used in modern ES6 environments. However, it changes the API a bit by requiring `.then` to be called in between Cortex functions instead of being able to chain them.

Here's the fork: https://github.com/jdpigeon/cortex-example

If you're interested in adding this support to this main example even though it might change the way you work with the code I'd be happy to make a PR

**Comment by nguoithichkhampha** [comment]
@jdpigeon , we always welcome all the contribution.
