### ISSUE TITLE
JSONRPC Internal Error during authorize request in Node.js example 

### ISSUE THREAD

**Issue by jdpigeon** [Emotiv/cortex-example#22]
Operating system: Windows
language version: Node.js
Cortex version: v1.3.0

A new issue has arisen in the last week for code that has not changed: JSONRPC internal errors thrown by attempting to call the `authorize` method in the Cortex SDK.

The `raw` example in this repo was working for me just last week. Now the same code hangs and eventually produces an error: `Uncaught JSONRPCError: Internal error
    at Object.requests.(anonymous function)`. I did a little snooping and found that this happened right after the script had ran the APIResult promise for authorizing my user credentials. `inspectAPI` and `getUserLogin` run without incident.

I think this is most likely due to something on Emotiv's end. Is the authentication server down? Has my client_id or client secret expired? I've tried rebooting and reinstalling the Cortex SDK

**Comment by jdpigeon** [comment]
I've been able to get around this issue recently by restarting the Cortex service every time after I encounter an error. I'm not exactly sure what is changing, though. Do any issues in the API commands sent to the Cortex service cause it to break so that it has to be restarted before it can be used again?

**Comment by Khalidxx** [comment]
I'm facing the same issue. Is there any fix or a work-around that doesn't involve ES5 code, since this would be severely limiting?

**Comment by jdpigeon** [comment]
Hey @Khalidxx,

I discovered that this error was getting thrown in my app because my credentials were incorrect. The real problem, I think, is that Cortex doesn't seem to throw informative errors and breaks internally.

Since fixing the error I haven't ported the code back to ES6 yet, so I don't know if it's actually an issue or not. I'd recommend you give it a shot with whatever JavaScript flavour you're working in, but just make sure that you're performing every step 100% correctly and you have all the required licensing

**Comment by Khalidxx** [comment]
@jdpigeon Yeah, you're right, the fault was from my side. It is not really an issue, but it would've been nicer if there were better error messages.
