### ISSUE TITLE
wss protocol in python

### ISSUE THREAD

**Issue by Gowresh7** [Emotiv/cortex-example#23]
Question: How to access wss://emotivcortex.com:54321 in Python 
Operating system: Windows 10
language version: Python 3.6 
Cortex version:  1.3.0
I've tried using the standard websocket library to connect to the wss://emotivcortex.com:54321 but I have no response. Can you please help me in implementing wss protocol in python 3.6
![wss](https://user-images.githubusercontent.com/40490231/41771597-4627bdd2-7633-11e8-83bc-6dc04fcebd5c.jpg)

![wss2](https://user-images.githubusercontent.com/40490231/41806529-6049d740-76dd-11e8-8596-5485ed47569e.jpg)

**Comment by Gowresh7** [comment]
Found a way to do it..!!

**Comment by bestofluckpurnima** [comment]
Could you please share the solution you have found if possible,

**Comment by Gowresh7** [comment]
> Could you please share the solution you have found if possible,
Its pretty simple. You just have to skip the ssl verification..!!
import websocket
import ssl
**_ws = websocket.WebSocket(sslopt={"cert_reqs": ssl.CERT_NONE})_**
ws.connect("wss://emotivcortex.com:54321")
print("Connection Established")

**Comment by NihalKarne** [comment]
> > Could you please share the solution you have found if possible,
> > Its pretty simple. You just have to skip the ssl verification..!!
> > import websocket
> > import ssl
> > **_ws = websocket.WebSocket(sslopt={"cert_reqs": ssl.CERT_NONE})_**
> > ws.connect("wss://emotivcortex.com:54321")
> > print("Connection Established")

really grateful thanks for help
