### ISSUE TITLE
band power

### ISSUE THREAD

**Issue by notnot** [Emotiv/cortex-example#24]
My experience with the Emotiv Insight band power data is this:
I get very low values (mostly between 0 and 4) when i don't move my face.
I get very high values (up to 10000 sometimes more) when i move some muscles in my face.
Do others experience the same?
How are we supposed to measure brain activity when the device is much more sensitive to muscle activations?
Please help. Maybe i have an abnormal brain?

**Comment by bchaperon** [comment]
Muscle signals EMG(mV) are significantly bigger than EEG signals (uV)
So yes, you will get high band powers during facial expressions.
But it would be the same with any EEG system.
Not talking or moving much when wearing the headset helps significantly to get a clear EEG signal.
And there is probably nothing wrong with your brain :)

**Comment by notnot** [comment]
@bchaperon 
Yes i can accept that the muscle signals are much stronger than the EEG signals, but my problem is that there are almost no features left in the EEG signal. For example i get sequences like 0.0 0.0 1.0 0.0 0.0 1.0 1.0 1.0 2.0 0.0 1.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1.0 ... 
In the meantime i bought a Muse 2016 headband which is another consumer EEG headset, and with that device i am getting very detailed signals, also when i don't move my face. 
I think the Emotiv implementation of the band power with the websockets API might be flawed?

**Comment by patdotme** [comment]
hi @notnot which API did you use to get the results? And what were the sequences of the APIs did you use? Would you be able to provide us some of the sample output files from our example and also from Muse please?

**Comment by gmac-emotiv** [comment]
Is it possible you are reading the signals with insufficient resolution? Here is a typical sequence extracted from a clean section of EEG data in the alpha band:

0.59813, 0.683071, 0.706067, 0.659607, 0.55837, 0.434528, 0.324426, 0.249195, 0.209976, 0.192205, 0.184232, 0.181206, 0.180404, 0.18279, 0.192179, 0.212205, 0.238767, 0.26198, 0.272384, 0.265369

These are collected at 0.125s intervals. The numbers presented are in uV ^2 / Hz (spectral power density)
You can convert to decibels (dB) by taking 1/20 log10 ( bandpower ) which has a higher dynamic range for plotting

**Comment by notnot** [comment]
@patdotme 
I used the Cortex websockets API, subscribing to the "pow" stream. This stream doesn't behave properly, see the other issue i filed, which might be related. 

Here is what typical output looks like when i don't move my face:

```
[849] 
EEG band power sample 2018-07-03 11:42:22.110:
	 AF3   3.000   2.000   1.000   1.000   0.000
	  T7   1.000   1.000   0.000   0.000   0.000
	  Pz   3.000   1.000   1.000   1.000   0.000
	  T8   1.000   1.000   0.000   1.000   1.000
	 AF4   0.000   0.000   0.000   0.000   0.000

[850] 
EEG band power sample 2018-07-03 11:42:22.185:
	 AF3   2.000   2.000   2.000   1.000   0.000
	  T7   1.000   1.000   0.000   0.000   0.000
	  Pz   3.000   2.000   1.000   1.000   0.000
	  T8   0.000   1.000   0.000   1.000   1.000
	 AF4   0.000   0.000   0.000   0.000   0.000

[851] 
EEG band power sample 2018-07-03 11:42:22.259:
	 AF3   2.000   2.000   2.000   1.000   0.000
	  T7   1.000   1.000   0.000   0.000   0.000
	  Pz   3.000   2.000   1.000   1.000   0.000
	  T8   0.000   1.000   0.000   1.000   1.000
	 AF4   0.000   0.000   0.000   0.000   0.000

[852] 
EEG band power sample 2018-07-03 11:42:22.336:
	 AF3   2.000   2.000   2.000   1.000   0.000
	  T7   2.000   1.000   0.000   0.000   0.000
	  Pz   3.000   2.000   1.000   1.000   0.000
	  T8   0.000   1.000   0.000   1.000   0.000
	 AF4   0.000   0.000   0.000   0.000   0.000

[853] 
EEG band power sample 2018-07-03 11:42:22.409:
	 AF3   2.000   2.000   2.000   1.000   0.000
	  T7   2.000   1.000   0.000   0.000   0.000
	  Pz   3.000   2.000   1.000   1.000   0.000
	  T8   0.000   1.000   0.000   1.000   0.000
	 AF4   0.000   0.000   0.000   0.000   0.000

```
Here is what typical output looks like when i frown my forehead, for instance:

```
[165] 
EEG band power sample 2018-07-03 11:51:20.053:
	 AF3 9735.000 1891.000 367.000  80.000  35.000
	  T7  46.000  18.000  10.000   7.000   3.000
	  Pz  82.000  10.000   2.000   2.000   1.000
	  T8 116.000   9.000   8.000  16.000  10.000
	 AF4 656.000 405.000 197.000  73.000  23.000

[166] 
EEG band power sample 2018-07-03 11:51:20.185:
	 AF3 7506.000 1526.000 274.000  70.000  30.000
	  T7  36.000  17.000  10.000   6.000   4.000
	  Pz  70.000   8.000   2.000   2.000   1.000
	  T8  97.000   6.000   8.000  24.000  14.000
	 AF4 580.000 348.000 169.000  63.000  20.000

[167] 
EEG band power sample 2018-07-03 11:51:20.309:
	 AF3 4888.000 1054.000 175.000  57.000  26.000
	  T7  34.000  16.000  10.000   5.000   5.000
	  Pz  57.000   6.000   1.000   2.000   1.000
	  T8  77.000   5.000   9.000  33.000  18.000
	 AF4 435.000 253.000 123.000  46.000  15.000

[168] 
EEG band power sample 2018-07-03 11:51:20.434:
	 AF3 2609.000 614.000  94.000  44.000  22.000
	  T7  36.000  15.000   9.000   4.000   6.000
	  Pz  44.000   5.000   1.000   2.000   1.000
	  T8  57.000   5.000  10.000  41.000  21.000
	 AF4 269.000 151.000  73.000  27.000   9.000

[169] 
EEG band power sample 2018-07-03 11:51:20.558:
	 AF3 1107.000 306.000  44.000  32.000  20.000
	  T7  41.000  14.000   8.000   3.000   7.000
	  Pz  33.000   4.000   1.000   2.000   1.000
	  T8  40.000   8.000  13.000  44.000  22.000
	 AF4 130.000  69.000  34.000  13.000   4.000

```

Note that in both cases, contact quaility is reported as 100%.

The Muse headband gives band power output that is typically like this:

```
POW sample 2018-07-03 12:00:18.332: 
	 TP9   0.960   0.858   0.493   1.403   0.537
	 Fp1   0.687  -0.136   1.284   0.725   0.601
	 Fp2   0.114   1.280  -0.005  -0.270   0.000
	TP10  -0.008  -0.145  -0.779  -0.337  -0.332

POW sample 2018-07-03 12:00:18.410: 
	 TP9   0.972   0.892   0.591   1.403   0.541
	 Fp1   0.703  -0.054   1.286   0.725   0.603
	 Fp2   0.144   1.280   0.019  -0.254  -0.009
	TP10   0.006  -0.121  -0.782  -0.325  -0.304

POW sample 2018-07-03 12:00:18.493: 
	 TP9   0.960   0.909   0.647   1.401   0.535
	 Fp1   0.713  -0.001   1.287   0.725   0.603
	 Fp2   0.144   1.280   0.034  -0.248  -0.020
	TP10   0.009  -0.112  -0.785  -0.304  -0.292

POW sample 2018-07-03 12:00:18.575: 
	 TP9   0.897   0.913   0.675   1.392   0.485
	 Fp1   0.715   0.028   1.284   0.725   0.603
	 Fp2   0.144   1.280   0.041  -0.250  -0.033
	TP10   0.003  -0.111  -0.790  -0.278  -0.294

```
As you can see, this is much more detailed compared to the Emotiv Insight results.

**Comment by patdotme** [comment]
@notnot from your output it seems like the significant figures are all gone - has it been casted to int / read as int somewhere? Would you be able to post the raw JSON respond from the "pow" stream please?

**Comment by notnot** [comment]
@patdotme 
@gmac-emotiv 
It is strange to see that the floating point numbers in the JSON "pow" stream results are always whole numbers. Maybe something is wrong in the Cortex driver?

**Comment by notnot** [comment]
A typical JSON reply instance:

```
{
  "pow":[
    3.0,
    4.0,
    2.0,
    2.0,
    1.0,
    2.0,
    2.0,
    1.0,
    0.0,
    1.0,
    0.0,
    0.0,
    1.0,
    1.0,
    2.0,
    1.0,
    0.0,
    1.0,
    0.0,
    0.0,
    2.0,
    1.0,
    1.0,
    0.0,
    0.0
  ],
  "sid":"d8834c5f-ae19-4a3c-8ce0-a861c5e05daf"
}

```

**Comment by patdotme** [comment]
hi @notnot we found the rounding error of band power values in the Cortex service, the new version will include that fix by next week. Thanks for reporting!

**Comment by notnot** [comment]
@patdotme 
Thanks! 
Sadly for me this fix comes to late, i have already switched to the Muse 2016 for my research project. But it is always good to hear that bugs are found and fixed :)

**Comment by patdotme** [comment]
No worries @notnot 
With the EPOC+ headset and a EmotivPRO subscription you will be able to access 14 channels of EEG data - may be something on your next research project ;)

**Comment by nguoithichkhampha** [comment]
@notnot , We have updated Cortex. Please try with Cortex 1.4. Thanks for your feedback.

**Comment by notnot** [comment]
Yes i can confirm that Cortex 1.4 fixes this issue. Thanks, but sadly this comes too late for me...
