### ISSUE TITLE
wss://emotivcortex.com:54321 error with macOS, matlab

### ISSUE THREAD

**Issue by tanujhasija** [Emotiv/cortex-example#25]
Question:

Operating system: macOS High Sierra 10.13.5
MATLAB version: 2017b
Cortex version: Latest (Downloaded last month)

Issue: 

I am trying to connect to cortex through websocket in matlab in macOS. The matlab websocket implementation I am using is:  
https://github.com/jebej/MatlabWebSocket

I get the following error when I run the command 

client = SimpleClient('wss://emotivcortex.com:54321'); 
 
Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Disconnected from server at wss://emotivcortex.com:54321

I know there have been issues posted in the past related to the certificate and some people have suggested to skip certificate verification. Is there a possible solution to this without skipping the certificate verification and in case there isn't is there an example of how to solve this?

Thanks!

**Comment by nguoithichkhampha** [comment]
hi @tanujhasija , we are working on some solutions help computer trust our certificate.

**Comment by tanujhasija** [comment]
Hi @nguoithichkhampha,

Thanks for the prompt reply! If possible could you please give an approximate time by when I could expect a solution?

**Comment by patdotme** [comment]
hi @tanujhasija by skipping the verification the connection is still secure and protected with SSL. Is there anyway you can do that for now with the MatlabWebSocket lib?

**Comment by tanujhasija** [comment]
Hi @patdotme. I couldn't skip the verification using the Matlabwebsocket lib. I skipped the certificate checks from the java control panel but it did not work and continue giving me the same error.
