### ISSUE TITLE
How to change device sampling rate

### ISSUE THREAD

**Issue by jdpigeon** [Emotiv/cortex-example#26]
Working with the new Cortex SDK in Node.js I just realized that I don't seem to have any control over the sampling rate of the device, although it's described as able to work in both 128hz and 256hz modes (Epoc+)

I don't see any way in the documentation to change sampling rate. `createSession` doesn't allow me to pass a `settings` parameter and I don't see any other methods involved in changing headset settings.

Is this possible?

**Comment by colaspolarbear** [comment]
Hello all, I am trying to plug the headset into my computer and the device is not recognized. However, it is recognized if I use the USB dongle only. How do I get the device to be recognized so I can change the sample rate?
