### ISSUE TITLE
Question: Connect to Mac via Websockets (eventually iOS)

### ISSUE THREAD

**Issue by 10donovanr** [Emotiv/cortex-example#3]
Question:

Operating system: iOS 11.2.5/ macOS High Sierra 10.13.3
Last upstream commit (run `git log --author="Robert Lord" | head -n 1`): 

    Add Marker Example

commit bc955aef71d17f0ab46c944eee5206a35aadf613
Author: Benoit <benoit.chaperon@free.fr>
Date:   Thu Jan 11 11:00:47 2018 +0700

language version: Qt version 5.9 (c++)
Cortex version:  Not given (master?, I just downloaded it fresh 2/12/18)

---
Issue:

I get different errors on my iOS and device and my Mac. So first, 1.) does the cortex-example c++ file works on iOS? Because I get this error on iOS.

QAbstractSocket::SocketTimeoutError

On Mac I get this error.

SSL error: "The host name did not match any of the valid hosts for this certificate"
SSL error: "The root CA certificate is not trusted for this purpose"
Socket error: QAbstractSocket::SocketError(13)

Also it would be nice to know if wss connection works. I can't handshake it through 3rd party applications so I don't know if the server is even up and running at wss://emotivcortex.com:54321

2.) If I use C++ I don’t have to use NodeJS as well correct? Those files are not dependent on each other correct?

**Comment by bchaperon** [comment]
Hello
Thank you for your interest in Cortex.
Currently, Cortex is available for macOS and Windows only. The iOS version has not been released yet.

First of all, you must download the macOS Cortex installer from this page: https://www.emotiv.com/developer/

After the installation, you can run the CortexUI application (it is in your application folder) and check if your Emotiv headset is detected. You should also be able to connect to wss://emotivcortex.com:54321 , using the C++ examples, or any web socket client.

You don’t need Nodejs.

**Comment by 10donovanr** [comment]
Are you saying that you can only use the cortex-client API if you have downloaded the cortexUI application and/or the EmotivePro Application? I'm guessing that is the case but the documentation doesn't explicitly say that and there is no reason to assume that this is the case.

I purchased EmotivePro and I downloaded CortexUI. I can connect to the headset through EmotivPro.  CortexUI remains stuck at "connecting to service."

Anyways, then why am I still not able to get a handshake using the EmotivPro and the cortexexamples project on my Mac? I read all of the README's and completed all of the EmotivIDS and passwords, created a client and secret, and added my license but it still doesn't work. I get the following handshake error.

SSL error: "The host name did not match any of the valid hosts for this certificate"
SSL error: "The root CA certificate is not trusted for this purpose"
Socket error: QAbstractSocket::SocketError(13)
Disconnected.

**QUESTIONS**

1.) Is the Socket error cause by the SSL error or some area of the code/naming convention that you guys use or is this a problem on my side.
2.) Can you give me any direction on where to go to learn how to fix this issue.
3.) What time frame are you looking at for getting iOS to work: 3months to 1year, 1year-2years, 1year to 5 years? Or is it completely and utterly unknown?

**Comment by bchaperon** [comment]
In order to use the Cortex API, the only prerequisite is to have the Cortex service running on your computer.

The Cortex service is a background process, it communicates with your headset, and also with the Emotiv cloud (for authentication).
It is also a websocket server. When you run the Cortex client example, you connect to this (local) server. CortexUI and EmotivPRO also connect to the Cortex service.
See the Cortex API documentation for more details: https://emotiv.github.io/cortex-docs/

So, to run your application, you need to install the Cortex service (using the Cortex installer, or the EmotivPRO installer), but you don't need to have CortexUI or EmotivPRO running.

For iOS support, it should be in the next few months, but I don't know exactly when.

**Comment by 10donovanr** [comment]
Knowing that it has to be on and running (and that it is separate from EmotivPro) is helpful. I didn’t interpret that from the documentation. But it works on my mac now. Thanks.
