### ISSUE TITLE
Python Example

### ISSUE THREAD

**Issue by afung-git** [Emotiv/cortex-example#31]
Is there any time frame on releasing some examples on using Python?

**Comment by bchaperon** [comment]
Sorry, we don't plane to release Python examples in the near future.

**Comment by Tylersuard** [comment]
Pretty pleeeeeeeease?

**Comment by Agitolyev** [comment]
@Tylersuard I`ve collected a small codebase in python for my project, you can find it [here](https://github.com/Agitolyev/emotiv-client). The code isn`t great there, and I`m going to rewrite it, but I hope examples will be of some help to you.

**Comment by Tylersuard** [comment]
You, sir, are a gentleman and a scholar.  Thank you.

**Comment by Daniboid** [comment]
Hi all,

So, as far as this goes, I've kinda built my own version of a python way of recording Emotiv Data, very similar to @Agitolyev 's....

However, it seems to be injecting markers fine (i.e., when i call the "injectMarker" method it returns some data to the console), but when I open EmotivPro to create a CSV or EDF of the data there are no markers in it. Can anyone help? I would gladly share the little bit of code that i have for some much needed assistance...

Best,
Dani

**Comment by Daniboid** [comment]
anyone?

**Comment by HongweiN** [comment]
Could you share the code as a project  @Daniboid ?  So we can test it.
