### ISSUE TITLE
Get data raw EEG for Research with EPOC+

### ISSUE THREAD

**Issue by phamkhactuy** [Emotiv/cortex-example#34]
Hi Emotive,
Last month, I purchase headset EPOC+ ([EPOC+](https://www.emotiv.com/product/emotiv-epoc-14-channel-mobile-eeg/)). I want to get raw data EEG to trial for research, how to way get it?

**Comment by nguoithichkhampha** [comment]
@phamkhactuy , to can get raw eeg data. we need a license. Please look at this page to understand our license model
[https://www.emotiv.com/developer/](url)
After that follow our docs to know how to get eeg data with Cortex API
[https://emotiv.github.io/cortex-docs/#introduction](url)

**Comment by phamkhactuy** [comment]
Thanks, I checked file on cortex-example/nodejs/src/numbers.js 
Please explain more data on console log (theta, alpha...) ? I dont understand this data is average raw data ?
This data is useful?

**Comment by nguoithichkhampha** [comment]
this is band power data, is not raw eeg data.
[https://en.wikipedia.org/wiki/Alpha_wave](url)

**Comment by phamkhactuy** [comment]
Thank you so much. I will read on your link. Please, please help me if I have trouble. I can contact via your email?

**Comment by nguoithichkhampha** [comment]
feel free contact with me if you have any trouble.
