### ISSUE TITLE
C# MotionLogger example not writing data to csv

### ISSUE THREAD

**Issue by Sollo01** [Emotiv/cortex-example#35]
Hello all, 
I've been trying to get the MotionLogger to work recently. While I am able to log in to my account and connect to my headset, once I exit and check the .csv where the data should be stored, all I see are the headers at the top-the rest is completely blank. Anyone know why this is happening?

**Comment by hoangphamemotiv** [comment]
Hi @Sollo01 . 
can you tell me what of headset type are you using ? and firmware version? did you use the lastest of SDK library?
we don't need to login EmotivID to get motion data.

**Comment by nguoithichkhampha** [comment]
@Sollo01 , did you can create session and subscribe motion data successfully ?

**Comment by Sollo01** [comment]
@nguoithichkhampha According to the log, I can create a session successfully, and while I don't see any message indicating that it has subscribed motion data, it does seem to successfully unsubscribe upon pressing enter. Here's what a the log reads when I try to get data:
`MOTION LOGGER
Please wear Headset with good signal!!!
Websocket Client Connected
Querry Headset successfully
Headset Connected
Selected HeadsetID EPOCPLUS-3B9AD8F7
Querry Headset successfully
Selected HeadsetID EPOCPLUS-3B9AD8F7
Username :sollo
Authorize successfully!!!. Access Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6IiIsImV4cCI6MTUzMzkwOTM4MCwiZmlyc3ROYW1lIjoiIiwibGFzdE5hbWUiOiIiLCJsaWNlbnNlSWQiOiIiLCJsaWNlbnNlU2NvcGUiOjEsImxpY2Vuc2VfYWdyZWVtZW50Ijp7ImFjY2VwdGVkIjpmYWxzZSwibGljZW5zZV91cmwiOiIifSwibGljZW5zZV9leHBpcmUiOjAsImxpY2Vuc2VfaGFyZExpbWl0IjowLCJsaWNlbnNlX3NvZnRMaW1pdCI6MCwibmJmIjoxNTMzNjUwMTgwLCJ1c2VyQ2xvdWRJZCI6LTEsInVzZXJuYW1lIjoiQmFzaWMifQ.fpGi9twxzfWMyYXEcmuYdB7Cyv_FRlI1SqlP_gdUvRs
Querry Profile Successfully
Create SESSION successfully
Querry Headset successfully
Selected HeadsetID EPOCPLUS-3B9AD8F7
Press Enter to exit
Querry Headset successfully
Selected HeadsetID EPOCPLUS-3B9AD8F7
Unsubscribe stream mot with session 5ac0a0b9-3873-4b8e-ae44-957b75a49f5b success
`

**Comment by nguoithichkhampha** [comment]
@Sollo01 , can you check mode of Epoc Plus headset ? call "[queryHeadsets](https://emotiv.github.io/cortex-docs/#queryheadsets)" to get this info.

**Comment by meta-meta** [comment]
I have a related issue trying to log motion data in node. I can subscribe to pow, mot and met but the only one that streams data is pow. `client.on('mot', onMot);` onMot never gets called. But `client.on('pow', onMot);` will log data constantly. 

I'm trying to use the EMOTIV EEG without the saline pads just to get motion data. Are the pads required?

```
const client = new Cortex({});

client.ready
  .then(() => client.init())
  .then(() => client.queryHeadsets().then((headsets) => {
    console.log(headsets)
  }))
  .then(() => client.authorize())
  .then(({ _auth }) => client.createSession({ _auth, status: 'open' }))
  .then(() => client.subscribe({ streams: ['pow', 'mot', 'met'] }))
  .then(subs => {
    console.log('boom', subs);
    const onMot = (ev) => {
      console.log(ev)
    };

    // client.on('pow', onMot);
    client.on('mot', onMot);
    // client.on('met', onMot);
  })
  .catch(err => console.error(err));
```

**Comment by meta-meta** [comment]
```
[ { connectedBy: 'dongle',
    dongle: '565',
    firmware: '565',
    id: 'EPOC-000000CC',
    label: '',
    motionSensors:
     [ 'GYROX',
       'GYROY',
       'GYROZ',
       'ACCX',
       'ACCY',
       'ACCZ',
       'MAGX',
       'MAGY',
       'MAGZ' ],
    sensors:
     [ 'AF3',
       'F7',
       'F3',
       'FC5',
       'T7',
       'P7',
       'O1',
       'O2',
       'P8',
       'T8',
       'FC6',
       'F4',
       'F8',
       'AF4' ],
    settings:
     { eegRate: 128, eegRes: 14, memsRate: 0, memsRes: 0, mode: 'EPOC' },
    status: 'connected' } ]
boom [ { pow: { cols: [Array] },
    sid: 'ae8e5918-9e1a-4e17-936e-de2656c1272b' },
  { mot: { cols: [Array] },
    sid: 'ae8e5918-9e1a-4e17-936e-de2656c1272b' },
  { met: { cols: [Array] },
    sid: 'ae8e5918-9e1a-4e17-936e-de2656c1272b' } ]
```
