### ISSUE TITLE
c# EEG Logger example generates Internal JSON-RPC error during authorize

### ISSUE THREAD

**Issue by sahin-ozsoy** [Emotiv/cortex-example#37]
Operating system: **Windows 10**
Last upstream commit: c221de76 6/24/2018
language version: **c#**
Cortex version:  latest
---

When I compile and run debug/release version of EEGLogger, I get this error during authorize:

Received: Internal JSON-RPC error.
Message Error recieved from CortexAccess.CortexClient
Recieved: -32603 : Internal JSON-RPC error.

double checked my user id / licence i. They are correct and licence up to date.

MotionLogger runs OK.
EmotivPro runs OK

Logged into the web site and under applications, I am getting this EULA agreement. I am pushing continue and nothing happens.

restarting cortex service does not help.

![errlog](https://user-images.githubusercontent.com/23072504/44064190-d7871878-9f31-11e8-94c6-42818b028c9f.jpg)

**Comment by patdotme** [comment]
hi @sahin-ozsoy, are you trying to run EmotivPRO and EEGLogger at the same time?
At the moment Cortex doesn't allow streaming to 2 apps concurrently so please try again with only the EEGLogger.

**Comment by sahin-ozsoy** [comment]
No, not at the same time.

**Comment by sahin-ozsoy** [comment]
I have made another test. I can get EEG data if I use the CommunitySDK. 
So, it seems that I can actually get eeg data from the device. 
But I am stuck with this Cortex API authorize function. Since CommunitySDK announced end of life as of 31 December 2018, I do not want to use it in the new design. And ideas?

**Comment by sahin-ozsoy** [comment]
Oh, that was the problem. I did not realized that they were there. This solved my issue. Thank you very much.
As a feedback, it would have been better if the cortex returned with a more explanatory error, rather than just saying "Internal JSON-RPC error". I have spent days trying to find a problem with JSON format and RPC messaging.

**Comment by miscrealitystudios** [comment]
how to register app and how should i get app id in visual studio @sahin-ozsoy

**Comment by bchaperon** [comment]
@miscrealitystudios To register a Cortex app, you must login to the Emotiv web site and go to this page https://www.emotiv.com/my-account/cortex-apps/

**Comment by miscrealitystudios** [comment]
Ok thanks.
I want to use the Emotiv's Unity 3d Support Pack which requires Password can you please mail me the required credentials at shubham.gupta@atmecs.com or sg83108@gmail.com.
My Order id is 342720
