### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by dfalagian** [Emotiv/cortex-example#38]
Operating system: Windows 
Last upstream commit (run `git log --author="Robert Lord" | head -n 1`): ✍️ TODO
language version:(nodejs version, ruby version ....) NodeJS
Cortex version:  ✍️ Last

---

Good Morning.
 
We have problems with authentication. As you can see with our user and use the PRO license, it gives an error.

We have detected that if we login with the Free account if it returns information about the headset. But with the user using PRO license gives error.

https://emotiv.github.io/cortex-docs/#login
We believe that it is a problem with the user.
Can you check it ???
image.png

It also returns error in requesting a full user:
https://emotiv.github.io/cortex-docs/#authorize
image.png
![error 1]

**Comment by bchaperon** [comment]
Hello @dfalagian 
On the first screenshot, you have an extra comma at the end of the "client_secret" line.
On the second screenshot, you are missing a comma at the end of the "license" line.
So your json requests are invalid.

**Comment by nguoithichkhampha** [comment]
@dfalagian , we found a mistake in our docs. we will update soon. And you should not publish client id/ client secret of your app.

**Comment by dfalagian** [comment]
OK
 Thanks
I erase the incidence

**Comment by patdotme** [comment]
@dfalagian the docs have been updated, please check again. Thanks!
