### ISSUE TITLE
Error in profile

### ISSUE THREAD

**Issue by dfalagian** [Emotiv/cortex-example#39]
Operating system: ✍️ Windows 
Last upstream commit (run `git log --author="Robert Lord" | head -n 1`): ✍️ TODO
language version:(nodejs version, ruby version ....) ✍️ C#
Cortex version:  ✍️ Last

---

We have an error in the moment of recovering the profiles in the users had been made in the emotional Xavier Control Panel 3.5.1. After trying a good time we could delete the profiles that were giving error.

Training Controler comes with values 0 and gives an error.
How can we solve this problem??
![error profile 1](https://user-images.githubusercontent.com/42551396/44383643-a96c1b80-a519-11e8-818d-9594623be65a.png)
![error profile 2](https://user-images.githubusercontent.com/42551396/44383644-aa04b200-a519-11e8-939d-5ed0dbc8447c.png)

**Comment by tungntEmotiv** [comment]
Hi @dfalagian,
Please pull the latest code and retry. We have some bug fixes recently. Thanks
