### ISSUE TITLE
Connect With Azuer

### ISSUE THREAD

**Issue by dfalagian** [Emotiv/cortex-example#40]
Operating system: ✍️ Windows
Last upstream commit (run `git log --author="Robert Lord" | head -n 1`): ✍️ TODO
language version:(nodejs version, ruby version ....) ✍️ CSharp
Cortex version:  ✍️ Last

---

Do you have an example to connect with Azure ??
Or some documentation ??

Thanks

**Comment by bchaperon** [comment]
Sorry @dfalagian I don't understand your question.
What are you trying to do exactly?
Are you talking about Microsoft Azure? Or another service/software?

**Comment by dfalagian** [comment]
Hi.
We want to connect with Microsoft Azure, to store the data.
We have searched for information but there is nothing. We need an example or documentation.

Thanks

**Comment by patdotme** [comment]
hi @dfalagian I believe if you want to store the data returned by Cortex to Azure you will need to consult the Microsoft Azure documentation instead of Cortex one.

https://azure.microsoft.com/en-us/services/storage/blobs/

**Comment by dfalagian** [comment]
Hi.
We are interested in storing the data in the Microsoft Azure cloud.
We know that you have to do it through WebSocket. Our intention was to see if you had some documentation or some example of the connection with Azure.

**Comment by bchaperon** [comment]
Cortex doesn't interact with Microsoft Azure in anyway, so we don't have any documentation or example for that.
