### ISSUE TITLE
Accept EULA without Cortex API Call

### ISSUE THREAD

**Issue by beefsuprimo** [Emotiv/cortex-example#42]
Is it possible to accept the EULA manually without using Cortex's acceptLicense method?
One account using the EmotivPro license can successfully create sessions, but another account is getting a "EULA has not been accepted by the user error...", even after registering a new application and successfully logging into EmotivPro.

**Comment by patdotme** [comment]
At the moment when you login to an Emotiv app it will pop-up the EULA acceptance dialog if you haven't accepted it. Do you have the same problem on EmotivBCI app?

**Comment by nguoithichkhampha** [comment]
@beefsuprimo , if you don't want to implement  acceptLicense on your app. You can let consumer acceptLicense manually on Cortex app. after that, they can use your app normally.
