### ISSUE TITLE
Unable to create a Cortex App for use in Qt Code

### ISSUE THREAD

**Issue by syami** [Emotiv/cortex-example#43]
Hi,

I am trying to create a cortex app on Emotiv site, so that I can use the Qt code. However I am unable to do so.
After trying to give an app name and do a 'Register Application', the site just says - "Client Secret" without actually giving any client secret. I tried using Chrome and Edge

thanks

**Comment by patdotme** [comment]
Hi @syami I just tried on Safari and seems to be working fine. The team will check other browsers as well. What’s your EmotivID? We can check it for you.

**Comment by bchaperon** [comment]
Hi @syami 

I just tried with Chrome and Edge on Windows 10, I was unable to reproduce that bug.
It also works fine on macOS using Chrome, Safari and Firefox.

Do you use any addone/plugin/adblocker that might interfere with the web page?
If yes, can you try to disable them all?

Also, even if the client secret is not visible on the page, can you try and click the "Copy to clipboard" link on the right, and then paste the content of your clipboard in a text editor?

Thanks for your feedback.

**Comment by nguoithichkhampha** [comment]
@syami ,
Could you please make a screen record on your machine and send for us. It will very useful for us find the issue.

**Comment by bchaperon** [comment]
@syami Did you change the email address linked to your Emotiv account recently?
If this is the case, then it is probably the cause of your problem.
Please, contact the Emotiv customer support, tell them your Emotiv id and your email address, they should be able to solve the problem.
https://www.emotiv.com/contact-support/
