### ISSUE TITLE
Socket error: QAbstractSocket::UnsupportedSocketOperationError

### ISSUE THREAD

**Issue by SeanYXWang** [Emotiv/cortex-example#44]
Operating system: ✍️ windows 10 education 64-bit
Last upstream commit (run `git log --author="Robert Lord" | head -n 1`): ✍️ TODO
language version:(nodejs version, ruby version ....) ✍️ C++
Cortex version:  ✍️ latest version

---

✍️ TODO write your issue here

Hi 

I run the cortex-example c++ code in the qt creator, get a socket error,  error output show below, I did not modify any code except the emotiv id, passwords and the EEG license key. ( and cortex id and secret)

I also tried to open the eeg.ext application from  
../cortex-example-master\cortex-example-master\build-cortexexamples-Desktop_Qt_5_10_1_MSVC2015_32bit-Debug\eeg\debug\eeg.exe

A message box pop up says missing qtwebsocketsd.dll.

Maybe when I compile the project I didnt link to the qt dlls? 

Could any developer help me with this please?

**qt creator application output below**

09:48:06: The program has unexpectedly finished.
09:48:06: The process was ended forcefully.

09:48:06: C:/Users/Sean/Downloads/cortex-example-master/cortex-example-master/build-cortexexamples-Desktop_Qt_5_10_1_MSVC2015_32bit-Debug/eeg/debug/eeg crashed.

09:48:06: Starting C:\Users\Sean\Downloads\cortex-example-master\cortex-example-master\build-cortexexamples-Desktop_Qt_5_10_1_MSVC2015_32bit-Debug\eeg\debug\eeg...

#####
Reminder: to subscribe to the EEG data stream, you must get an appropriate licence from Emotiv.
#####

Socket error: QAbstractSocket::UnsupportedSocketOperationError

**Comment by SeanYXWang** [comment]
HI @bchaperon 
I download openssl and installed it under C:\Program Files\OpenSSL-Win64
all dlls are copied at C:\Program Files\OpenSSL-Win64\bin

then I copy all dlls and correspond .lib files from openssl to the project directory
C:\Users\Sean\Downloads\cortex-example-master\cortex-example-master\eeg 

The same error shows again.

in your answer " download the openSSL DLLs, and put them in a folder where your Qt application can find them."  Would you mind tell me a bit more how to do this under qt creator

**Comment by bchaperon** [comment]
Hi @SeanYXWang 
Copying the DLL in the source folder will not work.
You have to copy them in a system folder, or a in folder that is in your Windows path.

To make things simple, just copy them into the bin folder of your Qt installation.
For example, if you installed Qt in c:\Qt, then you should have a folder like "C:\Qt\5.11.1\msvc2017_64\bin" or something similar.
This folder already contains all the Qt DLL, just add the OpenSSL DLL (no need for the .lib files)

**Comment by NihalKarne** [comment]
> Hi @SeanYXWang
> Copying the DLL in the source folder will not work.
> You have to copy them in a system folder, or a in folder that is in your Windows path.
> 
> To make things simple, just copy them into the bin folder of your Qt installation.
> For example, if you installed Qt in c:\Qt, then you should have a folder like "C:\Qt\5.11.1\msvc2017_64\bin" or something similar.
> This folder already contains all the Qt DLL, just add the OpenSSL DLL (no need for the .lib files)

Thanks this help me!
