### ISSUE TITLE
using cortex recording, how to align time of marker and time of eeg data

### ISSUE THREAD

**Issue by neoana** [Emotiv/cortex-example#46]
Hi @patdotme @nguoithichkhampha @jdpigeon @halybang :
For cortex API, when you want to inject a marker to the recording data, you should provide the marker label and the marker timestamp. This means, the cortex just records this two values. I don't know how the time of the marker is align to the time of eegdata.

For EmotivPro, during recording, when you give a marker, for example, press a key in the keyboard, the EmotivPro will detect the time when the key pressing happens, and then record the key value and the detected time. This makes sense.

However, for cortex recording, I don't know how it align the time of marker and the time of eegdata. What is the time framework of the eegdata, does the EPOCH timestamp of each eegdata point will also be recorded?

Thank you.

**Comment by patdotme** [comment]
Hi @neoana internally we will align the timestamp of the marker with the closest possible timestamp of EEG sample where we keep track of for each one of them.

**Comment by neoana** [comment]
Thank you. @patdotme 
When recorded eeg raw data through cortex API, the received data is like this:
[84.0,0.0,0.0,4034.0,4144.0,4358.0,3976.0,4113.0,4153.0,4297.0,4564.0,4051.0,4298.0,3903.0,4076.0,4179.0,3917.0,0.0,0.0],"sid":"37e37572-6120-42cc-b040-c4a743a4049b","time":4030.861}
Here, the 'time' is said equal to  "the time that data being received" - "the time cortex was started".
However, I can't get "the time cortex was started", so I can't get the true timestamp of each eeg data. currently, I just using the timestamp of the first received eeg data as zero time point. I don't know whether this will give me the precise time of each eeg data. Is it possible to get the exactly  "the time cortex was started"? Thank you

**Comment by nguoithichkhampha** [comment]
@neoana , currently don't have any way to get the time cortex was started. we know this issue and next version will return epoch time in milliseconds of each package.

**Comment by neoana** [comment]
That's great. Thank you @nguoithichkhampha
