### ISSUE TITLE
Get unix timestamp of eeg data recorded by EmotivPro software

### ISSUE THREAD

**Issue by neoana** [Emotiv/cortex-example#47]
Hi @halybang @nguoithichkhampha @patdotme @jdpigeon @NguyenDuyToan 
When recording eeg data using EmotivPro software, in the recorded file, the zero point of time is when the recording begins. Is it possible to get the unix timestamp of this recorded data? I think once we know exactly the timestamp of the record begins, we may know the timestamp of these recorded data.
I want to use this timestamp of eeg data to align the time of other signals.

Thank you

**Comment by patdotme** [comment]
hi @neoana in the exported file header from EmotivPRO you can found the Unix epoch time of the first sample. Adding the offset time of each sample then you will be able to get the Unix epoch time of each sample.

**Comment by neoana** [comment]
Thank you very much

**Comment by patdotme** [comment]
@neoana unfortunately that's the limitation of the EDF format which it doesn't save the millisecond part of the timestamp :(
We actually write the epoch time into the reserve field of the EDF header as well, you will need to change the code of the EDF reader in MATLAB in order to get that as it is non-standard.

**Comment by patdotme** [comment]
hi @neoana unfortunately standard EDF spec doesn't have a field to store that epoch time in the header, as you can see here:
https://www.edfplus.info/specs/edf.html

Currently we write the epoch time into the "44 ascii : reserved" field in the header, which are not supported by any standard EDF readers (they simply will skip the reserve field).

One way is to figure out the code to read the "8 ascii : number of bytes in header record" field in your EDF reader, and then insert the code to read the following bytes from reserve field to get the epoch time. You can open the EDF file with Notepad (Windows) or TextEdit (Mac), or with the "hexdump -C" command if you are on Mac / Linux, to examine the header contents to help debugging.

**Comment by AhmedAlhammadi65** [comment]
Dear Team, 

  Im trying to understand the timestamp given in the bp.csv file when reading the EEG signal. The timestamp given is like "1539449762.02387"

Question, is what does this number mean? 

How can i convert it to hh:mm:ss format?

Please support

Ahmed

**Comment by nguoithichkhampha** [comment]
@AhmedAlhammadi65 , this is epoch time in seconds.
This link for more details https://en.wikipedia.org/wiki/Unix_time
you can use some online tool convert it to iso format
https://www.epochconverter.com/
1539449762 -> GMT: Saturday, October 13, 2018 4:56:02 PM
