### ISSUE TITLE
[question] No sessions queried and how to access events

### ISSUE THREAD

**Issue by kubaper** [Emotiv/cortex-example#48]
Operating system: ✍️ windows 10
language version:(nodejs version, ruby version ....) ✍️ python
Cortex version:  ✍️ latest version

---

Hi, i'm trying to code something in python using cortex, but i encountered some problems. I use emotiv epoc+, connected by usb dongle, but without attached sensors for now.  I don't have any subscription, only basic license. 

1) When i call querysessions i recieve response:
{'id': 1, 'jsonrpc': '2.0', 'result': []}
Then i call createsession, it is succesfull but after that querysessions still looks the same:
{'id': 1, 'jsonrpc': '2.0', 'result': []}
I can subscribe to session without problems, but querysessions answer is always the same i do not understand why is that.

2) Could you please tell me how can i access events from the device? I subscribe to motion data and i have this response:
{'id': 1, 'jsonrpc': '2.0', 'result': [{'mot': {'cols': ['COUNTER', 'GYROX', 'GYROY', 'GYROZ', 'ACCX', 'ACCY', 'ACCZ', 'MAGX', 'MAGY', 'MAGZ']}, 'sid': 'fc3ec1c7-2ffe-486a-8ca2-d59632bbb659'}]}
How can i access events with actual data sent from the device? I didn't find answer in documentation. And I don't know whether this is somehow connected with 1) or not. 

3) In docs it is said that authorization is not needed to work with cortex, but almost all methods need auth token, so how is working possible without it? 

4) How can i accept license? I get this message when i try to do it with acceptlicense method:
{'error': {'code': 0, 'message': ''}, 'id': 1, 'jsonrpc': '2.0'}

**Comment by bchaperon** [comment]
Hello @kubaper 

2. After you subscribe, Cortex will simply send you the motion data, until you call unsubscribe.
All you have to do is to check for new messages on your web socket.

3. To get a token, you can call the authorize method, with no parameter.
Look for "Example: Anonymous authorize", on this page https://emotiv.github.io/cortex-docs/#authorize

**Comment by kubaper** [comment]
Thank you @bchaperon 
I realized that i can acquire other data types, but only "mot" stream doesn't send me anything. Maybe it's problem with gyroscope or something.

**Comment by nguoithichkhampha** [comment]
@kubaper which headset you are using ? it has enabled motion ?

**Comment by meta-meta** [comment]
Same problem over here but with node. No motion data.

```
[ { connectedBy: 'dongle',
    dongle: '565',
    firmware: '565',
    id: 'EPOC-000000CC',
    label: '',
    motionSensors:
     [ 'GYROX',
       'GYROY',
       'GYROZ',
       'ACCX',
       'ACCY',
       'ACCZ',
       'MAGX',
       'MAGY',
       'MAGZ' ],
    sensors:
     [ 'AF3',
       'F7',
       'F3',
       'FC5',
       'T7',
       'P7',
       'O1',
       'O2',
       'P8',
       'T8',
       'FC6',
       'F4',
       'F8',
       'AF4' ],
    settings:
     { eegRate: 128, eegRes: 14, memsRate: 0, memsRes: 0, mode: 'EPOC' },
    status: 'connected' } ]
```

**Comment by meta-meta** [comment]
ah, I see memsRate: 0. https://github.com/Emotiv/community-sdk/issues/113#issuecomment-230191724

**Comment by meta-meta** [comment]
How do I set this thing to send motion data?
