### ISSUE TITLE
Question: MentalCommandTraining C# How to make it work?

### ISSUE THREAD

**Issue by OttkO** [Emotiv/cortex-example#49]
Operating system: Windows 10
Last upstream commit (run `git log --author="Robert Lord" | head -n 1`): Not a git repository
language version:(nodejs version, ruby version ....) C#
Cortex version:  Latest

---
How exactly does example work?
I load a pre-defined profile.
I expect to see something like "Pull command detected" or "Push".
I have modified the code to look like this:
` static void Main(string[] args)
        {
            Console.WriteLine("MENTAL COMMAND TRAINING");
            Console.WriteLine("Please wear Headset with good signal!!!");

            Process p = new Process();
            Thread.Sleep(10000); //wait for querrying user login, query headset
            if (String.IsNullOrEmpty(p.GetUserLogin()))
            {
                p.Login(Username, Password);
                Thread.Sleep(5000); //wait for logining
            }
            // Show username login
            Console.WriteLine("Username :" + p.GetUserLogin());

            if (p.AccessCtr.IsLogin)
            {
                // Send Authorize
                p.Authorize();
                Thread.Sleep(5000); //wait for authorizing
            }
            if (!p.IsHeadsetConnected())
            {
                p.QueryHeadset();
                Thread.Sleep(10000); //wait for querying headset and create session
            }
            if (!p.IsCreateSession)
            {
                p.CreateSession();
                Thread.Sleep(5000);
            }
            if (p.IsCreateSession)
            {
                // Subcribe sys event
                p.SubcribeData("sys");
                Thread.Sleep(5000);
            }

            // Query Profile
            p.QuerryProfiles();
            Thread.Sleep(5000);
            if (p.IsProfilesExisted(ProfileName))
                p.LoadProfile(ProfileName);
            // get Detection Information
            while (true)
            {
                p.QuerryDetectionInfo("mentalCommand");
            }
           
        }`

Thank you in advance!

**Comment by tungntEmotiv** [comment]
Hi @OttkO 
Currently, we only support load profiles which created by Emotiv Application such as BCI. You can use getTrainedSignatureActions() api without sessionId to get trained actions. 
We haven't had example for the Api yet . But you can add some lines at TrainingController.cs as below
public void GetTrainedSignatureActions(string token, string detection, string sessionId, string profile)
        {
            // getTrainedSignatureActions
            JObject param = new JObject(
                    new JProperty("_auth", token),
                    new JProperty("detection", detection),
                    new JProperty("profile", "profile"));
            if (!string.IsNullOrEmpty(sessionId))
            {
                param.Add("session", sessionId);
            }
            CortexClient.Instance.SendTextMessage(param, (int)StreamID.TRAINING_STREAM, "getTrainedSignatureActions", true, (int)TrainingReqType.GET_TRAINED_SIGNATURE_ACTIONS);
        }
and in ParseData() function
 case (int)TrainingReqType.GET_TRAINED_SIGNATURE_ACTIONS:
                        Console.WriteLine("Get training signature action");
                        JArray jTrainingActionArr = (JArray)result["trained_actions"];
                        foreach (var item in jTrainingActionArr)
                        {
                            JObject trainingActionSig = (JObject)item;
                            string action = (string)trainingActionSig["action"];
                            Console.WriteLine("Action " + action);
                        }
                        break;
Thanks

**Comment by OttkO** [comment]
I did what you asked and also added:
      GET_TRAINED_SIGNATURE_ACTIONS = 45 to public enum TrainingReqType : int
Nevertheless, I just get:

MENTAL COMMAND TRAINING
Please wear Headset with good signal!!!
Websocket Client Connected
Headset Connected
Selected HeadsetID INSIGHT-XXXX
Selected HeadsetID INSIGHT-XXXX
Username :XXXXX
Authorize successfully!!!. Access Token XXXXX
Create SESSION successfully
Selected HeadsetID INSIGHT-XXXX
Querry Profile Successfully
Selected HeadsetID INSIGHT-XXXX
Load Profile Successfully
Selected HeadsetID INSIGHT-XXXX
Selected HeadsetID INSIGHT-XXXX

When will the new examples be available?

Thanks for the fast reply.

**Comment by OttkO** [comment]
This is my code:
   static void Main(string[] args)
        {
            Console.WriteLine("MENTAL COMMAND TRAINING");
            Console.WriteLine("Please wear Headset with good signal!!!");

            Process p = new Process();
            Thread.Sleep(10000); //wait for querrying user login, query headset
            if (String.IsNullOrEmpty(p.GetUserLogin()))
            {
                p.Login(Username, Password);
                Thread.Sleep(5000); //wait for logining
            }
            // Show username login
            Console.WriteLine("Username :" + p.GetUserLogin());

            if (p.AccessCtr.IsLogin)
            {
                // Send Authorize
                p.Authorize();
                Thread.Sleep(5000); //wait for authorizing
            }
            if (!p.IsHeadsetConnected())
            {
                p.QueryHeadset();
                Thread.Sleep(10000); //wait for querying headset and create session
            }
            if (!p.IsCreateSession)
            {
                p.CreateSession();
                Thread.Sleep(5000);
            }
            if (p.IsCreateSession)
            {
                // Subcribe sys event
                p.SubcribeData("com");
                Thread.Sleep(5000);
            }

            // Query Profile
            p.QuerryProfiles();
            Thread.Sleep(5000);
            if (p.IsProfilesExisted(ProfileName))
                p.LoadProfile(ProfileName);
            p.SubcribeData("com");
            // get Detection Information
            p.QuerryDetectionInfo("mentalCommand");


        }
    }
I don't understand if it is not in a while loop, how will it keep on polling the information?
It terminates after the code is executed.
The thread 0x41e8 has exited with code 0 (0x0).
The thread 0x424c has exited with code 0 (0x0).
The program '[11620] MentalCommandTraining.exe' has exited with code 0 (0x0).

PLEASE PROVIDE FULL WORKING EXAMPLE C# OR JAVA.

**Comment by OttkO** [comment]
I changed my code to call the code that you gave me above, but I get:
Load Profile Successfully
Received: Invalid profile name.
Message Error recieved from CortexAccess.CortexClient
Recieved: -32031 : Invalid profile name.

`    Console.WriteLine("MENTAL COMMAND TRAINING");
            Console.WriteLine("Please wear Headset with good signal!!!");
            Console.WriteLine("profilename is " + ProfileName);
            Process p = new Process();
            Thread.Sleep(10000); //wait for querrying user login, query headset
            if (String.IsNullOrEmpty(p.GetUserLogin()))
            {
                p.Login(Username, Password);
                Thread.Sleep(5000); //wait for logining
            }
            // Show username login
            Console.WriteLine("Username :" + p.GetUserLogin());

            if (p.AccessCtr.IsLogin)
            {
                // Send Authorize
                p.Authorize();
                Thread.Sleep(5000); //wait for authorizing
            }
            if (!p.IsHeadsetConnected())
            {
                p.QueryHeadset();
                Thread.Sleep(10000); //wait for querying headset and create session
            }
            if (!p.IsCreateSession)
            {
                p.CreateSession();
                Thread.Sleep(5000);
            }
            if (p.IsCreateSession)
            {
                // Subcribe sys event
                p.SubcribeData("com");
                Thread.Sleep(5000);
            }

            // Query Profile
            p.QuerryProfiles();
            Thread.Sleep(5000);
            if (p.IsProfilesExisted(ProfileName))
                p.LoadProfile(ProfileName);
             p.SubcribeData("com");

             Console.WriteLine("Querying");
             p.GetData("profile1");`


` public void GetData(string profile)
        {
            TrainingCtr.GetTrainedSignatureActions(GetAccessToken(), "mentalCommand", GetCurrentSessionID(), profile);
        }`

**Comment by OttkO** [comment]
I made it work:
I added the following:
case (int)StreamID.MENTAL_CMD_DATA_STREAM:
                    JArray wtf = (JArray)evt.Data["com"];
                    Console.WriteLine("Mental Data received: " + wtf[0]);
                    break;

to StreamDataReceived in Process.cs
You can now close this.
