### ISSUE TITLE
Question: How to resolve, "EULA hasn't been accepted by the user" error ?

### ISSUE THREAD

**Issue by prabalv** [Emotiv/cortex-example#51]
Operating system: ✍️ Windows 8
Last upstream commit (run `git log --author="Robert Lord" | head -n 1`): ✍️ 
language version:(nodejs version, ruby version ....) ✍️ C# 7.0
Cortex version:  ✍️ Latest

---

✍️ When I am trying to record raw EEG data using C# in Visual Studio, it is able to authorise itself, however it is showing that "EULA has not been accepted by the user". Can you please guide me to resolve this problem? Because of this it is recording something like"yyyyyyyyyyyyy" in csv file. I have attached a screenshot of the problem.
![problem](https://user-images.githubusercontent.com/22233249/47350650-edbf9780-d6d3-11e8-91e8-898190303e55.PNG)

Thanks in advance!

**Comment by tungntEmotiv** [comment]
Hi @prabalv ,

You might need use Cortex App to accept EULA one time for the account. We have released CortexApp at 
https://www.emotiv.com/developer/ . Free for developers.
Another way, you can use api https://emotiv.github.io/cortex-docs/#acceptlicense for accepting
