### ISSUE TITLE
Question: problem with profiles on server side? Profile creation/deletion errors. 

### ISSUE THREAD

**Issue by kubaper** [Emotiv/cortex-example#53]
Operating system: Win 10
language version:Python3
Cortex version:  latest

---
I have problems while working with profiles. When i try to create or delete training profile i always get:
ERROR -32036: Error processing profile.
But the funny thing is that the commands actually work. So profile is created/deleted, i can load and unload it later, just the response to create/delete command i get is always error. Is this just my case, or server problem? It is not comfortable to work with, because i won't know when errors actually occur.

**Comment by nguoithichkhampha** [comment]
Hi @kubaper , can you send me cortex token you got ?
