### ISSUE TITLE
issues with Profile management methods

### ISSUE THREAD

**Issue by landret** [Emotiv/cortex-example#54]
Operating system: windows 8.1
language version: java, using Netbeans
Cortex version:  latest

---

Hi team,
I am integrating Cortex in my java app. I am able to communicate with Cortex (user login, event,...). 
However, I am having trouble with the Profile management methods:

* queryProfile : it returns an empty array, while I created several profiles using EmotivBCI

* setupProfile : 
  - when I try to create a profile, it returns an error "code":-32031,"message":"Invalid profile name.", while I am using names like "test".
  - other thing : It is quite unclear if a command (create, save, load, unload,...) is occuring on the local machine or on Emotiv's server

thanks for your help

**Comment by bchaperon** [comment]
Hello @landret 

The setupProfile API create and saves profiles on your local machine.
But then, your profiles are automatically synchronized with the Emotiv server.

The error "Invalid profile name." usually means that you try to create a profile "test" when another profile with the same name already exists.

For the queryProfile, I don't have any explanation.
Do you run EmotivBCI and your Java code on the same computer, using the same EmotivID?

**Comment by landret** [comment]
Hello,
I met another issue, this time with Session management:

- query Sessions:
   * after successfully creating a Session with my headset, a query to Cortex returns an empty array of Sessions... This happens even when EmotivBCI is opened and getting feedback from the headset (so definitelly with an opened Session).

I used for this test both my app and a Firefox Websocket Client. Both gave same results.

**Comment by MichaelaCF** [comment]
I could solve the problem. Apparently you need the headset connected with the CortexUI and give the exact headset-id as param with the setupProfile request (just why?)

**Comment by nguoithichkhampha** [comment]
@MichaelaCF  @landret , did you authorize with Cortex as an anonymous user ? 
if this anonymous user can not access profile of current logged in user. So, queryProfile return empty.

**Comment by landret** [comment]
Hi,
I was indeed authorizing as an anonymous user. 
I have a client ID and a client Secret. However it looks like I also need to give Cortex a License ID (a client ID and a client Secret are not enough for Cortex), which I don't have. I am using the Basic License. How can I get a License ID for the Basic License?

**Comment by nguoithichkhampha** [comment]
@landret  actually, if you are using basic license. you don't need set param license id. You should login with your emotiv id and call authorize after.

**Comment by landret** [comment]
Hi, I am still having the issue with the QueryProfile and the SetupProfile methods... I am blocked now. Could you please tell me what I am doing wrong? Here is the sequence I follow with my basic license:

1) login with parameters : username, userpassword, clientID, clientSecret
2) anonymous authorize (with parameter : { } )
3) queryProfile with parameter: authentication key
or 3') setupProfile with parameters: authentication key, profileName

Just to mention it, I am able to subscribe to events.

**Comment by MichaelaCF** [comment]
@landret 
Sorry to hear it is still not working. I am not really able to help you, but what strikes me a little is the anonymous authorization. Have you tried authorizing with clientID and clientSecret? 
What I am doing is: 
- logging in with same params as you / or via CortexUI
- Authorize with dlientID, dlientSecret and debit (but I think you don't need debit)
- queryProfile with auth key

I still use emotivPro, but I think there should not be a difference for profile management.

**Comment by landret** [comment]
@MichaelaCF 
when authorizing with client id and client secret (no other parameters), Cortex returns an "Internal JSON-RPC error".

**Comment by NihalKarne** [comment]
I was having the same problem. I found the solution. For users having basic license this is the JSON required to be used : 
```
 {
    "jsonrpc": "2.0",
    "method": "authorize",
    "params": {
           "client_id": "your ID",
           "client_secret": "your client secret",
           "license" : "",
           "debt": 0
    },
    "id": 1
  }
```
This will allow to use the profile related APIs.

**Comment by landret** [comment]
@NihalKarne 
thanks nihal. Unfortunatelly, when I do that, Cortex returns an "Invalid License Key" error. I also tried not to mention the license parameter, but Cortex returns the same error.

**Comment by landret** [comment]
I just solve the issue. My current client ID and client Secret are not working. I just created a new set of client ID and secret by registering a "test" app in my Emotiv account, and now profile management is possible... 
I just can't figure out why my previous client ID and secret are not accepted (string size are correct at least)

**Comment by cedorland** [comment]
Solution to this issue is to add working client_id and client_secret to params when calling the method authorize.  
Fixed a similar problem for me as well. Might want to close the issue to let everyone know it has been solved.
