### ISSUE TITLE
Question: Multiple sessions cannot be activated on the same headset

### ISSUE THREAD

**Issue by ProjectProgramAMark** [Emotiv/cortex-example#55]
Operating system: MacOS Mojave (10.14.1)
language version: NodeJS
Cortex version: Latest

---

No matter what I try, I get the error "Multiple sessions cannot be activated on the same headset"

I have tried querying all of the sessions, closing them, and then calling createSession. I made sure it was synchronous as well; createSession is within the looped callback of querySession. I've attached  the relevant snippet of code below.

```
  client.ready.then(function() {
    client.init(auth)
    .then(res => {
      // console.log("init success response: ", res);
      // creating new session
      client.querySessions().then((res) => {
        console.log("successfully queried sessions: ");
        console.log(res);
        console.log("closing sessions");
        // making sure all sessions are closed before opening a new one
        var closePreviousSessions = function(res) {
          return new Promise(function(resolve, reject) {
            console.log("res.length is: ", res.length);
          if(res.length > 0) {
            for (var i = 0; i < res.length; i++) {
              var sessionID = res[i].id;
              console.log(res[i].id);
              if(res[i].status != "closed") {
                console.log("updating session status to closed");
                client.updateSession({ session: sessionID, status: "close" })
                .then((res) => {
                  console.log("successfully closed session: ", res.id);
                }, (err) => {
                  // console.log("error in closing session ", sessionID, ": ", err);
                  reject("error in closing session", sessionID, ": ", err);
                })
              }
            }
            resolve('Successfully closed all sessions');
          } else {
              resolve('No sessions present');
            }
          });
        }
      closePreviousSessions(res).then((res) => {
          console.log("all session statuses now: ");
          client.querySessions().then((res) => {console.log(res)});
          client.createSession({ status: "active" })
          .then((res) => {
            console.log("successfully created session");
            console.log(res);
            // DEBUGGING
            // console.log("getting current profile");
            // client.getCurrentProfile({ headset: res.headset.id }).then((res) => {console.log("current profile: ", res)}, (err) => {console.log("error getting current profile: ", err)})

            // subscribing to eeg data
            client.subscribe({ streams: ["eeg"] })
            .then((res) => {
              console.log("successfully subscribed to eeg");
              console.log(res);
            }, (err) => {
              console.log("error subscribing to eeg");
              console.log(err);
            }).then((res) => {
              client.updateSession({ session: res.id, status: "close" })
              .then((res) => {
                console.log("session is now closed");
              }, (err) => {
                console.log("error closing session");
              })
            })
          }, (err) => {
            console.log("error creating session: ");
            console.log(err);
          })
      }, (err) => {console.log("error error: ", err)});

      });
    }, (err) => console.log("error in initialization: ", err))
  }, function(err) {
    console.log(err);
  })
```

EDIT: Also another issue I just found that might be relevant to this one
When I query the session by status like this:

`client.querySessions({ status: "activated" })`

it still returns all sessions, regardless of status. I have tried variations, such as status: "active", status: "closed", "close", etc.

**Comment by nguoithichkhampha** [comment]
Hi @ProjectProgramAMark ,
For the query session with a condition. please look at this docs 
https://emotiv.github.io/cortex-docs/#querysessions
I think you are sending wrong param. in your case should send request:
`
{
  "jsonrpc": "2.0",
  "method": "querySessions",
  "params": {
    "_auth": "abcd",
    "query": {
      "status": "activated"
    }
  },
  "id": 1
}
`

**Comment by bchaperon** [comment]
Hello @ProjectProgramAMark 

'Stream unavailable' means that you don't have the appropriate license to subscribe to that stream.
In your code, I see that you want to get the EEG stream.
You need a PRO license to do that.
https://www.emotiv.com/developer/

**Comment by ProjectProgramAMark** [comment]
@bchaperon got it, I just switched over to another one (com). I'm still getting the "multiple sessions cannot be activated on the same headset," error however. I'm positive there are no sessions active (I'm querying both all of the sessions as well as only the ones that are activated, and getting 0 for both. It works sometimes, which is the weird thing. I get it to work in the very beginning pretty consistently for 2 or 3 times, and then it just starts being really weird with this. I'm even going through all of the sessions and updating them to "closed," just in case. But other than that I am really not sure.

**Comment by lhxstar** [comment]
Hi, I meet the same question. I want to know how do you to solve it？
