### ISSUE TITLE
Not able to run with sudo privileges?

### ISSUE THREAD

**Issue by ProjectProgramAMark** [Emotiv/cortex-example#58]
Operating system: MacOS Mojave (10.14.1)
language version: NodeJS
Cortex version: Latest

I'm using the Cortex API with NodeJS (ExpressJS to be specific). I need to open a TCP port and talk to it, and to do this, I need to run the server with sudo privileges. However, when I do this, the logging in part fails (when it doesn't if running without sudo). I get the error
`JSONRPCError: Incorrect user name or password`
If I have CortexUI on as well, it logs me out and makes me log back in, which breaks the process. Any way to get around this?

**Comment by bchaperon** [comment]
Sorry @ProjectProgramAMark I don't understand your question.
What do call the "Emotiv Server"? Do you mean the Cortex Service?

Anyway, running your application with sudo should not interfere with the logging process.
Can you trace the json messages from your app and make sure you send the correct user name and password?

**Comment by ProjectProgramAMark** [comment]
Yes, sorry, I meant the Cortex API. I am positive I am using the correct username and password. It works every other time when I'm running without sudo.

**Comment by nguoithichkhampha** [comment]
@ProjectProgramAMark , which part you run with sudo ? is your nodejs code ?
