### ISSUE TITLE
Question: How to use Emotiv on Max/MSP with NODE RED ?

### ISSUE THREAD

**Issue by Edvoy** [Emotiv/cortex-example#60]
@halybang @nguoithichkhampha @patdotme @jdpigeon @NguyenDuyToan @pstechfreak @prabalv @bchaperon

Hi Everybody !
It has been several weeks since using Emotiv with Max / MSP using the OSC protocol.
That's why I use NODE RED, but today Max/MSP just gets a "bang", instead of receiving digital data from the Emotiv headset!

I would like to receive digital data !
Do you have any idea how to solve this problem?

Have a nice day
Ed

<img width="1435" alt="unknown" src="https://user-images.githubusercontent.com/39824263/50009218-adcfaf00-ffb6-11e8-97e5-bb5f5caeaa71.png">

**Comment by Edvoy** [comment]
up

**Comment by duytan90** [comment]
Hey @Edvoy, you don't need to wire profile name with Performance Metric node since it doesn't associate with a training profile. Connect it directly to EMOTIV node, and add debug node to the output of Performance Metric node to debug, see any data was coming out from it?
