### ISSUE TITLE
authorization does not work on the QT corexclient program (error 32001 "Incorrect user name or password.") buy I have inputted my username and password in all of the visual studio programs

### ISSUE THREAD

**Issue by Adityarai10101** [Emotiv/cortex-example#61]
Operating system: ✍️ TODO
Last upstream commit (run `git log --author="Robert Lord" | head -n 1`): ✍️ TODO
language version:(nodejs version, ruby version ....) ✍️ TODO
Cortex version:  ✍️ TODO

---

✍️ TODO write your issue here

**Comment by Adityarai10101** [comment]
also what is a client id

**Comment by bchaperon** [comment]
To use Cortex, you need to create the client id and client secret to identify your application.
Go here to create them https://www.emotiv.com/my-account/cortex-apps/
Then input your client id an secret in SessionCreator.cpp, as explained in the [readme](https://github.com/Emotiv/cortex-example/blob/master/cpp-qt/README.md)
