### ISSUE TITLE
I am using the GitHub cpp/qt programs and am trying to run the training through qt. I have entered my username, password, client id, client secret and license key but the software is giving me and issue with my license key. What should I do? Additionally, what is the constant it speaks of in the error messages?

### ISSUE THREAD

**Issue by Adityarai10101** [Emotiv/cortex-example#62]
Operating system: ✍️ TODO
Last upstream commit (run `git log --author="Robert Lord" | head -n 1`): ✍️ TODO
language version:(nodejs version, ruby version ....) ✍️ TODO
Cortex version:  ✍️ TODO

---

✍️ TODO write your issue here

**Comment by Adityarai10101** [comment]
![code3qt](https://user-images.githubusercontent.com/46286306/50668160-fd384800-0f82-11e9-8ca6-093b28d35df2.png)
![code2](https://user-images.githubusercontent.com/46286306/50668162-ff020b80-0f82-11e9-87ab-2b0e617db3cc.png)
![code1](https://user-images.githubusercontent.com/46286306/50668164-00cbcf00-0f83-11e9-9237-14e88300f922.png)

**Comment by bchaperon** [comment]
Hello @Adityarai10101 
As mentioned in the [readme](https://github.com/Emotiv/cortex-example/blob/master/cpp-qt/README.md), you need to edit the variables at the beginning of the file SessionCreator.cpp
You don't need to edit CortexClient.h

And from your screenshot, it seems that you got the C++ syntax all wrong.
Do you have any experience in C++ programming?
