### ISSUE TITLE
MentalCommand is active, FacialExpression is active

### ISSUE THREAD

**Issue by landret** [Emotiv/cortex-example#63]
Operating system: windows 8.1
language version:(nodejs version, ruby version ....): java
Cortex version:  latest

---

Hi,
I created a java app with the former SDK. The SDK had 2 functions:
* EmoState.INSTANCE.IS_MentalCommandIsActive : for all Mental Commands
* EmoState.INSTANCE.IS_FacialExpressionIsActive : for each Facial Expression

How do I get access to these info with Cortex?
Thanks

**Comment by bchaperon** [comment]
Hello @landret 
These 2 functions are not available in the Cortex API.
In theory, the Facial Expression detection is always active. Except maybe if you have a really bad contact quality.
The Mental Command detection is active as soon as you load a profile that contains training for at least 1 action.

**Comment by cedorland** [comment]
For this, you should load your profile to a headset, and then open a session on that headset.
Then, subscribe to "com" stream for mental commands, or "fac" stream for facial expressions. Actions will be sent to you in near-real time as JSON objects.
Consult the Cortex API documentation for reference.
