### ISSUE TITLE
Question: How to calibrate motion sensor values in emotive insight and how we can use them to identify left and right head moment

### ISSUE THREAD

**Issue by sulemanbashir** [Emotiv/cortex-example#64]
I am working on emotive insight motion sensors. I am getting 9-axis values of emotive insight in this form

![image](https://user-images.githubusercontent.com/31032389/50734492-c0a65f80-11c1-11e9-9a5f-5797741ffbda.png)

**But I do not know how to calibrate these sensors in Cortex.**

**Comment by NihalKarne** [comment]
@sulemanbashir did u found the solution to this? I am facing the same issue.
