### ISSUE TITLE
how to use IEE_HeadsetGetGyroDelta(UserId, GyroX, GyroY) with new Cortex API

### ISSUE THREAD

**Issue by sulemanbashir** [Emotiv/cortex-example#65]
I am using Cortex API for accessing Motion Sensor data and now I want to calibrate gyroscope values so that I detect head movement. In Community-sdk **IEE_HeadsetGetGyroDelta(UserId, GyroX, GyroY)** used to calibrate gyroscope but how we call this in cortex API for gyroscope calibration.

**Comment by sulemanbashir** [comment]
@bchaperon

**Comment by bchaperon** [comment]
Hi @sulemanbashir 
Sorry, these 2 API are not available in Cortex.

**Comment by hoangphamemotiv** [comment]
hi @sulemanbashir 
these APIs is used to detect direction of the headset in 2D. but not exactly about amplitude physical of each directly. 
then, i think you can use Motion with 9 values of gyro, accelerometer, magnetometer, it is better to know exactly where the headset is in 3D. 
we will also support new Motion values with quaternion, accelerometer, magnetometer on new firmware versions

**Comment by sulemanbashir** [comment]
When will the new firmware release?

**Comment by hoangphamemotiv** [comment]
@sulemanbashir we released it and selling in the website. the new motion is feature of Epoc+ headset from headset version 0x630. Insight will be soon. 
Gyro (dps) = (value / 2^14) * (500 *2);
Acc (g) = (value / 2^14) * (4 *2);
Mag (gauss) = (value / 2^14) * (4 *2);

i don't remember the method 100%. but it is almost like that.

**Comment by sulemanbashir** [comment]
@hoangphamemotiv thank you for your guidance
I am using Insight and I will give try to this method

**Comment by hoangphamemotiv** [comment]
@landret
Yes, the first 4 are the quaternios. The 3 next values are ACC. And 3 last values are MAG. And they are g on ACC and gauss on MAG. This information should be in headset information in the website or document of Emotiv Pro.
For exactly direction X, Y, Z btw new epoc+ and old/other headset types i will check again and tell you later

**Comment by landret** [comment]
@hoangphamemotiv 
I tryed your conversion with my Insight, however, the results are not the same to those given by EmotivBCI.

**Comment by hoangphamemotiv** [comment]
@landret the conversion will convert from ADC to physical values. What did you get from emotivBCI. Sorry i haven't checked new features on BCI yet

**Comment by landret** [comment]
@hoangphamemotiv 
emotivBCI shows values stabilized around 0, varying +/-100 for the gyro and acc. While your method gives values stabilized around something else than 0 (like 200 for instance). For the mag, values are also different.

**Comment by hoangphamemotiv** [comment]
@landret the motion graph in BCI as you saw, we applied High Pass Filter to motion values. then you see it run around 0. the ranger is not exactly from -100 -> 100. it can be bigger when you move headset faster. i think we should improve max min of the graph in this case.
