### ISSUE TITLE
querySessions returns empty array

### ISSUE THREAD

**Issue by landret** [Emotiv/cortex-example#66]
Operating system: windows 8.1
language version: java
Cortex version: latest

---

Hi,
I am building a java app on a computer. 
I am able to create a session and then get its session ID, and then subscribe to events.
However, method querySessions always returns an empty array...

**Comment by landret** [comment]
I just solve this issue as well as my other profile management issue. My current client ID and client Secret are not working. I just created a new set of client ID and secret by registering a "test" app in my Emotiv account, and now querying sessions is possible... I just can't figure out why my previous client ID and secret are not accepted (string sizes are correct).

**Comment by cedorland** [comment]
You might've mistyped them - it can be especially tricky working with a client secret, as it only gets shown to you a single time.
If you fixed the issue, you might want to consider closing this thread.
