### ISSUE TITLE
Can't close activated session! (Session is not closed when headset is turned off) 

### ISSUE THREAD

**Issue by mfinger-irt** [Emotiv/cortex-example#67]
Hi, 
most of the time I want to connect to the headset with createSession I get the Error "Session limit has been reached..." 
So when I do querySession I indeed get an array with quite a big amount of sessions. 
Then I try to close all sessions with a updateSession query (one for each open session) containing auth, session-id, and "close" as value for the params. This gives me the error "Session does not exist".
I have no clue, what the problem here is... (it is definitely the correct id, since it is directly from the response to querySession) 

I am using the cortex wrapper and part of the raw.js from the node.js example from emotiv.

EDIT: I just noticed all the sessions listed seem to be old ones, that are already closed. Why are they all logged in query session? And why I am getting "Session limit has been reached for current device" if there is no active session?

I would highly appreciate any tips!

Best regards, 
Michaela

**Comment by MichaelaCF** [comment]
So, I filtered all the old sessions, and I found one that is still activated. 
Relevant part of the JSON response: 
[...]
"started":"2018-12-29T11:14:17.498757+01:00",
 "status":"activated",
 "stopped":"",
 "streams":null,
[...]

It stays activated even if I unplug the headset for more than one minute. 
When I try to close it manually with updateSession again I get the response "Session does not exist"

**Comment by cedorland** [comment]
You should be able to use `updateSession` without sending it a session ID, with the parameter `"status" : "closed"`. This will close the first active/open session it finds.
If you're worried about your sessions not closing property, catch your program's exit action (for example, clicking the red X at the top left of the program) and try closing the first active session.
Just a thought.

**Comment by MichaelaCF** [comment]
@cedorland 
Thank's for your reply! 
Unfortunately, it is both not working. When sending updateSession with "status":"close" I get "Invalid status" error (both times, when sending with or without sessionID). 
When sending updateSession with "status":"closed" (like in the docs), I get "Session does not exist (again both times, when sending it with or without sessionID)...
