### ISSUE TITLE
Load profile from EmotivBCI not working

### ISSUE THREAD

**Issue by cedorland** [Emotiv/cortex-example#68]
I have a connection to the server working in Java on MacOS.
I have a training profile saved using the EmotivBCI app. I've tried loading my profile, but it always says that my profile name is invalid. I have only saved one training profile, and it is named "Ciaran". Inputting "Ciaran" as the argument for param "profile" returns an error saying the profile name is incorrect.
When I query profiles after logging in, it returns an empty array.  
Do I have to create, train, save, and load profiles via WebSockets? I thought that I could train on the EmotivBCI app, then just load my training profile in my app to get mental commands data. Is this not possible?

**Comment by bchaperon** [comment]
Hi @cedorland 
Yes, you can create and train your profile in EmotivBCI and then use the profile in your app.
The problem is to know why queryProfile returns an empty array.
When you call the authorize API, do you provide your client secret and client id?

**Comment by bchaperon** [comment]
You can also have a look at this other ticket:
https://github.com/Emotiv/cortex-example/issues/54

**Comment by cedorland** [comment]
@bchaperon No, I hadn't been providing my client ID and client secret when I called to authorize. As noted in the API documentation, "Most features are available for free, however a subscription is required for professional and research features like Raw EEG data and high-resolution performance metrics. [...] If your application will use these features, you should provide the username and password of the appropriately licensed user when you call the authorize method." That makes it sound as though I shouldn't need to call authorize unless I'm accessing PRO features.
I will change my authorize call to include client ID, client secret, username and password, and try again.

**Comment by cedorland** [comment]
Thank you! After adding client_id and client_secret to my authorization call, everything works perfectly.
