### ISSUE TITLE
Profile field is always empty for createsession API.

### ISSUE THREAD

**Issue by NihalKarne** [Emotiv/cortex-example#69]
I have successfully loaded a trained profile in my WebSocket code. After that, I try to create a session using the following parameters: _auth, status, and headset. Session gets created but the profile key is always empty in that session. Shouldn't the profile key have the name of training profile I just setup using 'setupProfile' API? How to ensure that all the mental command detection is happening according to the specific profile. Or is it that we cannot set up a session wrt to a specific profile?

**Comment by cedorland** [comment]
Did you load your profile to the headset before opening a session?
You have to use setupProfile with the param "status" : "load" and also pass it the param "headset" : "(your headset ID)" before opening a session?
This loads your profile and associates it with that headset. When you open a session, you have to pass it the same headset ID. This will link your training profile with that session.

**Comment by NihalKarne** [comment]
@cedorland I have done the same thing. The profile is loaded before opening the session and I have used the same headset ID. To check I also used the 'getcurrentprofile' API which shows the name of profile I loaded, but the session is still not showing profile name. Why is that so?

**Comment by cedorland** [comment]
I just tested my program and when I create a session, the 'profile' field is always empty for me as well. It doesn't seem to matter, however - the session *is* connected to the intended profile, it just doesn't show up in the session's information. Sending and receiving information works as it should. This is interesting - it doesn't have any effect on my code, so it's not a bug in functionality, but it is a bug in diagnostics.

**Comment by bchaperon** [comment]
Hi @NihalKarne 
To check which profile is loaded for your headset, you can use the API [getCurrentProfile](https://emotiv.github.io/cortex-docs/#getcurrentprofile).

**Comment by NihalKarne** [comment]
@cedorland thanks for the reply, yes even though the field is empty it's not affecting the code. The intended profile is working.
@bchaperon Thanks I checked using 'getCurrentProfile' and it's showing the correct profile name. So I think I am good to go ahead.
