### ISSUE TITLE
Question: Control cursor movement and generate click event on browser.

### ISSUE THREAD

**Issue by athergeek** [Emotiv/cortex-example#7]
Operating system: ✍️ WINDOWS 10
Last upstream commit (run git log --author="Robert Lord" | head -n 1): ✍️ its coming blank -- just downloaded the code
language version:(nodejs version, ruby version ....) ✍️ nodejs
Cortex version: ✍️ Not sure, just downloaded the code

---

I need help from you gurus. I am trying to build an application where i need to control cursor and force a click event on browser. Probably i need to capture "mot" motion events but how to control cursor movement based on these values independent of resolution. And also i like to generate a click event as well may be when user focuses on something on screen.  I really need help here. its imprtant.Any help will greatly be appreciated.

**Comment by patdotme** [comment]
hi @athergeek - probably this project may give you some idea:
https://www.hackster.io/onyx/gesture-mouse-a4320a
