### ISSUE TITLE
Session limit on this device has been reached running Python example

### ISSUE THREAD

**Issue by miji** [Emotiv/cortex-example#70]
I'm trying to run _example.py_, but I get the error:

`lib.cortex.CortexApiException: {"error":{"code":-32019,"message":"Session limit on this device has been reached."},"id":8,"jsonrpc":"2.0"}`

However, there is no open session. Can you help me with this issue? See log:

[cortex.log](https://github.com/Emotiv/cortex-v2-example/files/4053289/cortex.log)

**Comment by vasyllyashkevych** [comment]
Your should change counter and you can do this in the way
if you use python:
insert new line (202) and set up the parameter "debit" = 33000 in the file "cortex.py"

![image](https://user-images.githubusercontent.com/17712632/74258306-c8a6cc00-4cfe-11ea-9f1d-df0feda90676.png)
