### ISSUE TITLE
closed session in Cortex

### ISSUE THREAD

**Issue by landret** [Emotiv/cortex-example#70]
Operating system: windows 8.1
language version: java
Cortex version:  latest

---
It looks like once created, and even if it is closed, a session will keep on appearing for a very long time in the session list returned by the querySessions method. This list is not reset even after a computer restart. After all my test, this list has now 30 closed sessions... My question is : how long will a closed session keeps on appearing in the list? Does Cortex make a reset of it at some point?

**Comment by cedorland** [comment]
I believe closed streams are kept so that you can still find information about them. If you don't want to see closed streams, you can query your streams with the param `"status" : "open"` or `"status" : "active"` to only receive information about open or active streams.

**Comment by HongweiN** [comment]
> I believe closed streams are kept so that you can still find information about them. If you don't want to see closed streams, you can query your streams with the param `"status" : "open"` or `"status" : "active"` to only receive information about open or active streams.
Yesterday，I ran this code to get the real-time data,but  and there was a mistake  about " Session limit has been reached for current device.". How can I deal with this question?

**Comment by bchaperon** [comment]
@HongweiN The session limit is linked to your license.
You should contact the [Emotiv customer support.](https://www.emotiv.com/contact-support/)
