### ISSUE TITLE
streams array in Session Data Type

### ISSUE THREAD

**Issue by landret** [Emotiv/cortex-example#71]
Operating system: windows 8.1
language version: java
Cortex version:  latest

---

When I subscribe to events for a session, the "streams" field value in this session remains "null". Is that normal?

**Comment by cedorland** [comment]
When you make a call to `subscribe`, are you sending it a `stream` parameter?
You should be sending it something like `"params": { [...] "stream" : "com" , [...] }` so that it knows what stream you want to receive.

**Comment by landret** [comment]
I do. And I do receive the events I requested. But the Session object in Cortex is not showing the subscribed streams.

**Comment by nguoithichkhampha** [comment]
> When I subscribe to events for a session, the "streams" field value in this session remains "null". Is that normal?
yes, it's normal. Actually, this is a field in the design but we don't implement yet.

**Comment by landret** [comment]
Thanks for the answer
