### ISSUE TITLE
Device limit problem.

### ISSUE THREAD

**Issue by NihalKarne** [Emotiv/cortex-example#72]
I tested my code on one laptop having windows 10 operating system. I have successfully authorized using clientID and clientSecret on this device. But when I tried to run the same code on another laptop I am getting this error for 'authorize' API with the same parameters :  
`{'error': {'code': -32022, 'message': 'You have exceeded the limit on the number of devices.'}, 'id': 103, 'jsonrpc': '2.0'}`

Why is this happening? Device limit is up to 3 devices with unlimited sessions for the basic license then why I am getting this message for using it with just one device?

**Comment by nguoithichkhampha** [comment]
@NihalKarne , what is your emotiv id and which cortex version you are using ?

**Comment by NihalKarne** [comment]
@nguoithichkhampha 
EmotivID : nihalk
I am not sure of the version. The EMotivBCI application of version 1.8.0 is installed on my system. How to check the version ?

**Comment by nguoithichkhampha** [comment]
when you get this error, can you tell me exactly time ?

**Comment by NihalKarne** [comment]
ok. Time isn't exact but it was yesterday (15 Jan 2019) around 14:30 India (9:00 AM GMT)

Actually, I wrote a code to detect eye blinks. For that, I established the connection using WebSockets. After that, I called authorize API to get _auth ID. And then continued the process to extract the stream. This code worked fine on my laptop. 
But when I tried to run the same code on another laptop with the same login I got this error during authorize API call.

**Comment by nguoithichkhampha** [comment]
thank you, can we setup a teamview session on the laptop you get the error ? Do you still can run project on the lap that work well before ?

**Comment by NihalKarne** [comment]
@nguoithichkhampha Thanks for the reply. Yes, the project runs fine on the first working device. Regarding teamview session right now I dont have that laptop. Is it possible to arrange the session tomorrow(17 Jan 2019) around 10:00 India (4:30 AM GMT) ?

**Comment by nguoithichkhampha** [comment]
As our system, you already active your license on 3 devices in 11 Jan 2019. So, your request on new laptop in 15 Jan 2019 return error.

**Comment by NihalKarne** [comment]
@nguoithichkhampha Ok thanks Is there any way to know these devices? Bcz as far as I can remember I just login using my ID only on two devices. I can't remember any third device or so.

Yes on 15 Jan I used 'nihalk' ID.

**Comment by nguoithichkhampha** [comment]
yes, your suggestion time is fine for teamwiew session. I have last question. Did you run emotiv product (emotiv bci/ emotiv pro) and the second laptop ?

**Comment by NihalKarne** [comment]
Yes, I do run emotivBCI on the second laptop.
Last week the code was running fine on both laptop.

**Comment by nguoithichkhampha** [comment]
you can email for me cuong@emotiv.com
