### ISSUE TITLE
Creating a Project

### ISSUE THREAD

**Issue by ml2305** [Emotiv/cortex-example#73]
Operating system: windows 10
language version: C# 
Cortex version: latest

Hi, 
I want to create a project in C# to get the performance metrics data from the headset. 
Do I need to put my emotiv id and secret only in the PerfLogger example project or in the CortexAccess project too?
And do I need a licenseID if I have a BASIC license?

I would appreciate it if you could explain to me how to create the PerfLogger project with a reference to the CortexAccess project.

Thanks for your help, 
Maor.

**Comment by mpueblaa** [comment]
Hello, 

Were you able to create a C# project that was able to log the Performance metrics data? If so, would you be able to explain to me how you did it?

Thank you
