### ISSUE TITLE
while opening project in visual studio blank screen is showing

### ISSUE THREAD

**Issue by miscrealitystudios** [Emotiv/cortex-example#74]
Operating system: ✍️ TODO
Last upstream commit (run `git log --author="Robert Lord" | head -n 1`): ✍️ TODO
language version:(nodejs version, ruby version ....) ✍️ TODO
Cortex version:  ✍️ TODO

---

✍️ TODO write your issue here

**Comment by bchaperon** [comment]
Sorry @miscrealitystudios I don't understand your issue.
I suppose you are trying to run the C# examples, is that correct?
What do you call a "blank screen"?
What version of Visual Studio do you use?
Are you able to compile and run the examples?
