### ISSUE TITLE
emotiv cortex dose not respond

### ISSUE THREAD

**Issue by asmasaad** [Emotiv/cortex-example#75]
Operating system: macOs version  10.13.6
Cortex service version: 1.8.357
cortex UI version: 1.8.97

---
after the last update of emotiv cortex  .
the cortex UI stop responding after I enter the password and emotv id 

 Thanks for your help

**Comment by cedorland** [comment]
We're going to need some more info to help you. I'm running the same versions of MacOS and Cortex and my program is working fine.
What *exactly* is happening? What does your code look like? What language are you using?

**Comment by asmasaad** [comment]
@cedorland  I am just trying to connect my headset using Cortex UI Application like what I did before the new update. so I entered my emotiv id and password then the program stops responding


also, I tried to install cortex in another MacOs laptop and still not work after I enter password and username

**Comment by bchaperon** [comment]
Hello @asmasaad
If your problem is related to Emotiv applications (CortexUI, EmotivPRO or EmotivBCI) then you should contact the [Emotiv customer support.](https://www.emotiv.com/contact-support/) 
They should be able to help you.
