### ISSUE TITLE
deal the streaming data as  in matlab for online analysis 

### ISSUE THREAD

**Issue by AnPang940** [Emotiv/cortex-example#76]
Operating system: win10 edu
language version:(nodejs version, ruby version ....) nodejs
Cortex version:  v1.7.1-x86

---
I can successfully obtain the data in matlab
It shows like
![matlab cortexui](https://user-images.githubusercontent.com/46832517/51422010-88037e80-1be2-11e9-8507-7fc6dbdc3a73.png)

then 
I want to  analyze the data by BCIlab in online analysis.
how can I deal with it? I can not find any data in workplace nor can I do anything for the BCIlab(GUI)
![Uploading 20190119121021.png…]()

**Comment by kinghaseo** [comment]
@AnPang940  Hey , I am sorry can you tell me how you obtained the data in matlab ? if possible can i have the reproductions steps please
