### ISSUE TITLE
Getting Error while running Facial Expression Example

### ISSUE THREAD

**Issue by miscrealitystudios** [Emotiv/cortex-example#78]
FACIAL EXPRESSION TRAINING
Please wear Headset with good signal!!!
Websocket Client Connected
Headset Connected
Selected HeadsetID EPOCPLUS-3B9AEB5A
Selected HeadsetID EPOCPLUS-3B9AEB5A
Username :arvrlab
Received: Internal JSON-RPC error.
Message Error recieved from CortexAccess.CortexClient
Recieved: -32603 : Internal JSON-RPC error.
Selected HeadsetID EPOCPLUS-3B9AEB5A
Received: Invalid auth token.
Message Error recieved from CortexAccess.CortexClient
Recieved: -32014 : Invalid auth token.
Received: Invalid auth token.
Message Error recieved from CortexAccess.CortexClient
Recieved: -32014 : Invalid auth token.

###### Train NEUTRAL Action
Selected HeadsetID EPOCPLUS-3B9AEB5A
Selected HeadsetID EPOCPLUS-3B9AEB5A
Selected HeadsetID EPOCPLUS-3B9AEB5A
Received: The JSON sent is not a valid Request object.
Message Error recieved from CortexAccess.CortexClient
Recieved: -32600 : The JSON sent is not a valid Request object.
Selected HeadsetID EPOCPLUS-3B9AEB5A
Received: The JSON sent is not a valid Request object.
Message Error recieved from CortexAccess.CortexClient
Recieved: -32600 : The JSON sent is not a valid Request object.
Selected HeadsetID EPOCPLUS-3B9AEB5A

###### Train SMILE Action
Received: The JSON sent is not a valid Request object.
Message Error recieved from CortexAccess.CortexClient
Recieved: -32600 : The JSON sent is not a valid Request object.
Selected HeadsetID EPOCPLUS-3B9AEB5A
Received: The JSON sent is not a valid Request object.
Message Error recieved from CortexAccess.CortexClient
Recieved: -32600 : The JSON sent is not a valid Request object.

**Comment by nguoithichkhampha** [comment]
from the log. I think the request you send is not json format.
