### ISSUE TITLE
C# Example using Microsoft Visual Studio Express

### ISSUE THREAD

**Issue by BrainVictory** [Emotiv/cortex-example#79]
I unzip the zip file and I navigate to the "csharp" folder and I open up  the CortexExamples.sln file.  Microsoft Visual Studio 2019 opens up with the project.  I press the start button to see what the example does and I get this message: "There were build errors. Would you like to continue and run the last successful build?"  I didn't make any changes in the code.  I just wanted to run it first to see what the example does before I started personalizing the program.  A couple years ago a wrote a program based off of the SDK that was here on GetHub for the emotiv using C#.  Emotiv is saying that values from the older SDK can't be trusted and so I am trying to see if I can do the same thing with this new Cortex, but I can't seem to get be able to get started.  Why do I get an error as soon as I run the example?  Thanks

**Comment by bchaperon** [comment]
Hi @BrainVictory 
What error message do you get during the build?
Did you follow the instructions from the readme file? https://github.com/Emotiv/cortex-v2-example/tree/master/csharp
Especially, did you use the Nuget Package Manager to install Newtonsoft.Json, SuperSocket.ClientEngine.Core, WebSocket4Net for CortexAccess project ?

**Comment by BrainVictory** [comment]
As you can see in the picture I have installed Newtonsoft.Json,
SuperSocket.ClientEngine.Core, WebSocket4Net for CortexAccess project and I
am still getting build errors in the CortexAccess project.  Something must
not have taken correctly.

[image: image.png]

Here are all my errors:

Severity

Code

Description

Project

File

Line

Suppression State

Suppression State

Error

CS0246

The type or namespace name 'Newtonsoft' could not be found (are you missing
a using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

4

Active

Error

CS0246

The type or namespace name 'JArray' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

19

Active

Error

CS0246

The type or namespace name 'JArray' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

19

Active

Error

CS0246

The type or namespace name 'JArray' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

24

Active

Error

CS0246

The type or namespace name 'JArray' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

25

Active

Error

CS0246

The type or namespace name 'JArray' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

48

Active

Error

CS0246

The type or namespace name 'JArray' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

57

Active

Error

CS0246

The type or namespace name 'JObject' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

108

Active

Error

CS0246

The type or namespace name 'JObject' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

109

Active

Error

CS0246

The type or namespace name 'JObject' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

110

Active

Error

CS0246

The type or namespace name 'JArray' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

118

Active

Error

CS0246

The type or namespace name 'JObject' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

120

Active

Error

CS0246

The type or namespace name 'JObject' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

152

Active

Error

CS0246

The type or namespace name 'JToken' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

241

Active

Error

CS0246

The type or namespace name 'JObject' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

582

Active

Error

CS0246

The type or namespace name 'JToken' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

626

Active

Error

CS0246

The type or namespace name 'JToken' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

626

Active

Error

CS0246

The type or namespace name 'JToken' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

626

Active

Error

CS0246

The type or namespace name 'JObject' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

677

Active

Error

CS0246

The type or namespace name 'JArray' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

677

Active

Error

CS0246

The type or namespace name 'JToken' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

677

Active

Error

CS0246

The type or namespace name 'JToken' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

677

Active

Error

CS0246

The type or namespace name 'JToken' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\CtxClient.cs

709

Active

Error

CS0246

The type or namespace name 'Newtonsoft' could not be found (are you missing
a using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\DataStreamExample.cs

1

Active

Error

CS0246

The type or namespace name 'JArray' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\DataStreamExample.cs

47

Active

Error

CS0246

The type or namespace name 'Newtonsoft' could not be found (are you missing
a using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\Headset.cs

1

Active

Error

CS0246

The type or namespace name 'JObject' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\Headset.cs

16

Active

Error

CS0246

The type or namespace name 'JObject' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\Headset.cs

24

Active

Error

CS0246

The type or namespace name 'JObject' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\Headset.cs

138

Active

Error

CS0246

The type or namespace name 'Newtonsoft' could not be found (are you missing
a using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\HeadsetFinder.cs

4

Active

Error

CS0246

The type or namespace name 'Newtonsoft' could not be found (are you missing
a using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\Record.cs

1

Active

Error

CS0246

The type or namespace name 'JArray' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\Record.cs

16

Active

Error

CS0246

The type or namespace name 'JArray' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\Record.cs

111

Active

Error

CS0246

The type or namespace name 'JObject' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\Record.cs

141

Active

Error

CS0246

The type or namespace name 'Newtonsoft' could not be found (are you missing
a using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\Training.cs

3

Active

Error

CS0246

The type or namespace name 'JArray' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\Training.cs

71

Active

Error

CS0246

The type or namespace name 'JObject' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\Training.cs

138

Active

Error

CS0246

The type or namespace name 'JObject' could not be found (are you missing a
using directive or an assembly reference?)

CortexAccess

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\Training.cs

181

Active

Error

CS0006

Metadata file
'C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\CortexAccess\bin\Debug\CortexAccess.dll'
could not be found

BandPowerLogger

C:\COrtex\cortex-v2-example-master\cortex-v2-example-master\csharp\BandPowerLogger\CSC

1

Active

Warning

The referenced component 'Newtonsoft.Json' could not be found.

CortexAccess

Warning

Could not resolve this reference. Could not locate the assembly
"Newtonsoft.Json". Check to make sure the assembly exists on disk. If this
reference is required by your code, you may get compilation errors.

CortexAccess

Warning

The referenced component 'Newtonsoft.Json' could not be found.

BandPowerLogger

Warning

Could not resolve this reference. Could not locate the assembly
"Newtonsoft.Json". Check to make sure the assembly exists on disk. If this
reference is required by your code, you may get compilation errors.

BandPowerLogger

**Comment by tungntEmotiv** [comment]
Hi @BrainVictory ,

As your log, the reference to "Newtonsoft.json" is broken. Please try to re-install the lib. You can refer to 
https://stackoverflow.com/questions/40416569/newtonsoft-could-not-be-found/40417243.
After reinstalling the library, please send us the result. Thanks
