### ISSUE TITLE
How to solve the authorization error?

### ISSUE THREAD

**Issue by masashi555** [Emotiv/cortex-example#8]
Operating system: Windows 7 Professional
language version: C++
Cortex version:  ?

The sample program of "eeg" shows error " "authorize" -32022 "You have exceeded the
limit on the number of devices"".

The programs could run until yesterday, and I didn't change the program at all.
I have only one Emotiv Epoc+ EEG headset. So I don't know why it says I have exceeded the limit on the number of devices.

Please let me know how to solve the problem.

**Comment by nguoithichkhampha** [comment]
hi @masashi555 , could you send me your emotiv id ?

**Comment by masashi555** [comment]
Hi @nguoithichkhampha ,
 Thanks. I sent my emotiv ID to your gmail.

**Comment by nguoithichkhampha** [comment]
Hi @masashi555, I received your email and checking with the team. Will give you the result soon.

**Comment by nguoithichkhampha** [comment]
Can you try your project again ? it should work right now.

**Comment by nguoithichkhampha** [comment]
As you said: "Yesterday, program runs, but to day it error". Can you confirm with me you work on same computer and don't change hardware of the computer ?

**Comment by hoangphamemotiv** [comment]
Hi @masashi555 
we are counting your device number depends hardware components of your PC. so do you tell me some update on your hardwares? or something like you use your PC at home or office...?

**Comment by masashi555** [comment]
Hi @nguoithichkhampha , @hoangphamemotiv 

Thank you so much. It works!!
I use the same computer, and I installed KB4091290 update program for Windows 7 the same day.
http://catalog.update.microsoft.com/v7/site/Search.aspx?q=KB4091290

I don't know how to check the Cortex version.

**Comment by cpizzolato** [comment]
@nguoithichkhampha @hoangphamemotiv 
I have a PRO License, 3 devices (EPOCH+) currently floating around the office and a couple of computer that I'm using for testing. Apparently I have exceeded the number of devices (3), as I receive the same error message when running the c++ example of the eeg streaming.

I would like to fix my account so I can use only a single device, but I will still be using a couple of computers for testing. I have also recently reimaged my computer, which may have created some miscounting with the number of installations. Do you think you could help?

**Comment by bchaperon** [comment]
@cpizzolato Please, contact the Emotiv customer support, they can fix it for you.
Don’t forget to give them your Emotiv id.
https://www.emotiv.com/contact-support/
