### ISSUE TITLE
I need help!!!

### ISSUE THREAD

**Issue by ml2305** [Emotiv/cortex-example#80]
Operating system: windows 10
language version: C#
Cortex version: latest

Hi, 
I opened a new project to get the performance metrics data from the headset and I provided my emotiv id and secret. I have the BASIC license. when I run the project it gives me a massage with error recieved from CortexAccess.CortexClient and it says:
Recieved: -32603 Internal JSON-RPC error.

What does it mean?

**Comment by ml2305** [comment]
Hi, here are the steps I followed: 

1. I downloaded the file from https://github.com/Emotiv/cortex-example 

2. I used Visual Studio to Open the project "PerfLogger" here - https://github.com/z3ro1/stuff/blob/master/emotiv_example/cortex-example/csharp/PerfLogger/Program.cs 

3. I inserted the Username and Password to this project. I didn't provide LicenseID because I have a BASIC license. 

4. I used Nuget Package Manager to install Newtonsoft.Json, SuperSocket.ClientEngine.Core, WebSocket4Net and NUnit for CortexAccess project (I had to install NUnit for the CortexClient file).

5. I added to the PerfLogger project a reference to the CortexAccess project. 

6. I created a cortex app in my emotiv account and got the clientId and ClientSecret. 

7. I inserted the clientID and ClientSecret to the AccessController file in the CortexAccess project. 

8. When I run the PerfLogger project, I get this error message - Received: Internal JSON-RPC error.
    Message Error recieved from CortexAccess.CortexClient
    Recieved: -32603 : Internal JSON-RPC error. 

What can I do? 
Did I miss something?
I need your help. 
Thanks.

**Comment by ml2305** [comment]
well I don't know how, but now it actually works.

**Comment by mpueblaa** [comment]
I have done the exact same steps as you have and am getting the same error. Did you do anything different to correct this?

**Comment by ml2305** [comment]
Well, 
I don't remember much of how I fixed it, I just remember that it eventually worked.
