### ISSUE TITLE
Failed to Opened session ontime

### ISSUE THREAD

**Issue by asmasaad** [Emotiv/cortex-example#81]
Operating system: ✍️ mac os 10.13.6
language version: c#
Cortex version:   

---
I try to run facial expression training and this appears in the output 
Failed to Opened session ontime
Websocket Client disconnect

**Comment by MKnierim** [comment]
Operating system: Mac os 10.11.6
language version: C#
Cortex (Service) version: 1.8.362

-----------------------------------

I am facing the same issue trying to run another example (EEGLogger) ... could this be a Mac related problem? Any other ideas?

**Comment by Jecheverria1997** [comment]
I am facing the same issue for all examples on Mac. Any possible solutions?
