### ISSUE TITLE
"authorize" Error: -32002 "Invalid license key"

### ISSUE THREAD

**Issue by aitoey** [Emotiv/cortex-example#83]
Operating system: Microsoft Windows 10 Enterprise
language version: C++
Cortex version:  v1.8.0

---

Hello, 

I am starting with this Emotiv cortex-examples following the "Readme" document.
As is written, I have created an app in order to get my clientID and clienSecret strings. I have wrote them in the "SessionCreator.cpp" file, with my username and password, but when I run the code I receive the following error message:

> 
Connected to Cortex.
Looking for headsets...
1 headset(s) found:
	 "EPOCPLUS-4A2C0009, connected (dongle)"
Cortex returned an error:
	 "authorize" -32002 "Invalid license key."
Disconnected.
 <

I have created different apps in order to see if there was an error with my clientID or the clientSecret but still not working.

In my account I have a BCI License, so if it is the "free" one, I believe that I am not supposed to write the license in the code. And as in our department we have a PRO license with what I can use the EmotivPRO software, I have tried to use the PRO license code with my emotivID but is not working neither.

I am trying to figure out which is the problem but I don't know it yet.

Thank you for your help, and sorry for the inconvenience,

AT.

**Comment by aitoey** [comment]
I already found the issue. I was just trying to run in Qt the "EEG" file, and as I said my user only has a BCI License, so I can't access to the eeg data with this user. I believe that I should use the one that bought the PRO license for all the department although I have the key.

**Comment by soufineyestani** [comment]
I faced the same problem, would you please let me know how you solved the problem.
