### ISSUE TITLE
"All subscriptions of session XXX was stopped by Cortex."

### ISSUE THREAD

**Issue by cedorland** [Emotiv/cortex-example#84]
OS: Windows 10 and MacOSX
Language: Java
Cortex version: Latest (not sure how to find out what version this is - updated this morning).
----------------------------------------------------------------------------------------------------------

My code was working fine until I updated to the latest version of Cortex. Now, a few seconds after subscribing to a session (only the "com" stream), and sometimes immediately after subscribing, I receive the following message:
`{"jsonrpc":"2.0","warning":{"code":0,"message":"All subscriptions of session (Session ID) was stopped by Cortex"}}`
This has never happened before and only changed once I updated Cortex to the latest version.

**Comment by cedorland** [comment]
This is the message received when you unsubscribe from a session - I'm going to leave this issue open to suggest that it is added to the documentation.
Something else I'd suggest adding: all sessions should be closed upon logging out, if they aren't already, and this should be noted in the Cortex documentation.

**Comment by nguoithichkhampha** [comment]
@cedorland thanks for your feedback, we will explain warning message in next version.
