### ISSUE TITLE
problem with work

### ISSUE THREAD

**Issue by areejhameed** [Emotiv/cortex-example#85]
hello..
i execute the example with my epoc+ and put my information in ( "license " : "EmotivPROStudent",
	"client_id" and "client_secret" , but it does not work . it connected successfully with headset but an error message had appears with license
how can i fix this ?
best regards

**Comment by nguoithichkhampha** [comment]
"license " should be your license key.

**Comment by areejhameed** [comment]
Thank youمرسل من هاتف Samsung Galaxy الذكي.
-------- الرسالة الأصلية --------من: Cuong Trinh Manh <notifications@github.com> التاريخ: ٢٠‏/٤‏/٢٠٢٠  ٩:٣٩ ص  (GMT+03:00) إلى: Emotiv/cortex-v2-example <cortex-v2-example@noreply.github.com> نسخة: areejhameed <areej.alanbary@gmail.com>, Author <author@noreply.github.com> الموضوع: Re: [Emotiv/cortex-v2-example] problem with work (#85) 
"license " should be your license key.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Emotiv/cortex-v2-example/issues/85#issuecomment-616342815",
"url": "https://github.com/Emotiv/cortex-v2-example/issues/85#issuecomment-616342815",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
