### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by areejhameed** [Emotiv/cortex-example#86]
hello..
pls. the following errors appeared to me and i don't know how to fix them.
could someone help me to solve them?
thanks
![error](https://user-images.githubusercontent.com/48274172/79699006-39390e80-8295-11ea-8a60-b09227f14642.jpg)

**Comment by nguoithichkhampha** [comment]
@areejhameed . did you define "license" in user object ? did you use our example code or write by yourself ? 
`user = {
	"license" : "your license",
	"client_id" : "your client id",
	"client_secret" : "your client ",
	"debit" : 100,
	"number_row_data" : 10
}`

**Comment by areejhameed** [comment]
thank you 

> @areejhameed . did you define "license" in user object ? did you use our example code or write by yourself ?
> `user = { "license" : "your license", "client_id" : "your client id", "client_secret" : "your client ", "debit" : 100, "number_row_data" : 10 }`

thank you ,
I used your code and put my personal license information in the user field above
