### ISSUE TITLE
Wrong Action when loading profile

### ISSUE THREAD

**Issue by abartolomei** [Emotiv/cortex-example#86]
Operating system: Windows 10
language version: C#
Cortex version:  v1.8.1

---

Wrong Action when loading profile

-Register a profile for example "test1" and action type PULL
-Register a second profile for example "test2" and action type PUSH

So i registered two profiles with two different actions.
When I load the "test2" profile, If I go to read the result of the response["com"] i return the action of the profile "test1", how is it possible?

**Comment by nguoithichkhampha** [comment]
which profile loaded when you get data from mental command stream ?

**Comment by abartolomei** [comment]
Thanks for your answer,
now with the p.UnSubcribeData("sys"); command I can recover the correct actions, but if I try to use the profile "test1", unsubscrive data and then load the "profilob" without making a new session \ login i get this error:   "**-32044 Current headset has linked with a profile.**"

is it always necessary to login / session every time I want to change profile?

**Comment by nguoithichkhampha** [comment]
@abartolomei you need to call "unload" profile "test1" before call load profile "test2"

**Comment by abartolomei** [comment]
thanks for the quick response, now work.
A greetin

Antonio



Il giorno mer 13 mar 2019 alle ore 12:33 Cuong Trinh Manh <
notifications@github.com> ha scritto:
