### ISSUE TITLE
RuntimeWarning: coroutine 'WebSocketCommonProtocol.close' was never awaited   self.websocket.close() RuntimeWarning: Enable tracemalloc to get the object allocation traceback

### ISSUE THREAD

**Issue by skshreyas4** [Emotiv/cortex-example#88]
There was a import error in Pycharm,which pycharm always had, so i removed the lib folder and moved the cortex file,now the cortex file is with other files,but when i run this example.py i am getting these warning as follows
RuntimeWarning: coroutine 'WebSocketCommonProtocol.close' was never awaited
  self.websocket.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
@nguoithichkhampha can you help me

**Comment by nguoithichkhampha** [comment]
@skshreyas4 , seems the structure of project is not correct. Can you run example from command line tool ?
