### ISSUE TITLE
When I run the process.cs from cortexexamples.sln I am able to create a session. However, I keep getting the "EEG data received" message and the training never begins HELP?!

### ISSUE THREAD

**Issue by binaryboi10101** [Emotiv/cortex-example#88]

**Comment by binaryboi10101** [comment]
I am sure I am making a silly mistake thus i wanted to see if anyone else is running into the same problem and any fixes others used

**Comment by nguoithichkhampha** [comment]
@binaryboi10101 , which project you run from cortexexamples.sln ? may you are running example get eeg data.

**Comment by binaryboi10101** [comment]
@nguoithichkhampha I am running process.cs
