### ISSUE TITLE
Dependency fo EmotivPro for Cortex

### ISSUE THREAD

**Issue by jascott11** [Emotiv/cortex-example#9]
I would like to better understand the role of the developer for 
emotiv. Right now I have the pro license simply so that I can have 
access to the raw data. Can I do the same with Cortex tools? Or is  the pro license required
in order to make use of the developer tools? 
The ongoing cost of the pro license is becoming prohibitive since my 
primary funding will expire in a few months. I would like to continue 
working on this educational project but I may not be able to. Or I may 
switch to a vendor that does not charge for the raw data.

**Comment by bchaperon** [comment]
Yes, you can access the raw EEG data with the Cortex API, see the [C++ eeg example](https://github.com/Emotiv/cortex-example/tree/master/cpp-qt)
But you still need a PRO license in order to do this.

The details are on the Emotiv web site [here](https://www.emotiv.com/developer/)
