### ISSUE TITLE
Error : "Application does not have permission to use the license."

### ISSUE THREAD

**Issue by Louislar** [Emotiv/cortex-example#90]
Operating system: Windows 10 Professional
language version: C#
Cortex version: Cortex Pro 1.8.1

Two week ago, my previous subscription was expired, so I ordered the new PRO License yesterday, not resubscribe, and also I got the new License Key.
But I meet the error "Application does not have permission to use the license."
I create the new Cortex Apps, but both old and new apps are send the same error.
What can I do?
What's the relation about the multi License and Cortex Apps?

**Comment by KroxXx** [comment]
https://www.emotiv.com/non-commercial-sdk-application-form/

Go and fill this form

**Comment by bchaperon** [comment]
Hi @Louislar,
The license to use EmotivPRO and the license to use the Cortex SDK are now 2 different licenses.
So as mentioned by @KroxXx, you need to apply for the SDK license after you get your PRO license.
