### ISSUE TITLE
Question: How "MOT" data is used to control Unity Camera?

### ISSUE THREAD

**Issue by sulemanbashir** [Emotiv/cortex-example#91]
I am trying to control camera movement in unity with Emotiv Insight inertial sensors. I am trying to use Gyroscope values to control camera. I converted the Gyro values to degree per second(dps). But how can I use these values to control camera in unity.

**Comment by hoangphamemotiv** [comment]
hi @sulemanbashir . 
i think the answer depends on your requirement also. 
- if you just simple want to know direction of headset moving, you can use Gyro easy 
ie: Gx > A . move to left.  Gx < -A move to right
- if you need more exactly how much of moving. you need write a algorithm base on Gyro, Acc, and Mag to detect orientation your headset in 3D. 
- if your requirement need to be exact as a compass, i suggest you use a new Epoc+ headset, which already support quaternion that you can use it

**Comment by hoangphamemotiv** [comment]
@sulemanbashir 
uhm. are you using Cortex or old SDK library. if you have already connected Cortex to Unity. can you share me your code of the connection? my email is hoang@emotiv.com
it is very useful for other users btw we haven't support Unity with Cortex yet

**Comment by sulemanbashir** [comment]
I will share it with you soon.
