### ISSUE TITLE
We have details of subscription of pow event but we dont have details of channels

### ISSUE THREAD

**Issue by waleedali430** [Emotiv/cortex-example#92]
Operating system: ✍️ TODO
Last upstream commit (run `git log --author="Robert Lord" | head -n 1`): ✍️ TODO
language version:(nodejs version, ruby version ....) ✍️ TODO
Cortex version:  ✍️ TODO

---

✍️ TODO write your issue here

**Comment by bchaperon** [comment]
Sorry @waleedali430 but I don't understand your question.
What do you mean by "details of channels" and "details of subscription"?
What information are you missing exactly?
