### ISSUE TITLE
Emotic Cortex chooses wrong license.

### ISSUE THREAD

**Issue by kennetao** [Emotiv/cortex-example#94]
Operating system: Windows 10 Home 1803 Build: 17134.590
language version:Norwegian
Cortex version:  CortexApp-Installer-v1.8.0-x86

---

I am trying to get raw eeg data from an Epoc+ headset, using python. I manage to log in to my cortex user, which has a trial pro license, and receive 'mot' data. But when I try to subscribe to 'eeg' it tells me my license does not have the correct privileges. When I check the license with the 'getLicenseInfo' method, the license_id does not match the license key listed online. 

In addition, when I try to subscribe to different streams it sometimes tells me I have too many subscription already. When I querySubscritions, I do get a tremendous amount of subscriptions. Are there any way to delete old subscritpions?

**Comment by kennetao** [comment]
I have now tried deleting and reinstalling all my emotiv programs, but it seems it still only uses the wrong license. When I am logged in to emotiv.com it only shows my prolicense.

**Comment by bchaperon** [comment]
Hi @kennetao 
When you call the authorize method, do you explicitly set your license id in the "license" field?
https://emotiv.github.io/cortex-docs/#authorize

**Comment by lost-beast** [comment]
i have the same issue, i am new to this device please tell me how to short out this problem
