### ISSUE TITLE
cannot find headset from mobile example

### ISSUE THREAD

**Issue by KhangSoCute** [Emotiv/cortex-example#94]
i am trying the cortex api in android through mobile example. i filled client_id, client_secret and even license_id  in Constant.java. i an connect to emotiv app in android, but when open example band power, it is any things in the list view Headset Name. Do you have any instruction in connect headset to cortex through mobile example ?

**Comment by nguoithichkhampha** [comment]
Cortex mobile still in beta testing. did you install Emotiv app on Android ?

**Comment by KhangSoCute** [comment]
yes, i installed and could find the headset by emotiv app

**Comment by nguoithichkhampha** [comment]
can you share your emotiv id and the email to register testing program ?

**Comment by KhangSoCute** [comment]
my emotiv id is tknhatkhang
the email is tknhatkhang@gmail.com

**Comment by nguoithichkhampha** [comment]
may you was confused the name of **Emotiv app**.
there is emotiv app you are using ?
https://play.google.com/store/apps/details?id=com.emotiv.insightapp

**Comment by KhangSoCute** [comment]
yes, i used it to connect the headset, was it right ?

**Comment by nguoithichkhampha** [comment]
this is app use old sdk. it is not designed to work with cortex example. if you want to try Cortex mobile, pls send request to mail  hello@emotiv.com
