### ISSUE TITLE
Timestamp sync

### ISSUE THREAD

**Issue by niteshbhatia008** [Emotiv/cortex-example#96]
The eeglogger program logs the eeg data where the first field corresponds to the time stamp. In my case, I get time stamps in the order of "1591919732.8508" which is equivalent to '09-Mar-8528 20:25:09'. Is there a way to sync these time stamps with the system time or ntp? I am also confused about addressing the latency if I take the system time. 
(Epoc+ user)

**Comment by hoangphamemotiv** [comment]
hi @niteshbhatia008 
about Emotiv EEG timestamp. Each of data sample (EEG, motion, detection) has a timestamp itself. a timestamp is a Epoch time point that a EEG was borned in the headset. it is already synced with system time. 
it is not affected by transmit time or any delay time from a buffer.
