### ISSUE TITLE
How can I distinguish between similar EEG signals?

### ISSUE THREAD

**Issue by sulemanbashir** [Emotiv/cortex-example#97]
I getting EEG signals with cortex API by using "pow" stream values that are very similar. The difference is only in amplitudes. However, they are coming from different cognitive processes. What are some methods, beside FFT, for distinguishing between two very similar signals in terms of statistical information? Please let me know. Thank you

Device: Emotiv Insight

**Comment by bchaperon** [comment]
Hi @sulemanbashir 
For this kind of question, please contact the [Emotiv customer support.](https://www.emotiv.com/contact-support/)
I am just a software engineer, not a neuro scientist :)
