### ISSUE TITLE
Connecting to cortex wss over external ip

### ISSUE THREAD

**Issue by niteshbhatia008** [Emotiv/cortex-example#97]
Hi,
In the examples, I see that connection ip is always "wss://localhost:6868" which implies that any app should be running locally. Is there a way to connect to cortex client service through global ip i.e. lan ip? For e.g. my machine has an ip address of 192.168.1.30 but connecting to "wss://192.168.1.30:6868" via cortex api fails. Any help or pointers would be appreciated. 
Regards,
Nitesh

**Comment by nguoithichkhampha** [comment]
@niteshbhatia008 , that is good idea.
we will consider support it in the future.
