### ISSUE TITLE
Facial Expression Event 

### ISSUE THREAD

**Issue by asmasaad** [Emotiv/cortex-example#98]
hello 
there are multiple events for facial expression training , 
in ( Emotive BCI ) the Facial expression training limited with time 8 second . and in c sharp example after 10 second fe_accept function was called . 
and when i wait for FE_Succeeded it takes 20 second to complete training  .
my question is what is the difference between FE_Accepted , FE_completed and FE_Succeeded event ?.

**Comment by bchaperon** [comment]
FE_Succeeded means that the training ran for 8 seconds, and the data collected during these 8 seconds is of good quality.
If the data collected during the 8 seconds is of poor quality, then the training is a failure and you receive the event FE_failed.

After you receive FE_Succeeded, you must call the training method with control "accept" to validate this training. Then you will receive the event FE_Succeeded.
